// Code generated by z. DO NOT EDIT.

package cafm_002_001_03

import (
	"bytes"
	"encoding/base64"
	"encoding/xml"
	"time"
)

type AdditionalData1 struct {
	Tp  Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tp,omitempty"`
	Val Max2048Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Val,omitempty"`
}

type AdditionalData2 struct {
	Tp   Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tp,omitempty"`
	Dtls []AdditionalData1 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Dtls,omitempty"`
}

type AdditionalFee3 struct {
	Tp                  TypeOfAmount21Code      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tp"`
	OthrTp              Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrTp,omitempty"`
	Prgm                Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Prgm,omitempty"`
	Dscrptr             Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Dscrptr,omitempty"`
	CdtDbt              CreditDebit3Code        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CdtDbt,omitempty"`
	Amt                 float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Amt"`
	Ccy                 ISO3NumericCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Ccy,omitempty"`
	RcncltnAmt          float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 RcncltnAmt,omitempty"`
	RcncltnCcy          ISO3NumericCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 RcncltnCcy,omitempty"`
	RcncltnFctvXchgRate float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 RcncltnFctvXchgRate,omitempty"`
	Assgnr              PartyType32Code         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Assgnr,omitempty"`
	OthrAssgnr          Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrAssgnr,omitempty"`
	Desc                Max140Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Desc,omitempty"`
}

type Address2 struct {
	AdrLine1         Max99Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AdrLine1,omitempty"`
	AdrLine2         Max99Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AdrLine2,omitempty"`
	StrtNm           Max99Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 StrtNm,omitempty"`
	BldgNb           Max16Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 BldgNb,omitempty"`
	PstlCd           Max16Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PstlCd,omitempty"`
	TwnNm            Max50Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 TwnNm,omitempty"`
	CtrySubDvsnMnr   ISOCountrySubDivisionCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CtrySubDvsnMnr,omitempty"`
	CtrySubDvsnMjr   ISOCountrySubDivisionCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CtrySubDvsnMjr,omitempty"`
	CtrySubDvsnMjrNm Max50Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CtrySubDvsnMjrNm,omitempty"`
	CtrySubDvsnMnrNm Max50Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CtrySubDvsnMnrNm,omitempty"`
	Ctry             ISOMax3ACountryCode       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Ctry,omitempty"`
}

// May be one of EA2C, E3DC, DKP9, UKPT, UKA1, EA9C, EA5C
type Algorithm13Code string

// May be one of HS25, HS38, HS51
type Algorithm20Code string

// May be one of EA2C, E3DC, EA9C, EA5C, EA2R, EA9R, EA5R, E3DR, E36C, E36R, SD5C
type Algorithm23Code string

// May be one of HS25, HS38, HS51
type Algorithm5Code string

// May be one of ERSA, RSAO
type Algorithm7Code string

// May be one of MGF1
type Algorithm8Code string

type AlgorithmIdentification25 struct {
	Algo  Algorithm23Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Algo"`
	Param Parameter7      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Param,omitempty"`
}

type AlgorithmIdentification26 struct {
	Algo  Algorithm8Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Algo"`
	Param Algorithm5Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Param,omitempty"`
}

type AlgorithmIdentification27 struct {
	Algo  Algorithm7Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Algo"`
	Param Parameter13    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Param,omitempty"`
}

type AlgorithmIdentification28 struct {
	Algo  Algorithm13Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Algo"`
	Param Parameter14     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Param,omitempty"`
}

// May be one of CNAT, LATT, OATT, OUAT, CATT
type AttributeType1Code string

type Authority1 struct {
	Ctry             ISO3NumericCountryCode    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Ctry,omitempty"`
	CtrySubDvsnMjr   ISOCountrySubDivisionCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CtrySubDvsnMjr,omitempty"`
	CtrySubDvsnMnr   ISOCountrySubDivisionCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CtrySubDvsnMnr,omitempty"`
	CtrySubDvsnMjrNm Max50Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CtrySubDvsnMjrNm,omitempty"`
	CtrySubDvsnMnrNm Max50Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CtrySubDvsnMnrNm,omitempty"`
	Nm               Max50Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Nm,omitempty"`
}

type BatchManagementInformation1 struct {
	ColltnId         Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ColltnId,omitempty"`
	BtchId           Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 BtchId"`
	MsgSeqNb         Max15NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 MsgSeqNb,omitempty"`
	MsgChcksmInptVal Max140Binary     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 MsgChcksmInptVal,omitempty"`
}

// May be one of LNGT, NUL8, NULG, NULL, RAND
type BytePadding1Code string

type CardData15 struct {
	PAN        Max19NumericText       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PAN,omitempty"`
	PrtctdPAN  bool                   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PrtctdPAN,omitempty"`
	CardSeqNb  Min2Max3NumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CardSeqNb,omitempty"`
	FctvDt     ISOYearMonth           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 FctvDt,omitempty"`
	XpryDt     ISOYearMonth           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 XpryDt,omitempty"`
	PmtAcctRef Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PmtAcctRef,omitempty"`
	PANRefIdr  Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PANRefIdr,omitempty"`
	PANAcctRg  Max19NumericText       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PANAcctRg,omitempty"`
	Ctry       ISO3NumericCountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Ctry,omitempty"`
	PdctTp     Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PdctTp,omitempty"`
	PdctSubTp  Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PdctSubTp,omitempty"`
	PrtflIdr   Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PrtflIdr,omitempty"`
	AddtlData  []AdditionalData1      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlData,omitempty"`
}

// May be one of ICPY, MGST, ICCY, MICR, MLEY, OCRR, MSIP, OPTC, OTHN, RFID, UNSP, OTHP, KEEN, DFLE
type CardDataReading10Code string

// May be one of UNKW, OTHN, OTHP, CAMR, KEEN, ICPY, OPTC, CDFL, MBNK, TOKN, ICCY
type CardDataReading9Code string

// May be one of ICPY, MGST, ICCY, MSIP, OTHN, UNSP, OTHP
type CardDataWriting1Code string

type CardReadingCapabilities1 struct {
	Cpblty     CardDataReading10Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Cpblty"`
	OthrCpblty Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrCpblty,omitempty"`
}

type CardWritingCapabilities1 struct {
	Cpblty     CardDataWriting1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Cpblty"`
	OthrCpblty Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrCpblty,omitempty"`
}

type Cardholder22 struct {
	Nm        CardholderName3   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Nm,omitempty"`
	Id        []Credentials3    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Id,omitempty"`
	Adr       Address2          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Adr,omitempty"`
	CtctInf   ContactPersonal1  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CtctInf,omitempty"`
	DtOfBirth ISODate           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DtOfBirth,omitempty"`
	HghVal    bool              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 HghVal,omitempty"`
	AddtlData []AdditionalData1 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlData,omitempty"`
	LclData   LocalData13       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LclData,omitempty"`
}

type CardholderName2 struct {
	Nm     Max140Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Nm,omitempty"`
	GvnNm  Max70Text  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 GvnNm,omitempty"`
	MddlNm Max70Text  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 MddlNm,omitempty"`
	LastNm Max70Text  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LastNm,omitempty"`
}

type CardholderName3 struct {
	Nm     Max70Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Nm,omitempty"`
	GvnNm  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 GvnNm,omitempty"`
	MddlNm Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 MddlNm,omitempty"`
	LastNm Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LastNm,omitempty"`
}

type CardholderVerificationCapabilities1 struct {
	Cpblty     CardholderVerificationCapability5Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Cpblty"`
	OthrCpblty Max35Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrCpblty,omitempty"`
}

// May be one of APKI, NOVF, FBIG, FBIO, FDSG, FCPN, FEPN, NBIO, NPIN, OTHN, OTHP, SIGN, UNSP, VORN, PKIS, NOPN, NOOP
type CardholderVerificationCapability5Code string

type CertificateIssuer1 struct {
	RltvDstngshdNm []RelativeDistinguishedName1 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 RltvDstngshdNm"`
}

type ContactPersonal1 struct {
	Nm         Max70Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Nm,omitempty"`
	GvnNm      Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 GvnNm,omitempty"`
	MddlNm     Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 MddlNm,omitempty"`
	LastNm     Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LastNm,omitempty"`
	HomePhne   PhoneNumber       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 HomePhne,omitempty"`
	BizPhne    PhoneNumber       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 BizPhne,omitempty"`
	MobPhne    PhoneNumber       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 MobPhne,omitempty"`
	OthrPhne   PhoneNumber       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrPhne,omitempty"`
	PrsnlEmail Max256Text        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PrsnlEmail,omitempty"`
	BizEmail   Max256Text        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 BizEmail,omitempty"`
	OthrEmail  Max256Text        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrEmail,omitempty"`
	HomeFax    PhoneNumber       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 HomeFax,omitempty"`
	BizFax     PhoneNumber       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 BizFax,omitempty"`
	URL        Max256Text        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 URL,omitempty"`
	Lang       ISO2ALanguageCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Lang,omitempty"`
}

type ContentInformationType41 struct {
	MACData MACData1          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 MACData"`
	MAC     Max8HexBinaryText `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 MAC"`
}

// May be one of DATA, SIGN, EVLP, DGST, AUTH
type ContentType2Code string

// May be one of EVLP, IFSE
type ContentType3Code string

// May be one of SMBS, OTHR, CORP
type CorporateTaxType1Code string

type CorrectionIdentification1 struct {
	Ind bool    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Ind,omitempty"`
	Dt  ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Dt,omitempty"`
	Tm  ISOTime `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tm,omitempty"`
}

type Credentials3 struct {
	Tp     ExternalAuthenticationMethod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tp"`
	OthrTp Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrTp,omitempty"`
	SubTp  Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 SubTp,omitempty"`
	Val    Max70Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Val"`
	XpryDt ISOYearMonth                      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 XpryDt,omitempty"`
	Assgnr Authority1                        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Assgnr,omitempty"`
}

// May be one of CRDT, DBIT
type CreditDebit3Code string

type CustomerDevice5 struct {
	Manfctr       Max70Text                              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Manfctr,omitempty"`
	ManfctrMdlId  Max70Text                              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ManfctrMdlId,omitempty"`
	Tp            CustomerDeviceType2Code                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tp,omitempty"`
	OthrTp        Max35Text                              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrTp,omitempty"`
	Lang          ISO2ALanguageCode                      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Lang,omitempty"`
	Phne          PhoneNumber                            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Phne,omitempty"`
	GeogcLctn     GeographicPointInDecimalDegrees        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 GeogcLctn,omitempty"`
	LctnCtryCd    ISO3NumericCountryCode                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LctnCtryCd,omitempty"`
	IPAdr         Max70Text                              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 IPAdr,omitempty"`
	Email         Max256Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Email,omitempty"`
	DvcNm         Max100Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DvcNm,omitempty"`
	DvcNmNrmlzd   Max100Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DvcNmNrmlzd,omitempty"`
	DvcId         []DeviceIdentification1                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DvcId,omitempty"`
	OprgSysId     Max70Text                              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OprgSysId,omitempty"`
	OprgSysTp     ExternalDeviceOperatingSystemType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OprgSysTp,omitempty"`
	OthrOprgSysTp Max35Text                              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrOprgSysTp,omitempty"`
	OprgSysVrsn   Max35Text                              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OprgSysVrsn,omitempty"`
	OprgSysBld    Max70Text                              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OprgSysBld,omitempty"`
	Prvdr         Max35Text                              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Prvdr,omitempty"`
	AddtlData     []AdditionalData1                      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlData,omitempty"`
}

// May be one of MOBL, OTHN, OTHP, PECR, TBLT, NSCR, SECR, EMBD, VHCL, WRBL, WATC, GAMB, JEWL, KFOB, STIC, UNKW
type CustomerDeviceType2Code string

type DataRecord1Choice struct {
	Binry []Max20MbBinary `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Binry,omitempty"`
	Txt   []Max10MbText   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Txt,omitempty"`
}

type DeviceIdentification1 struct {
	Tp     DeviceIdentificationType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tp,omitempty"`
	OthrTp Max35Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrTp,omitempty"`
	Id     Max70Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Id,omitempty"`
	Assgnr Max70Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Assgnr,omitempty"`
}

// May be one of IMEI, OTHN, OTHP, SEID, SENU
type DeviceIdentificationType1Code string

type DisplayCapabilities6 struct {
	Dstn      UserInterface1Code  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Dstn"`
	AvlblFrmt []OutputFormat1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AvlblFrmt,omitempty"`
	NbOfLines float64             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NbOfLines,omitempty"`
	LineWidth float64             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LineWidth,omitempty"`
	AvlblLang []string            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AvlblLang,omitempty"`
}

type Document struct {
	FileActnRspn FileActionResponseV03 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 FileActnRspn"`
}

type EncryptedContent8 struct {
	CnttTp         ContentType2Code          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CnttTp"`
	CnttNcrptnAlgo AlgorithmIdentification25 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CnttNcrptnAlgo"`
	NcrptdDataElmt []EncryptedDataElement2   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NcrptdDataElmt"`
}

type EncryptedData2 struct {
	Ctrl       Exact1HexBinaryText     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Ctrl,omitempty"`
	KeySetIdr  Max8NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeySetIdr,omitempty"`
	DrvdInf    Max32HexBinaryText      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DrvdInf,omitempty"`
	Algo       Max2NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Algo,omitempty"`
	KeyLngth   Max4NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyLngth,omitempty"`
	KeyPrtcn   Max2NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyPrtcn,omitempty"`
	KeyIndx    Max5NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyIndx,omitempty"`
	PddgMtd    Max2NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PddgMtd,omitempty"`
	NcrptdFrmt Max2NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NcrptdFrmt,omitempty"`
	NcrptdElmt []EncryptedDataElement2 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NcrptdElmt"`
}

type EncryptedData2Choice struct {
	Binry    Max100KBinary `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Binry,omitempty"`
	HexBinry string        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 HexBinry,omitempty"`
}

type EncryptedDataElement2 struct {
	Id               Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Id,omitempty"`
	Data             EncryptedData2Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Data"`
	ClearTxtFrmt     EncryptedDataFormat1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ClearTxtFrmt,omitempty"`
	OthrClearTxtFrmt Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrClearTxtFrmt,omitempty"`
}

// May be one of ASCI, BINF, EBCD, HEXF, OTHN, OTHP
type EncryptedDataFormat1Code string

// May be one of TR34, TR31, CTCE, CBCE
type EncryptionFormat3Code string

type EnvelopedData12 struct {
	Vrsn       float64            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Vrsn,omitempty"`
	Rcpt       []Recipient7Choice `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Rcpt"`
	NcrptdCntt EncryptedContent8  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NcrptdCntt,omitempty"`
}

// Must match the pattern ([0-9A-F][0-9A-F]){1}
type Exact1HexBinaryText string

// May be no more than 4 items long
type ExternalAuthenticationMethod1Code string

// May be no more than 4 items long
type ExternalDeviceOperatingSystemType1Code string

// May be no more than 4 items long
type ExternalMessageFunction1Code string

type FileActionResponseV03 struct {
	Hdr           Header71                        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Hdr"`
	Orgtr         PartyIdentification286          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Orgtr,omitempty"`
	Acqrr         PartyIdentification286          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Acqrr,omitempty"`
	Sndr          PartyIdentification286          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Sndr,omitempty"`
	Card          CardData15                      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Card"`
	Rcvr          PartyIdentification286          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Rcvr,omitempty"`
	Issr          PartyIdentification286          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Issr,omitempty"`
	Dstn          PartyIdentification286          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Dstn,omitempty"`
	Prgrmm        ProgrammeMode5                  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Prgrmm,omitempty"`
	SysTracAudtNb Max12NumericText                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 SysTracAudtNb"`
	TrnsmssnDtTm  ISODateTime                     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 TrnsmssnDtTm"`
	RtrvlRefNb    string                          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 RtrvlRefNb,omitempty"`
	LifeCyclId    string                          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LifeCyclId,omitempty"`
	FileNm        Max140Text                      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 FileNm,omitempty"`
	Frmt          OutputFormat5Code               `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Frmt,omitempty"`
	DataRcrd      DataRecord1Choice               `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DataRcrd,omitempty"`
	ActnDt        ISODate                         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ActnDt,omitempty"`
	FileSctyCd    Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 FileSctyCd,omitempty"`
	Crrctn        CorrectionIdentification1       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Crrctn,omitempty"`
	Accptr        PartyIdentification284          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Accptr,omitempty"`
	Termnl        Terminal7                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Termnl,omitempty"`
	POICmpnt      []PointOfInteractionComponent16 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 POICmpnt,omitempty"`
	Pyer          PartyIdentification287          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Pyer,omitempty"`
	Pyee          PartyIdentification287          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Pyee,omitempty"`
	Tkn           Token2                          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tkn,omitempty"`
	CstmrDvc      CustomerDevice5                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CstmrDvc,omitempty"`
	Wllt          Wallet3                         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Wllt,omitempty"`
	Crdhldr       Cardholder22                    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Crdhldr,omitempty"`
	Jursdctn      Jurisdiction2                   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Jursdctn,omitempty"`
	SttlmSvc      SettlementService6              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 SttlmSvc,omitempty"`
	AddtlFee      []AdditionalFee3                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlFee,omitempty"`
	Rcncltn       Reconciliation4                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Rcncltn,omitempty"`
	AddtlData     []AdditionalData2               `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlData,omitempty"`
	RspnCd        ISO8583ResponseCode             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 RspnCd"`
	PrtctdData    []ProtectedData2                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PrtctdData,omitempty"`
	SplmtryData   []SupplementaryData1            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 SplmtryData,omitempty"`
	SctyTrlr      ContentInformationType41        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 SctyTrlr,omitempty"`
}

type FinancialInstitution8 struct {
	Id        Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Id,omitempty"`
	Nm        Max70Text   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Nm,omitempty"`
	Adr       Address2    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Adr,omitempty"`
	Email     Max256Text  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Email,omitempty"`
	URL       Max256Text  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 URL,omitempty"`
	Phne      Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Phne,omitempty"`
	CstmrSvc  Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CstmrSvc,omitempty"`
	AddtlCtct Max256Text  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlCtct,omitempty"`
	LclData   LocalData10 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LclData,omitempty"`
}

// May be one of YEAR, DAIL, FRTN, MNTH, QURT, MIAN, TEND, WEEK
type Frequency12Code string

type GenericIdentification183 struct {
	Id     Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Id"`
	Tp     PartyType17Code     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tp,omitempty"`
	OthrTp Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrTp,omitempty"`
	Assgnr PartyType18Code     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Assgnr,omitempty"`
	Ctry   ISOMax3ACountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Ctry,omitempty"`
	ShrtNm Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ShrtNm,omitempty"`
}

// Must match the pattern (\+|-)?[\d]{1,3}(\.[\d]{1,8})?/(\+|-)?[\d]{1,3}(\.[\d]{1,8})?
type GeographicPointInDecimalDegrees string

type Header71 struct {
	MsgFctn        ExternalMessageFunction1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 MsgFctn"`
	PrtcolVrsn     Max2048Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PrtcolVrsn"`
	XchgId         Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 XchgId,omitempty"`
	ReTrnsmssnCntr Max3NumericText              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ReTrnsmssnCntr,omitempty"`
	CreDtTm        ISODateTime                  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CreDtTm"`
	BtchMgmtInf    BatchManagementInformation1  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 BtchMgmtInf,omitempty"`
	InitgPty       GenericIdentification183     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 InitgPty"`
	RcptPty        GenericIdentification183     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 RcptPty,omitempty"`
	TracData       []AdditionalData1            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 TracData,omitempty"`
	Tracblt        []Traceability10             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tracblt,omitempty"`
}

// Must match the pattern [a-z]{2,2}
type ISO2ALanguageCode string

// Must match the pattern [0-9]{3,3}
type ISO3NumericCountryCode string

// Must match the pattern [0-9]{3,3}
type ISO3NumericCurrencyCode string

// Must match the pattern [0-9A-Z]{2,2}
type ISO8583ResponseCode string

// Must match the pattern [A-Z]{2,3}
type ISOCountrySubDivisionCode string

type ISODate time.Time

func (t *ISODate) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t ISODate) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type ISODateTime time.Time

func (t *ISODateTime) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t ISODateTime) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

// Must match the pattern [A-Z]{2,3}
type ISOMax3ACountryCode string

// Must match the pattern [a-z]{2,3}
type ISOMax3ALanguageCode string

type ISOTime time.Time

func (t *ISOTime) UnmarshalText(text []byte) error {
	return (*xsdTime)(t).UnmarshalText(text)
}
func (t ISOTime) MarshalText() ([]byte, error) {
	return xsdTime(t).MarshalText()
}

type ISOYearMonth time.Time

func (t *ISOYearMonth) UnmarshalText(text []byte) error {
	return (*xsdGYearMonth)(t).UnmarshalText(text)
}
func (t ISOYearMonth) MarshalText() ([]byte, error) {
	return xsdGYearMonth(t).MarshalText()
}

type IssuerAndSerialNumber1 struct {
	Issr  CertificateIssuer1 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Issr"`
	SrlNb Max35Binary        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 SrlNb"`
}

type Jurisdiction2 struct {
	DmstInd    bool      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DmstInd,omitempty"`
	DmstQlfctn Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DmstQlfctn,omitempty"`
}

type KEK6 struct {
	Vrsn          float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Vrsn,omitempty"`
	KEKId         KEKIdentifier6            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KEKId"`
	KeyNcrptnAlgo AlgorithmIdentification28 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyNcrptnAlgo"`
	NcrptdKey     Max500Binary              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NcrptdKey,omitempty"`
}

type KEKIdentifier2 struct {
	KeyId     Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyId"`
	KeyVrsn   Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyVrsn"`
	SeqNb     float64         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 SeqNb,omitempty"`
	DerivtnId Min5Max16Binary `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DerivtnId,omitempty"`
}

type KEKIdentifier6 struct {
	KeyId     Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyId"`
	KeyVrsn   Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyVrsn,omitempty"`
	SeqNb     float64         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 SeqNb,omitempty"`
	DerivtnId Min5Max16Binary `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DerivtnId,omitempty"`
}

type KeyTransport6 struct {
	Vrsn          float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Vrsn,omitempty"`
	RcptId        Recipient5Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 RcptId"`
	KeyNcrptnAlgo AlgorithmIdentification27 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyNcrptnAlgo"`
	NcrptdKey     Max5000Binary             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NcrptdKey"`
}

type LocalAddress1 struct {
	AdrLine1         Max200Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AdrLine1,omitempty"`
	AdrLine2         Max200Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AdrLine2,omitempty"`
	StrtNm           Max200Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 StrtNm,omitempty"`
	BldgNb           Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 BldgNb,omitempty"`
	PstlCd           Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PstlCd,omitempty"`
	TwnNm            Max100Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 TwnNm,omitempty"`
	CtrySubDvsnMnrNm Max100Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CtrySubDvsnMnrNm,omitempty"`
	CtrySubDvsnMjrNm Max100Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CtrySubDvsnMjrNm,omitempty"`
}

type LocalData10 struct {
	Lang      ISOMax3ALanguageCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Lang"`
	NcodgFrmt Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NcodgFrmt,omitempty"`
	Nm        Max70Text            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Nm,omitempty"`
	Adr       LocalAddress1        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Adr,omitempty"`
	AddtlCtct Max512Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlCtct,omitempty"`
	AddtlData []AdditionalData1    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlData,omitempty"`
}

type LocalData11 struct {
	Lang      ISOMax3ALanguageCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Lang"`
	NcodgFrmt Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NcodgFrmt,omitempty"`
	ShrtNm    Max70Text            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ShrtNm,omitempty"`
	LglCorpNm Max210Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LglCorpNm,omitempty"`
	NmAndLctn Max200Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NmAndLctn,omitempty"`
	Adr       LocalAddress1        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Adr,omitempty"`
	AddtlAdr  Max512Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlAdr,omitempty"`
	AddtlCtct Max512Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlCtct,omitempty"`
	AddtlData []AdditionalData1    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlData,omitempty"`
}

type LocalData13 struct {
	Lang      ISOMax3ALanguageCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Lang"`
	NcodgFrmt Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NcodgFrmt,omitempty"`
	Nm        CardholderName2      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Nm,omitempty"`
	Adr       LocalAddress1        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Adr,omitempty"`
	AddtlData []AdditionalData1    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlData,omitempty"`
}

type LocalData14 struct {
	Lang      ISOMax3ALanguageCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Lang"`
	NcodgFrmt Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NcodgFrmt,omitempty"`
	ShrtNm    Max70Text            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ShrtNm,omitempty"`
	LglCorpNm Max210Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LglCorpNm,omitempty"`
	AddtlData []AdditionalData1    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlData,omitempty"`
}

type LocalData15 struct {
	Lang      ISOMax3ALanguageCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Lang"`
	NcodgFrmt Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NcodgFrmt,omitempty"`
	Nm        CardholderName2      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Nm,omitempty"`
	Adr       LocalAddress1        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Adr,omitempty"`
	AddtlData []AdditionalData1    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlData,omitempty"`
}

type MACData1 struct {
	Ctrl         Exact1HexBinaryText `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Ctrl"`
	KeySetIdr    Max8NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeySetIdr"`
	DrvdInf      Max32HexBinaryText  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DrvdInf,omitempty"`
	Algo         Max2NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Algo"`
	KeyLngth     Max4NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyLngth,omitempty"`
	KeyPrtcn     Max2NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyPrtcn,omitempty"`
	KeyIndx      Max5NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyIndx,omitempty"`
	PddgMtd      Max2NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PddgMtd,omitempty"`
	InitlstnVctr Max32HexBinaryText  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 InitlstnVctr,omitempty"`
}

type Max100KBinary []byte

func (t *Max100KBinary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max100KBinary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be no more than 100 items long
type Max100Text string

// May be no more than 10000000 items long
type Max10MbText string

// Must match the pattern [0-9]{1,11}
type Max11NumericText string

// Must match the pattern [0-9]{1,12}
type Max12NumericText string

type Max140Binary []byte

func (t *Max140Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max140Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be no more than 140 items long
type Max140Text string

// Must match the pattern [0-9]{1,15}
type Max15NumericText string

// May be no more than 16 items long
type Max16Text string

// Must match the pattern [0-9]{1,19}
type Max19NumericText string

// May be no more than 200 items long
type Max200Text string

// May be no more than 2048 items long
type Max2048Text string

type Max20MbBinary []byte

func (t *Max20MbBinary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max20MbBinary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be no more than 210 items long
type Max210Text string

// May be no more than 256 items long
type Max256Text string

// Must match the pattern [0-9]{1,2}
type Max2NumericText string

// Must match the pattern ([0-9A-F][0-9A-F]){1,32}
type Max32HexBinaryText string

// May be no more than 350 items long
type Max350Text string

type Max35Binary []byte

func (t *Max35Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max35Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be no more than 35 items long
type Max35Text string

// Must match the pattern [0-9]{1,3}
type Max3NumericText string

// Must match the pattern [0-9]{1,4}
type Max4NumericText string

type Max5000Binary []byte

func (t *Max5000Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max5000Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

type Max500Binary []byte

func (t *Max500Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max500Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be no more than 50 items long
type Max50Text string

// May be no more than 512 items long
type Max512Text string

// Must match the pattern [0-9]{1,5}
type Max5NumericText string

// May be no more than 70 items long
type Max70Text string

// Must match the pattern ([0-9A-F][0-9A-F]){1,8}
type Max8HexBinaryText string

// Must match the pattern [0-9]{1,8}
type Max8NumericText string

// May be no more than 99 items long
type Max99Text string

// Must match the pattern [0-9]{2,3}
type Min2Max3NumericText string

type Min5Max16Binary []byte

func (t *Min5Max16Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Min5Max16Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be one of OFLN, ONLN, BOTH
type OnLineCapability2Code string

// May be one of MREF, TEXT, HTML
type OutputFormat1Code string

// May be one of OTHN, OTHP, TEXT, URLI, HTML, PLIN, JSON, XMLF, EDIF, CSVF, JPEG, PDFF, PNGF, SVGF
type OutputFormat5Code string

// May be one of OTHN, OTHP, SECS, SECH
type PINEntrySecurityCharacteristic1Code string

// May be one of AQPP, APPR, TLPR, SCPR, SERV, TERM, DVCE, SECM, APLI, EMVK, EMVO, MDWR, DRVR, OPST, MRPR, CRTF, TMSP, SACP, SAPR
type POIComponentType5Code string

type Parameter13 struct {
	DgstAlgo     Algorithm20Code           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DgstAlgo,omitempty"`
	MskGnrtrAlgo AlgorithmIdentification26 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 MskGnrtrAlgo,omitempty"`
}

type Parameter14 struct {
	NcrptnFrmt   EncryptionFormat3Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NcrptnFrmt,omitempty"`
	InitlstnVctr Max500Binary          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 InitlstnVctr,omitempty"`
	BPddg        BytePadding1Code      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 BPddg,omitempty"`
}

type Parameter7 struct {
	InitlstnVctr Max500Binary     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 InitlstnVctr,omitempty"`
	BPddg        BytePadding1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 BPddg,omitempty"`
}

type PartyIdentification284 struct {
	Id                   Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Id,omitempty"`
	Assgnr               Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Assgnr,omitempty"`
	Ctry                 ISO3NumericCountryCode          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Ctry,omitempty"`
	ShrtNm               Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ShrtNm,omitempty"`
	LglCorpNm            Max99Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LglCorpNm,omitempty"`
	AddtlId              AdditionalData1                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlId,omitempty"`
	NmAndLctn            Max99Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NmAndLctn,omitempty"`
	Adr                  Address2                        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Adr,omitempty"`
	AddtlAdr             Max256Text                      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlAdr,omitempty"`
	GeogcLctn            GeographicPointInDecimalDegrees `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 GeogcLctn,omitempty"`
	Email                Max256Text                      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Email,omitempty"`
	URLAdr               Max256Text                      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 URLAdr,omitempty"`
	PhneNb               Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PhneNb,omitempty"`
	CstmrSvc             Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CstmrSvc,omitempty"`
	AddtlCtct            Max256Text                      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlCtct,omitempty"`
	TaxRegnId            Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 TaxRegnId,omitempty"`
	LclData              LocalData11                     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LclData,omitempty"`
	CorpTaxId            Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CorpTaxId,omitempty"`
	CorpTaxIdTp          CorporateTaxType1Code           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CorpTaxIdTp,omitempty"`
	BizTp                Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 BizTp,omitempty"`
	BizTpPrvddBy         Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 BizTpPrvddBy,omitempty"`
	OwnrTp               Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OwnrTp,omitempty"`
	OwnrTpPrvddBy        Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OwnrTpPrvddBy,omitempty"`
	CertfctnTp           Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CertfctnTp,omitempty"`
	CertfctnTpPrvddBy    Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CertfctnTpPrvddBy,omitempty"`
	OwnrEthnctyTp        Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OwnrEthnctyTp,omitempty"`
	OwnrEthnctyTpPrvddBy Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OwnrEthnctyTpPrvddBy,omitempty"`
	AddtlData            []AdditionalData1               `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlData,omitempty"`
}

type PartyIdentification285 struct {
	Id        Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Id"`
	Assgnr    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Assgnr,omitempty"`
	Ctry      ISO3NumericCountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Ctry,omitempty"`
	ShrtNm    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ShrtNm,omitempty"`
	LglCorpNm Max99Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LglCorpNm,omitempty"`
	AddtlId   []AdditionalData1      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlId,omitempty"`
	LclData   []LocalData14          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LclData,omitempty"`
}

type PartyIdentification286 struct {
	Id        Max11NumericText       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Id"`
	Assgnr    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Assgnr,omitempty"`
	Ctry      ISO3NumericCountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Ctry,omitempty"`
	ShrtNm    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ShrtNm,omitempty"`
	LglCorpNm Max99Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LglCorpNm,omitempty"`
	AddtlId   []AdditionalData1      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlId,omitempty"`
	LclData   LocalData14            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LclData,omitempty"`
}

type PartyIdentification287 struct {
	FI          FinancialInstitution8 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 FI,omitempty"`
	Id          Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Id,omitempty"`
	Dsgnt       Max2NumericText       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Dsgnt,omitempty"`
	Crdntls     []Credentials3        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Crdntls,omitempty"`
	Nm          CardholderName3       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Nm,omitempty"`
	Adr         Address2              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Adr,omitempty"`
	Ctct        ContactPersonal1      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Ctct,omitempty"`
	Ntlty       ISOMax3ACountryCode   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Ntlty,omitempty"`
	CtryOfBirth ISOMax3ACountryCode   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CtryOfBirth,omitempty"`
	DtOfBirth   ISODate               `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DtOfBirth,omitempty"`
	AddtlData   []AdditionalData1     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlData,omitempty"`
	LclData     LocalData15           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LclData,omitempty"`
}

// May be one of OTHN, OTHP, ACQR, ACQP, CISS, CISP, AGNT
type PartyType17Code string

// May be one of ACQR, CISS, CSCH, AGNT
type PartyType18Code string

// May be one of ACQR, AGNT, ISUR, OTHN, OTHP
type PartyType32Code string

// Must match the pattern \+[0-9]{1,3}-[0-9()+\-]{1,30}
type PhoneNumber string

type PointOfInteractionComponent16 struct {
	Tp      POIComponentType5Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tp"`
	ItmNb   Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ItmNb,omitempty"`
	PrvdrId Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PrvdrId,omitempty"`
	Id      Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Id,omitempty"`
	SrlNb   Max70Text             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 SrlNb,omitempty"`
}

type ProgrammeMode5 struct {
	ApldId  Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ApldId"`
	AddtlId []AdditionalData1 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlId,omitempty"`
}

type ProtectedData2 struct {
	CnttTp     ContentType3Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CnttTp"`
	EnvlpdData EnvelopedData12  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 EnvlpdData,omitempty"`
	NcrptdData EncryptedData2   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 NcrptdData,omitempty"`
}

// May be one of OTHN, OTHP, SELM, SNCL, SOFT, TEEN
type ProtectionMethod1Code string

type Recipient5Choice struct {
	IssrAndSrlNb IssuerAndSerialNumber1 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 IssrAndSrlNb,omitempty"`
	KeyIdr       KEKIdentifier2         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyIdr,omitempty"`
}

type Recipient7Choice struct {
	KeyTrnsprt KeyTransport6  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyTrnsprt,omitempty"`
	KEK        KEK6           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KEK,omitempty"`
	KeyIdr     KEKIdentifier6 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 KeyIdr,omitempty"`
}

type Reconciliation4 struct {
	Id        Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Id,omitempty"`
	Dt        ISODate   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Dt,omitempty"`
	ChckptRef Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ChckptRef,omitempty"`
}

type RelativeDistinguishedName1 struct {
	AttrTp  AttributeType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AttrTp"`
	AttrVal Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AttrVal"`
}

// May be one of APPC, APPH, APPU, DONT
type RiskAssessment1Code string

type SettlementService6 struct {
	Tp         Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tp,omitempty"`
	Id         Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Id,omitempty"`
	ReqdDt     ISODate           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ReqdDt,omitempty"`
	Dfrrd      bool              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Dfrrd,omitempty"`
	Dt         ISODate           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Dt,omitempty"`
	Tm         ISOTime           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tm,omitempty"`
	Prd        Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Prd,omitempty"`
	CutOffTm   ISODateTime       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CutOffTm,omitempty"`
	RptgNttyTp Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 RptgNttyTp,omitempty"`
	RptgNttyId Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 RptgNttyId,omitempty"`
	AddtlInf   []AdditionalData1 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlInf,omitempty"`
}

type Software1 struct {
	Tp     SoftwareType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tp,omitempty"`
	OthrTp Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrTp,omitempty"`
	SubTp  Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 SubTp,omitempty"`
	Vrsn   Max256Text        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Vrsn,omitempty"`
}

// May be one of MFFW, MFSW, APSW, OTHP, OTHN
type SoftwareType1Code string

// May be one of CAWL, DVCE, ISWL, ONFL, OTHN, OTHP, TPWL
type StorageLocation1Code string

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type Terminal7 struct {
	Id                   Max16Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Id"`
	AddtlId              []AdditionalData1                     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlId,omitempty"`
	Tp                   TerminalType1Code                     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tp,omitempty"`
	OthrTp               Max35Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrTp,omitempty"`
	RdngCpblty           []CardReadingCapabilities1            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 RdngCpblty,omitempty"`
	WrtgCpblty           []CardWritingCapabilities1            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 WrtgCpblty,omitempty"`
	PINLngthCpblty       float64                               `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PINLngthCpblty,omitempty"`
	PINNtrySctyChrtc     PINEntrySecurityCharacteristic1Code   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PINNtrySctyChrtc,omitempty"`
	OthrPINNtrySctyChrtc Max35Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrPINNtrySctyChrtc,omitempty"`
	ApprvlCdLngth        float64                               `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ApprvlCdLngth,omitempty"`
	MxScrptLngth         float64                               `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 MxScrptLngth,omitempty"`
	CardCaptrCpbl        bool                                  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CardCaptrCpbl,omitempty"`
	OnLineCpblty         OnLineCapability2Code                 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OnLineCpblty,omitempty"`
	MsgCpblty            []DisplayCapabilities6                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 MsgCpblty,omitempty"`
	CrdhldrVrfctnCpblty  []CardholderVerificationCapabilities1 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CrdhldrVrfctnCpblty,omitempty"`
	TempScrStorg         bool                                  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 TempScrStorg,omitempty"`
	IntgtnTp             TerminalIntegrationCategory1Code      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 IntgtnTp,omitempty"`
	GeogcLctn            GeographicPointInDecimalDegrees       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 GeogcLctn,omitempty"`
	Outdr                bool                                  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Outdr,omitempty"`
	OffPrmiss            bool                                  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OffPrmiss,omitempty"`
	OnBrd                bool                                  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OnBrd,omitempty"`
	SrlNb                Max35Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 SrlNb,omitempty"`
	Sftwr                []Software1                           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Sftwr,omitempty"`
	CertfctnId           Max256Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CertfctnId,omitempty"`
}

// May be one of MPOI, MSLE, SSLE
type TerminalIntegrationCategory1Code string

// May be one of ATMT, MPOS, OTHN, OTHP, POST
type TerminalType1Code string

type Token2 struct {
	PmtTkn        Max19NumericText      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PmtTkn,omitempty"`
	TknXpryDt     ISOYearMonth          `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 TknXpryDt,omitempty"`
	TknRqstrId    Max11NumericText      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 TknRqstrId,omitempty"`
	TknAssrncData Max140Text            `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 TknAssrncData,omitempty"`
	TknAssrncMtd  Max2NumericText       `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 TknAssrncMtd,omitempty"`
	TknInittdInd  bool                  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 TknInittdInd,omitempty"`
	StorgLctn     StorageLocation1Code  `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 StorgLctn,omitempty"`
	OthrStorgLctn Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrStorgLctn,omitempty"`
	PrtcnMtd      ProtectionMethod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PrtcnMtd,omitempty"`
	OthrPrtcnMtd  Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrPrtcnMtd,omitempty"`
	AddtlData     []AdditionalData1     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlData,omitempty"`
}

type Traceability10 struct {
	Id      Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Id"`
	Tp      PartyType17Code     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Tp,omitempty"`
	OthrTp  Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrTp,omitempty"`
	Assgnr  PartyType18Code     `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Assgnr,omitempty"`
	Ctry    ISOMax3ACountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Ctry,omitempty"`
	ShrtNm  Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ShrtNm,omitempty"`
	DtTmIn  ISODateTime         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DtTmIn,omitempty"`
	DtTmOut ISODateTime         `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DtTmOut,omitempty"`
}

// May be one of INTC, FEEP, OTHN, OTHP, FEEA, CSIF, MXIF, MNIF
type TypeOfAmount21Code string

// May be one of CDSP, CRCP, MDSP, MRCP
type UserInterface1Code string

type Wallet3 struct {
	Prvdr                 PartyIdentification285 `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Prvdr,omitempty"`
	PANAge                float64                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PANAge,omitempty"`
	UsrAcctAge            float64                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 UsrAcctAge,omitempty"`
	AcctAge               float64                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AcctAge,omitempty"`
	DaysSncLastActvty     float64                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 DaysSncLastActvty,omitempty"`
	Actvty                float64                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 Actvty,omitempty"`
	ActvtyIntrvl          Frequency12Code        `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 ActvtyIntrvl,omitempty"`
	LastWlltChng          float64                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 LastWlltChng,omitempty"`
	SspdCrds              float64                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 SspdCrds,omitempty"`
	AcctCtry              ISOMax3ACountryCode    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AcctCtry,omitempty"`
	CardDataNtryMd        CardDataReading9Code   `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 CardDataNtryMd,omitempty"`
	OthrCardDataNtryMd    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 OthrCardDataNtryMd,omitempty"`
	AcctEmailAge          float64                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AcctEmailAge,omitempty"`
	PrvdrRskAssmnt        RiskAssessment1Code    `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PrvdrRskAssmnt,omitempty"`
	PrvdrRskAssmntMdlVrsn Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PrvdrRskAssmntMdlVrsn,omitempty"`
	PrvdrPhneScore        float64                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PrvdrPhneScore,omitempty"`
	PrvdrDvcScore         float64                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PrvdrDvcScore,omitempty"`
	PrvdrAcctScore        float64                `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 PrvdrAcctScore,omitempty"`
	AddtlData             []AdditionalData1      `xml:"urn:iso:std:iso:20022:tech:xsd:cafm.002.001.03 AddtlData,omitempty"`
}

type xsdBase64Binary []byte

func (b *xsdBase64Binary) UnmarshalText(text []byte) (err error) {
	*b, err = base64.StdEncoding.DecodeString(string(text))
	return
}
func (b xsdBase64Binary) MarshalText() ([]byte, error) {
	var buf bytes.Buffer
	enc := base64.NewEncoder(base64.StdEncoding, &buf)
	enc.Write([]byte(b))
	enc.Close()
	return buf.Bytes(), nil
}

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}

type xsdGYearMonth time.Time

func (t *xsdGYearMonth) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01")
}
func (t xsdGYearMonth) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01")
}
func (t xsdGYearMonth) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdGYearMonth) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}

type xsdTime time.Time

func (t *xsdTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "15:04:05.999999999")
}
func (t xsdTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "15:04:05.999999999")
}
func (t xsdTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
