// Code generated by z. DO NOT EDIT.

package caad_003_001_03

import (
	"bytes"
	"encoding/base64"
	"encoding/xml"
	"time"
)

type AdditionalData1 struct {
	Tp  Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Tp,omitempty"`
	Val Max2048Text `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Val,omitempty"`
}

type AdditionalData2 struct {
	Tp   Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Tp,omitempty"`
	Dtls []AdditionalData1 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Dtls,omitempty"`
}

type AdditionalInformation21 struct {
	Rcpt PartyType23Code      `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Rcpt,omitempty"`
	Trgt []UserInterface7Code `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Trgt,omitempty"`
	Frmt OutputFormat4Code    `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Frmt,omitempty"`
	Val  Max20KText           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Val"`
}

// May be one of EA2C, E3DC, DKP9, UKPT, UKA1, EA9C, EA5C
type Algorithm13Code string

// May be one of HS25, HS38, HS51
type Algorithm20Code string

// May be one of EA2C, E3DC, EA9C, EA5C, EA2R, EA9R, EA5R, E3DR, E36C, E36R, SD5C
type Algorithm23Code string

// May be one of HS25, HS38, HS51
type Algorithm5Code string

// May be one of ERSA, RSAO
type Algorithm7Code string

// May be one of MGF1
type Algorithm8Code string

type AlgorithmIdentification25 struct {
	Algo  Algorithm23Code `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Algo"`
	Param Parameter7      `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Param,omitempty"`
}

type AlgorithmIdentification26 struct {
	Algo  Algorithm8Code `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Algo"`
	Param Algorithm5Code `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Param,omitempty"`
}

type AlgorithmIdentification27 struct {
	Algo  Algorithm7Code `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Algo"`
	Param Parameter13    `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Param,omitempty"`
}

type AlgorithmIdentification28 struct {
	Algo  Algorithm13Code `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Algo"`
	Param Parameter14     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Param,omitempty"`
}

// May be one of CNAT, LATT, OATT, OUAT, CATT
type AttributeType1Code string

type BatchManagementInformation1 struct {
	ColltnId         Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ColltnId,omitempty"`
	BtchId           Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 BtchId"`
	MsgSeqNb         Max15NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 MsgSeqNb,omitempty"`
	MsgChcksmInptVal Max140Binary     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 MsgChcksmInptVal,omitempty"`
}

type BatchTransferInitiationV03 struct {
	Hdr           Header71                  `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Hdr"`
	BtchId        Max70Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 BtchId,omitempty"`
	OrgnlBtchId   Max70Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 OrgnlBtchId,omitempty"`
	NbOfMsgs      float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 NbOfMsgs,omitempty"`
	BtchChcksm    Max35Binary               `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 BtchChcksm,omitempty"`
	ReqAck        bool                      `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ReqAck,omitempty"`
	Orgtr         PartyIdentification286    `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Orgtr,omitempty"`
	Dstn          PartyIdentification286    `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Dstn,omitempty"`
	Prgrmm        []ProgrammeMode5          `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Prgrmm,omitempty"`
	SysTracAudtNb Max12NumericText          `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 SysTracAudtNb,omitempty"`
	TrnsmssnDtTm  ISODateTime               `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 TrnsmssnDtTm,omitempty"`
	RtrvlRefNb    string                    `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RtrvlRefNb,omitempty"`
	LifeCyclId    string                    `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 LifeCyclId,omitempty"`
	ClrBtchData   []ClearingBatchData3      `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ClrBtchData,omitempty"`
	ClrCtrlTtls   ClearingControlTotals3    `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ClrCtrlTtls,omitempty"`
	AgtData       []AdditionalInformation21 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AgtData,omitempty"`
	Rcrd          []Record3                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Rcrd,omitempty"`
	Jursdctn      Jurisdiction2             `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Jursdctn,omitempty"`
	SttlmSvc      SettlementService6        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 SttlmSvc,omitempty"`
	Rcncltn       Reconciliation4           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Rcncltn,omitempty"`
	OrgnlRspnCd   ISO8583ResponseCode       `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 OrgnlRspnCd,omitempty"`
	PrcgRslt      ProcessingResult26        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 PrcgRslt,omitempty"`
	AddtlData     []AdditionalData2         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AddtlData,omitempty"`
	PrtctdData    []ProtectedData2          `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 PrtctdData,omitempty"`
	SplmtryData   []SupplementaryData1      `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 SplmtryData,omitempty"`
	SctyTrlr      ContentInformationType41  `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 SctyTrlr,omitempty"`
}

// May be one of LNGT, NUL8, NULG, NULL, RAND
type BytePadding1Code string

type CertificateIssuer1 struct {
	RltvDstngshdNm []RelativeDistinguishedName1 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RltvDstngshdNm"`
}

type ClearingBatchData3 struct {
	Mtd               ClearingMethod2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Mtd"`
	OthrMtd           Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 OthrMtd,omitempty"`
	Prty              Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Prty,omitempty"`
	Dt                ISODate                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Dt,omitempty"`
	TtlsCnt           float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 TtlsCnt,omitempty"`
	TtlsAmt           float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 TtlsAmt,omitempty"`
	TtlsCcy           ISO3NumericCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 TtlsCcy,omitempty"`
	TtlsCdtDbt        CreditDebit3Code        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 TtlsCdtDbt,omitempty"`
	IntrchngFeeAmt    float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 IntrchngFeeAmt,omitempty"`
	IntrchngFeeCcy    ISO3NumericCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 IntrchngFeeCcy,omitempty"`
	IntrchngFeeCdtDbt CreditDebit3Code        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 IntrchngFeeCdtDbt,omitempty"`
	AgtFeeAmt         float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AgtFeeAmt,omitempty"`
	AgtFeeCcy         ISO3NumericCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AgtFeeCcy,omitempty"`
	AgtFeeCdtDbt      CreditDebit3Code        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AgtFeeCdtDbt,omitempty"`
}

type ClearingControlTotals3 struct {
	Cnt    float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Cnt"`
	Amt    float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Amt"`
	Ccy    ISO3NumericCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Ccy,omitempty"`
	CdtDbt CreditDebit3Code        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 CdtDbt,omitempty"`
}

// May be one of DAYC, DFRD, INST, OTHN, OTHP, RLTM
type ClearingMethod2Code string

type ContentInformationType41 struct {
	MACData MACData1          `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 MACData"`
	MAC     Max8HexBinaryText `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 MAC"`
}

// May be one of DATA, SIGN, EVLP, DGST, AUTH
type ContentType2Code string

// May be one of EVLP, IFSE
type ContentType3Code string

// May be one of CRDT, DBIT
type CreditDebit3Code string

type Document struct {
	BtchTrfInitn BatchTransferInitiationV03 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 BtchTrfInitn"`
}

type EncryptedContent8 struct {
	CnttTp         ContentType2Code          `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 CnttTp"`
	CnttNcrptnAlgo AlgorithmIdentification25 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 CnttNcrptnAlgo"`
	NcrptdDataElmt []EncryptedDataElement2   `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 NcrptdDataElmt"`
}

type EncryptedData2 struct {
	Ctrl       Exact1HexBinaryText     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Ctrl,omitempty"`
	KeySetIdr  Max8NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeySetIdr,omitempty"`
	DrvdInf    Max32HexBinaryText      `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 DrvdInf,omitempty"`
	Algo       Max2NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Algo,omitempty"`
	KeyLngth   Max4NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyLngth,omitempty"`
	KeyPrtcn   Max2NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyPrtcn,omitempty"`
	KeyIndx    Max5NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyIndx,omitempty"`
	PddgMtd    Max2NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 PddgMtd,omitempty"`
	NcrptdFrmt Max2NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 NcrptdFrmt,omitempty"`
	NcrptdElmt []EncryptedDataElement2 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 NcrptdElmt"`
}

type EncryptedData2Choice struct {
	Binry    Max100KBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Binry,omitempty"`
	HexBinry string        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 HexBinry,omitempty"`
}

type EncryptedDataElement2 struct {
	Id               Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Id,omitempty"`
	Data             EncryptedData2Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Data"`
	ClearTxtFrmt     EncryptedDataFormat1Code `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ClearTxtFrmt,omitempty"`
	OthrClearTxtFrmt Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 OthrClearTxtFrmt,omitempty"`
}

// May be one of ASCI, BINF, EBCD, HEXF, OTHN, OTHP
type EncryptedDataFormat1Code string

// May be one of TR34, TR31, CTCE, CBCE
type EncryptionFormat3Code string

type EnvelopedData12 struct {
	Vrsn       float64            `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Vrsn,omitempty"`
	Rcpt       []Recipient7Choice `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Rcpt"`
	NcrptdCntt EncryptedContent8  `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 NcrptdCntt,omitempty"`
}

// Must match the pattern ([0-9A-F][0-9A-F]){1}
type Exact1HexBinaryText string

// May be no more than 4 items long
type ExternalMessageFunction1Code string

type GenericIdentification183 struct {
	Id     Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Id"`
	Tp     PartyType17Code     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Tp,omitempty"`
	OthrTp Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 OthrTp,omitempty"`
	Assgnr PartyType18Code     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Assgnr,omitempty"`
	Ctry   ISOMax3ACountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Ctry,omitempty"`
	ShrtNm Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ShrtNm,omitempty"`
}

type Header71 struct {
	MsgFctn        ExternalMessageFunction1Code `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 MsgFctn"`
	PrtcolVrsn     Max2048Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 PrtcolVrsn"`
	XchgId         Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 XchgId,omitempty"`
	ReTrnsmssnCntr Max3NumericText              `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ReTrnsmssnCntr,omitempty"`
	CreDtTm        ISODateTime                  `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 CreDtTm"`
	BtchMgmtInf    BatchManagementInformation1  `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 BtchMgmtInf,omitempty"`
	InitgPty       GenericIdentification183     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 InitgPty"`
	RcptPty        GenericIdentification183     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RcptPty,omitempty"`
	TracData       []AdditionalData1            `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 TracData,omitempty"`
	Tracblt        []Traceability10             `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Tracblt,omitempty"`
}

// Must match the pattern [0-9]{3,3}
type ISO3NumericCountryCode string

// Must match the pattern [0-9]{3,3}
type ISO3NumericCurrencyCode string

// Must match the pattern [0-9A-Z]{2,2}
type ISO8583ResponseCode string

type ISODate time.Time

func (t *ISODate) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t ISODate) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type ISODateTime time.Time

func (t *ISODateTime) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t ISODateTime) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

// Must match the pattern [A-Z]{2,3}
type ISOMax3ACountryCode string

// Must match the pattern [a-z]{2,3}
type ISOMax3ALanguageCode string

type ISOTime time.Time

func (t *ISOTime) UnmarshalText(text []byte) error {
	return (*xsdTime)(t).UnmarshalText(text)
}
func (t ISOTime) MarshalText() ([]byte, error) {
	return xsdTime(t).MarshalText()
}

type IssuerAndSerialNumber1 struct {
	Issr  CertificateIssuer1 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Issr"`
	SrlNb Max35Binary        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 SrlNb"`
}

type Jurisdiction2 struct {
	DmstInd    bool      `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 DmstInd,omitempty"`
	DmstQlfctn Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 DmstQlfctn,omitempty"`
}

type KEK6 struct {
	Vrsn          float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Vrsn,omitempty"`
	KEKId         KEKIdentifier6            `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KEKId"`
	KeyNcrptnAlgo AlgorithmIdentification28 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyNcrptnAlgo"`
	NcrptdKey     Max500Binary              `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 NcrptdKey,omitempty"`
}

type KEKIdentifier2 struct {
	KeyId     Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyId"`
	KeyVrsn   Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyVrsn"`
	SeqNb     float64         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 SeqNb,omitempty"`
	DerivtnId Min5Max16Binary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 DerivtnId,omitempty"`
}

type KEKIdentifier6 struct {
	KeyId     Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyId"`
	KeyVrsn   Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyVrsn,omitempty"`
	SeqNb     float64         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 SeqNb,omitempty"`
	DerivtnId Min5Max16Binary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 DerivtnId,omitempty"`
}

type KeyTransport6 struct {
	Vrsn          float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Vrsn,omitempty"`
	RcptId        Recipient5Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RcptId"`
	KeyNcrptnAlgo AlgorithmIdentification27 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyNcrptnAlgo"`
	NcrptdKey     Max5000Binary             `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 NcrptdKey"`
}

type LocalData14 struct {
	Lang      ISOMax3ALanguageCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Lang"`
	NcodgFrmt Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 NcodgFrmt,omitempty"`
	ShrtNm    Max70Text            `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ShrtNm,omitempty"`
	LglCorpNm Max210Text           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 LglCorpNm,omitempty"`
	AddtlData []AdditionalData1    `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AddtlData,omitempty"`
}

type MACData1 struct {
	Ctrl         Exact1HexBinaryText `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Ctrl"`
	KeySetIdr    Max8NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeySetIdr"`
	DrvdInf      Max32HexBinaryText  `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 DrvdInf,omitempty"`
	Algo         Max2NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Algo"`
	KeyLngth     Max4NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyLngth,omitempty"`
	KeyPrtcn     Max2NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyPrtcn,omitempty"`
	KeyIndx      Max5NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyIndx,omitempty"`
	PddgMtd      Max2NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 PddgMtd,omitempty"`
	InitlstnVctr Max32HexBinaryText  `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 InitlstnVctr,omitempty"`
}

type Max100KBinary []byte

func (t *Max100KBinary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max100KBinary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// Must match the pattern [0-9]{1,11}
type Max11NumericText string

// Must match the pattern [0-9]{1,12}
type Max12NumericText string

type Max140Binary []byte

func (t *Max140Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max140Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be no more than 140 items long
type Max140Text string

// Must match the pattern [0-9]{1,15}
type Max15NumericText string

// May be no more than 2048 items long
type Max2048Text string

// May be no more than 20000 items long
type Max20KText string

// May be no more than 210 items long
type Max210Text string

type Max2MBBinary []byte

func (t *Max2MBBinary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max2MBBinary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// Must match the pattern [0-9]{1,2}
type Max2NumericText string

// Must match the pattern ([0-9A-F][0-9A-F]){1,32}
type Max32HexBinaryText string

// May be no more than 350 items long
type Max350Text string

type Max35Binary []byte

func (t *Max35Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max35Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be no more than 35 items long
type Max35Text string

// Must match the pattern [0-9]{1,3}
type Max3NumericText string

// Must match the pattern [0-9]{1,4}
type Max4NumericText string

type Max5000Binary []byte

func (t *Max5000Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max5000Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

type Max500Binary []byte

func (t *Max500Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max500Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// Must match the pattern [0-9]{1,5}
type Max5NumericText string

// May be no more than 70 items long
type Max70Text string

// Must match the pattern ([0-9A-F][0-9A-F]){1,8}
type Max8HexBinaryText string

// Must match the pattern [0-9]{1,8}
type Max8NumericText string

// May be no more than 99 items long
type Max99Text string

type Min5Max16Binary []byte

func (t *Min5Max16Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Min5Max16Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

type OtherAmount5 struct {
	ClrCnt            float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ClrCnt"`
	ClrAmt            float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ClrAmt"`
	ClrCcy            ISO3NumericCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ClrCcy,omitempty"`
	ClrCdtDbt         CreditDebit3Code        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ClrCdtDbt,omitempty"`
	IntrchngFeeAmt    float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 IntrchngFeeAmt"`
	IntrchngFeeCcy    ISO3NumericCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 IntrchngFeeCcy,omitempty"`
	IntrchngFeeCdtDbt CreditDebit3Code        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 IntrchngFeeCdtDbt,omitempty"`
	AgtFeeAmt         float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AgtFeeAmt"`
	AgtFeeCcy         ISO3NumericCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AgtFeeCcy,omitempty"`
	AgtFeeCdtDbt      CreditDebit3Code        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AgtFeeCdtDbt,omitempty"`
}

// May be one of FLNM, MREF, OTHN, OTHP, SMSI, TEXT, URLI, HTML
type OutputFormat4Code string

type Parameter13 struct {
	DgstAlgo     Algorithm20Code           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 DgstAlgo,omitempty"`
	MskGnrtrAlgo AlgorithmIdentification26 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 MskGnrtrAlgo,omitempty"`
}

type Parameter14 struct {
	NcrptnFrmt   EncryptionFormat3Code `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 NcrptnFrmt,omitempty"`
	InitlstnVctr Max500Binary          `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 InitlstnVctr,omitempty"`
	BPddg        BytePadding1Code      `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 BPddg,omitempty"`
}

type Parameter7 struct {
	InitlstnVctr Max500Binary     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 InitlstnVctr,omitempty"`
	BPddg        BytePadding1Code `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 BPddg,omitempty"`
}

type PartyIdentification286 struct {
	Id        Max11NumericText       `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Id"`
	Assgnr    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Assgnr,omitempty"`
	Ctry      ISO3NumericCountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Ctry,omitempty"`
	ShrtNm    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ShrtNm,omitempty"`
	LglCorpNm Max99Text              `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 LglCorpNm,omitempty"`
	AddtlId   []AdditionalData1      `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AddtlId,omitempty"`
	LclData   LocalData14            `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 LclData,omitempty"`
}

// May be one of OTHN, OTHP, ACQR, ACQP, CISS, CISP, AGNT
type PartyType17Code string

// May be one of ACQR, CISS, CSCH, AGNT
type PartyType18Code string

// May be one of OTHN, OTHP, CLRA
type PartyType23Code string

// May be one of ACCP, ACQR, ICCA, CISS, DLIS, AGNT, OTHN, OTHP
type PartyType26Code string

// May be one of ACQR, ACQP, CISS, CISP, CSCH, SCHP
type PartyType9Code string

type ProcessingResult26 struct {
	RspnSrcId     Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RspnSrcId,omitempty"`
	RspnSrcTp     PartyType26Code     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RspnSrcTp,omitempty"`
	RspnSrcOthrTp Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RspnSrcOthrTp,omitempty"`
	RspnSrcAssgnr PartyType9Code      `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RspnSrcAssgnr,omitempty"`
	RspnSrcCtry   ISOMax3ACountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RspnSrcCtry,omitempty"`
	RspnSrcShrtNm Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RspnSrcShrtNm,omitempty"`
	RspnCd        ISO8583ResponseCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RspnCd,omitempty"`
	AddtlInf      []AdditionalData1   `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AddtlInf,omitempty"`
}

type ProgrammeMode5 struct {
	ApldId  Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ApldId"`
	AddtlId []AdditionalData1 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AddtlId,omitempty"`
}

type ProtectedData2 struct {
	CnttTp     ContentType3Code `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 CnttTp"`
	EnvlpdData EnvelopedData12  `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 EnvlpdData,omitempty"`
	NcrptdData EncryptedData2   `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 NcrptdData,omitempty"`
}

type Recipient5Choice struct {
	IssrAndSrlNb IssuerAndSerialNumber1 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 IssrAndSrlNb,omitempty"`
	KeyIdr       KEKIdentifier2         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyIdr,omitempty"`
}

type Recipient7Choice struct {
	KeyTrnsprt KeyTransport6  `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyTrnsprt,omitempty"`
	KEK        KEK6           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KEK,omitempty"`
	KeyIdr     KEKIdentifier6 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyIdr,omitempty"`
}

type Reconciliation4 struct {
	Id        Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Id,omitempty"`
	Dt        ISODate   `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Dt,omitempty"`
	ChckptRef Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ChckptRef,omitempty"`
}

type Record3 struct {
	SeqCntr           float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 SeqCntr"`
	RcrdChcksmInptVal Max140Binary            `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RcrdChcksmInptVal,omitempty"`
	OrgtrId           Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 OrgtrId,omitempty"`
	OrgtrAssgnr       Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 OrgtrAssgnr,omitempty"`
	OrgtrCtry         ISO3NumericCountryCode  `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 OrgtrCtry,omitempty"`
	OrgtrShrtNm       Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 OrgtrShrtNm,omitempty"`
	DstnId            Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 DstnId,omitempty"`
	DstnAssgnr        Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 DstnAssgnr,omitempty"`
	DstnCtry          ISO3NumericCountryCode  `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 DstnCtry,omitempty"`
	DstnShrtNm        Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 DstnShrtNm,omitempty"`
	ClrMtd            ClearingMethod2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ClrMtd"`
	OthrClrMtd        Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 OthrClrMtd,omitempty"`
	ClrPrty           Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ClrPrty,omitempty"`
	ClrDt             ISODate                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ClrDt,omitempty"`
	ClrAmt            float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ClrAmt,omitempty"`
	ClrCcy            ISO3NumericCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ClrCcy,omitempty"`
	ClrCdtDbt         CreditDebit3Code        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ClrCdtDbt,omitempty"`
	IntrchngFeeAmt    float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 IntrchngFeeAmt,omitempty"`
	IntrchngFeeCcy    ISO3NumericCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 IntrchngFeeCcy,omitempty"`
	IntrchngFeeCdtDbt CreditDebit3Code        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 IntrchngFeeCdtDbt,omitempty"`
	AgtFeeAmt         float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AgtFeeAmt,omitempty"`
	AgtFeeCcy         ISO3NumericCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AgtFeeCcy,omitempty"`
	AgtFeeCdtDbt      CreditDebit3Code        `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AgtFeeCdtDbt,omitempty"`
	OthrAmt           OtherAmount5            `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 OthrAmt,omitempty"`
	RcrdMsg           RecordMessage1Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RcrdMsg"`
}

type RecordMessage1Choice struct {
	AdddmInitn      Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AdddmInitn,omitempty"`
	AdddmRspn       Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AdddmRspn,omitempty"`
	Amdmnt          Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Amdmnt,omitempty"`
	AuthstnInitn    Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AuthstnInitn,omitempty"`
	AuthstnRspn     Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AuthstnRspn,omitempty"`
	CardMgmtInitn   Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 CardMgmtInitn,omitempty"`
	CardMgmtRspn    Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 CardMgmtRspn,omitempty"`
	ChrgBckInitn    Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ChrgBckInitn,omitempty"`
	ChrgBckRspn     Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ChrgBckRspn,omitempty"`
	Err             Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Err,omitempty"`
	FeeColltnInitn  Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 FeeColltnInitn,omitempty"`
	FeeColltnRspn   Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 FeeColltnRspn,omitempty"`
	FileActnInitn   Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 FileActnInitn,omitempty"`
	FileActnRspn    Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 FileActnRspn,omitempty"`
	FinInitn        Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 FinInitn,omitempty"`
	FinRspn         Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 FinRspn,omitempty"`
	FrdDspstnInitn  Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 FrdDspstnInitn,omitempty"`
	FrdDspstnRspn   Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 FrdDspstnRspn,omitempty"`
	FrdRptgInitn    Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 FrdRptgInitn,omitempty"`
	FrdRptgRspn     Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 FrdRptgRspn,omitempty"`
	NqryInitn       Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 NqryInitn,omitempty"`
	NqryRspn        Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 NqryRspn,omitempty"`
	KeyXchgInitn    Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyXchgInitn,omitempty"`
	KeyXchgRspn     Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 KeyXchgRspn,omitempty"`
	NtwkMgmtInitn   Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 NtwkMgmtInitn,omitempty"`
	NtwkMgmtRspn    Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 NtwkMgmtRspn,omitempty"`
	RcncltnInitn    Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RcncltnInitn,omitempty"`
	RcncltnRspn     Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RcncltnRspn,omitempty"`
	RtrvlInitn      Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RtrvlInitn,omitempty"`
	RtrvlRspn       Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RtrvlRspn,omitempty"`
	RtrvlFlfmtInitn Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RtrvlFlfmtInitn,omitempty"`
	RtrvlFlfmtRspn  Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RtrvlFlfmtRspn,omitempty"`
	RvslInitn       Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RvslInitn,omitempty"`
	RvslRspn        Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RvslRspn,omitempty"`
	SttlmRptgInitn  Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 SttlmRptgInitn,omitempty"`
	SttlmRptgRspn   Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 SttlmRptgRspn,omitempty"`
	VrfctnInitn     Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 VrfctnInitn,omitempty"`
	VrfctnRspn      Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 VrfctnRspn,omitempty"`
}

type RelativeDistinguishedName1 struct {
	AttrTp  AttributeType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AttrTp"`
	AttrVal Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AttrVal"`
}

type SettlementService6 struct {
	Tp         Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Tp,omitempty"`
	Id         Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Id,omitempty"`
	ReqdDt     ISODate           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ReqdDt,omitempty"`
	Dfrrd      bool              `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Dfrrd,omitempty"`
	Dt         ISODate           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Dt,omitempty"`
	Tm         ISOTime           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Tm,omitempty"`
	Prd        Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Prd,omitempty"`
	CutOffTm   ISODateTime       `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 CutOffTm,omitempty"`
	RptgNttyTp Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RptgNttyTp,omitempty"`
	RptgNttyId Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 RptgNttyId,omitempty"`
	AddtlInf   []AdditionalData1 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 AddtlInf,omitempty"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type Traceability10 struct {
	Id      Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Id"`
	Tp      PartyType17Code     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Tp,omitempty"`
	OthrTp  Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 OthrTp,omitempty"`
	Assgnr  PartyType18Code     `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Assgnr,omitempty"`
	Ctry    ISOMax3ACountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 Ctry,omitempty"`
	ShrtNm  Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 ShrtNm,omitempty"`
	DtTmIn  ISODateTime         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 DtTmIn,omitempty"`
	DtTmOut ISODateTime         `xml:"urn:iso:std:iso:20022:tech:xsd:caad.003.001.03 DtTmOut,omitempty"`
}

// May be one of OCAI, CLRL, CLRA
type UserInterface7Code string

type xsdBase64Binary []byte

func (b *xsdBase64Binary) UnmarshalText(text []byte) (err error) {
	*b, err = base64.StdEncoding.DecodeString(string(text))
	return
}
func (b xsdBase64Binary) MarshalText() ([]byte, error) {
	var buf bytes.Buffer
	enc := base64.NewEncoder(base64.StdEncoding, &buf)
	enc.Write([]byte(b))
	enc.Close()
	return buf.Bytes(), nil
}

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}

type xsdTime time.Time

func (t *xsdTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "15:04:05.999999999")
}
func (t xsdTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "15:04:05.999999999")
}
func (t xsdTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
