// Code generated by z. DO NOT EDIT.

package seev_040_002_13

import (
	"bytes"
	"encoding/xml"
	"time"
)

type AccountIdentification73 struct {
	SfkpgAcct          RestrictedFINXMax35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 SfkpgAcct,omitempty"`
	BlckChainAdrOrWllt Max140Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 BlckChainAdrOrWllt,omitempty"`
	AcctOwnr           PartyIdentification136Choice   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 AcctOwnr,omitempty"`
	SfkpgPlc           SafekeepingPlaceFormat45Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 SfkpgPlc,omitempty"`
}

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type AnyBICDec2014Identifier string

type CorporateActionEventType116Choice struct {
	Cd    CorporateActionEventType40Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Cd,omitempty"`
	Prtry GenericIdentification47        `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Prtry,omitempty"`
}

// May be one of ACTV, ATTI, BRUP, DFLT, BONU, EXRI, CAPD, CAPG, CAPI, DRCA, DVCA, CHAN, COOP, CLSA, CONS, CONV, CREV, DECR, DETI, DSCL, DVOP, DRIP, DRAW, DTCH, EXOF, REDM, MCAL, INCR, PPMT, INTR, RHDI, LIQU, EXTM, MRGR, NOOF, CERT, ODLT, OTHR, PARI, PCAL, PRED, PINK, PLAC, PDEF, PRIO, BPUT, REDO, REMK, BIDS, SPLR, RHTS, DVSC, SHPR, SMAL, SOFF, DVSE, SPLF, TREC, TEND, DLST, SUSP, EXWA, WTRC, WRTH, ACCU
type CorporateActionEventType40Code string

type CorporateActionGeneralInformation187 struct {
	CorpActnEvtId      RestrictedFINXMax16Text           `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 CorpActnEvtId"`
	OffclCorpActnEvtId RestrictedFINXMax16Text           `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 OffclCorpActnEvtId,omitempty"`
	EvtTp              CorporateActionEventType116Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 EvtTp"`
	FinInstrmId        SecurityIdentification21          `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 FinInstrmId,omitempty"`
}

type CorporateActionInstructionCancellationRequest002V13 struct {
	ChngInstrInd   bool                                 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 ChngInstrInd,omitempty"`
	InstrId        DocumentIdentification37             `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 InstrId"`
	CorpActnGnlInf CorporateActionGeneralInformation187 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 CorpActnGnlInf"`
	AcctDtls       AccountIdentification73              `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 AcctDtls"`
	CorpActnInstr  CorporateActionOption202             `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 CorpActnInstr"`
	PrtctInstr     ProtectInstruction7                  `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 PrtctInstr,omitempty"`
	AddtlInf       CorporateActionNarrative19           `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 AddtlInf,omitempty"`
	SplmtryData    []SupplementaryData1                 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 SplmtryData,omitempty"`
}

type CorporateActionNarrative19 struct {
	AddtlTxt     []RestrictedFINXMax350Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 AddtlTxt,omitempty"`
	PtyCtctNrrtv []RestrictedFINXMax350Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 PtyCtctNrrtv,omitempty"`
}

// May be one of ABST, BSPL, BUYA, CASE, CASH, CERT, CEXC, CONN, CONY, CTEN, EXER, LAPS, MKDW, MKUP, MPUT, NOAC, NOQU, OFFR, OTHR, OVER, QINV, SECU, SLLE, TAXI, PRUN, BOBD
type CorporateActionOption16Code string

type CorporateActionOption202 struct {
	OptnNb   OptionNumber1Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 OptnNb"`
	OptnTp   CorporateActionOption43Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 OptnTp"`
	InstdQty Quantity55Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 InstdQty"`
}

type CorporateActionOption43Choice struct {
	Cd    CorporateActionOption16Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Cd,omitempty"`
	Prtry GenericIdentification47     `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Prtry,omitempty"`
}

// Must match the pattern [A-Z]{2,2}
type CountryCode string

// Must match the pattern [1-9B-DF-HJ-NP-TV-XZ][0-9B-DF-HJ-NP-TV-XZ]{8,8}
type DTI2024Identifier string

type Document struct {
	CorpActnInstrCxlReq CorporateActionInstructionCancellationRequest002V13 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 CorpActnInstrCxlReq"`
}

type DocumentIdentification37 struct {
	Id    RestrictedFINXMax16Text    `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Id"`
	LkgTp ProcessingPosition10Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 LkgTp,omitempty"`
}

// Must match the pattern [0-9]{3}
type Exact3NumericText string

// Must match the pattern [a-zA-Z0-9]{4}
type Exact4AlphaNumericText string

// May be no more than 4 items long
type ExternalFinancialInstrumentIdentificationType1Code string

type FinancialInstrumentQuantity36Choice struct {
	Unit        float64 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Unit,omitempty"`
	FaceAmt     float64 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 FaceAmt,omitempty"`
	AmtsdVal    float64 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 AmtsdVal,omitempty"`
	DgtlTknUnit float64 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 DgtlTknUnit,omitempty"`
}

type GenericIdentification47 struct {
	Id      Exact4AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Id"`
	Issr    Max4AlphaNumericText   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Issr"`
	SchmeNm Max4AlphaNumericText   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 SchmeNm,omitempty"`
}

type GenericIdentification84 struct {
	Id      RestrictedFINXMax34Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Id"`
	Issr    Max4AlphaNumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Issr"`
	SchmeNm Max4AlphaNumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 SchmeNm,omitempty"`
}

type GenericIdentification89 struct {
	Tp GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Tp"`
	Id RestrictedFINXMax30Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Id,omitempty"`
}

// Must match the pattern [A-Z]{2,2}[A-Z0-9]{9,9}[0-9]{1,1}
type ISINOct2015Identifier string

type ISODate time.Time

func (t *ISODate) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t ISODate) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type IdentificationSource4Choice struct {
	Cd    ExternalFinancialInstrumentIdentificationType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Cd,omitempty"`
	Prtry RestrictedFINExact2Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Prtry,omitempty"`
}

// May be no more than 140 items long
type Max140Text string

// May be no more than 16 items long
type Max16Text string

// May be no more than 350 items long
type Max350Text string

// Must match the pattern [a-zA-Z0-9]{1,4}
type Max4AlphaNumericText string

type OptionNumber1Choice struct {
	Nb Exact3NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Nb,omitempty"`
	Cd OptionNumber1Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Cd,omitempty"`
}

// May be one of UNSO
type OptionNumber1Code string

type OriginalAndCurrentQuantities4 struct {
	FaceAmt  float64 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 FaceAmt"`
	AmtsdVal float64 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 AmtsdVal"`
}

type OtherIdentification2 struct {
	Id  RestrictedFINXMax31Text     `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Id"`
	Sfx Max16Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Sfx,omitempty"`
	Tp  IdentificationSource4Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Tp"`
}

type PartyIdentification136Choice struct {
	AnyBIC  AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 AnyBIC,omitempty"`
	PrtryId GenericIdentification84 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 PrtryId,omitempty"`
}

type ProcessingPosition10Choice struct {
	Cd    ProcessingPosition3Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Cd,omitempty"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Prtry,omitempty"`
}

// May be one of AFTE, WITH, BEFO, INFO
type ProcessingPosition3Code string

type ProtectInstruction7 struct {
	TxTp    ProtectTransactionType3Code `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 TxTp"`
	TxId    RestrictedFINMax15Text      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 TxId,omitempty"`
	PrtctDt ISODate                     `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 PrtctDt,omitempty"`
}

// May be one of PROT
type ProtectTransactionType3Code string

// May be one of QALL
type Quantity1Code string

type Quantity55Choice struct {
	Cd                 Quantity1Code                       `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Cd,omitempty"`
	OrgnlAndCurFaceAmt OriginalAndCurrentQuantities4       `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 OrgnlAndCurFaceAmt,omitempty"`
	Qty                FinancialInstrumentQuantity36Choice `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Qty,omitempty"`
}

// Must match the pattern XX|TS
type RestrictedFINExact2Text string

// May be no more than 15 items long
type RestrictedFINMax15Text string

// Must match the pattern [0-9a-zA-Z/\-\?:\(\)\.\n\r,'\+ ]{1,140}
type RestrictedFINXMax140Text string

// Must match the pattern ([0-9a-zA-Z\-\?:\(\)\.,'\+ ]([0-9a-zA-Z\-\?:\(\)\.,'\+ ]*(/[0-9a-zA-Z\-\?:\(\)\.,'\+ ])?)*)
type RestrictedFINXMax16Text string

// Must match the pattern ([0-9a-zA-Z\-\?:\(\)\.,'\+ ]([0-9a-zA-Z\-\?:\(\)\.,'\+ ]*(/[0-9a-zA-Z\-\?:\(\)\.,'\+ ])?)*)
type RestrictedFINXMax30Text string

// Must match the pattern [0-9a-zA-Z/\-\?:\(\)\.,'\+ ]{1,31}
type RestrictedFINXMax31Text string

// Must match the pattern ([0-9a-zA-Z\-\?:\(\)\.,'\+ ]([0-9a-zA-Z\-\?:\(\)\.,'\+ ]*(/[0-9a-zA-Z\-\?:\(\)\.,'\+ ])?)*)
type RestrictedFINXMax34Text string

// Must match the pattern [0-9a-zA-Z/\-\?:\(\)\.\n\r,'\+ ]{1,350}
type RestrictedFINXMax350Text string

// Must match the pattern [0-9a-zA-Z/\-\?:\(\)\.,'\+ ]{1,35}
type RestrictedFINXMax35Text string

// May be one of CUST, ICSD, NCSD, SHHE
type SafekeepingPlace1Code string

// May be one of SHHE, ALLP
type SafekeepingPlace2Code string

type SafekeepingPlaceFormat45Choice struct {
	Id         SafekeepingPlaceTypeAndText9           `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Id,omitempty"`
	Ctry       CountryCode                            `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Ctry,omitempty"`
	DgtlLdgrId DTI2024Identifier                      `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 DgtlLdgrId,omitempty"`
	TpAndId    SafekeepingPlaceTypeAndIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 TpAndId,omitempty"`
	Prtry      GenericIdentification89                `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Prtry,omitempty"`
}

type SafekeepingPlaceTypeAndIdentification1 struct {
	SfkpgPlcTp SafekeepingPlace1Code   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 SfkpgPlcTp"`
	Id         AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Id"`
}

type SafekeepingPlaceTypeAndText9 struct {
	SfkpgPlcTp SafekeepingPlace2Code   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 SfkpgPlcTp"`
	Id         RestrictedFINXMax30Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Id,omitempty"`
}

type SecurityIdentification21 struct {
	ISIN   ISINOct2015Identifier    `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 ISIN,omitempty"`
	OthrId []OtherIdentification2   `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 OthrId,omitempty"`
	Desc   RestrictedFINXMax140Text `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Desc,omitempty"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:seev.040.002.13 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}
