// Code generated by z. DO NOT EDIT.

package sese_039_001_08

import (
	"bytes"
	"encoding/xml"
	"time"
)

type AcknowledgedAcceptedStatus23Choice struct {
	NoSpcfdRsn NoReasonCode              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 NoSpcfdRsn,omitempty"`
	Rsn        []AcknowledgementReason11 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Rsn,omitempty"`
}

type AcknowledgementReason11 struct {
	Cd          AcknowledgementReason14Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd"`
	AddtlRsnInf Max210Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AddtlRsnInf,omitempty"`
}

type AcknowledgementReason14Choice struct {
	Cd    AcknowledgementReason6Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd,omitempty"`
	Prtry GenericIdentification30    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Prtry,omitempty"`
}

// May be one of ADEA, SMPG, OTHR, NSTP, LATE
type AcknowledgementReason6Code string

type ActiveCurrencyAndAmount struct {
	Value float64            `xml:",chardata"`
	Ccy   ActiveCurrencyCode `xml:"Ccy,attr"`
}

// Must match the pattern [A-Z]{3,3}
type ActiveCurrencyCode string

type ActiveOrHistoricCurrencyAndAmount struct {
	Value float64                      `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode `xml:"Ccy,attr"`
}

// Must match the pattern [A-Z]{3,3}
type ActiveOrHistoricCurrencyCode string

// May be one of ADDR, PBOX, HOME, BIZZ, MLTO, DLVY
type AddressType2Code string

type AmountAndDirection51 struct {
	Amt                 ActiveCurrencyAndAmount           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Amt"`
	CdtDbtInd           CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 CdtDbtInd"`
	OrgnlCcyAndOrdrdAmt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 OrgnlCcyAndOrdrdAmt,omitempty"`
}

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type AnyBICDec2014Identifier string

type BlockChainAddressWallet3 struct {
	Id Max140Text              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Id"`
	Tp GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Tp,omitempty"`
	Nm Max70Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Nm,omitempty"`
}

type CashSettlementSystemPlace1Choice struct {
	DgtlLdgrId DTI2024Identifier       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 DgtlLdgrId,omitempty"`
	AnyBIC     AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AnyBIC,omitempty"`
	LEI        LEIIdentifier           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 LEI,omitempty"`
}

// Must match the pattern [A-Z]{2,2}
type CountryCode string

// May be one of CRDT, DBIT
type CreditDebitCode string

// Must match the pattern [1-9B-DF-HJ-NP-TV-XZ][0-9B-DF-HJ-NP-TV-XZ]{8,8}
type DTI2024Identifier string

type DateAndDateTime2Choice struct {
	Dt   ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Dt,omitempty"`
	DtTm ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 DtTm,omitempty"`
}

// May be one of VARI
type DateType3Code string

// May be one of OPEN, UKWN
type DateType4Code string

// May be one of FREE, APMT
type DeliveryReceiptType2Code string

type DeniedReason10 struct {
	Cd          DeniedReason15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd"`
	AddtlRsnInf Max210Text           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AddtlRsnInf,omitempty"`
}

type DeniedReason15Choice struct {
	Cd    DeniedReason6Code       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Prtry,omitempty"`
}

// May be one of ADEA, CDCY, CDRE, DCAN, DSET, DPRG, DREP, LATE, OTHR, CDRG
type DeniedReason6Code string

type DeniedStatus15Choice struct {
	NoSpcfdRsn NoReasonCode     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 NoSpcfdRsn,omitempty"`
	Rsn        []DeniedReason10 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Rsn,omitempty"`
}

type DigitalPaymentSettlement2 struct {
	FinInstrmId           SecurityIdentification19         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 FinInstrmId"`
	ElctrncMnyTknSttlmQty float64                          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 ElctrncMnyTknSttlmQty"`
	CshSttlmSysPlc        CashSettlementSystemPlace1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 CshSttlmSysPlc,omitempty"`
}

type Document struct {
	SctiesSttlmTxModReqStsAdvc SecuritiesSettlementTransactionModificationRequestStatusAdviceV08 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 SctiesSttlmTxModReqStsAdvc"`
}

// Must match the pattern [a-zA-Z0-9]{4}
type Exact4AlphaNumericText string

// May be no more than 4 items long
type ExternalFinancialInstrumentIdentificationType1Code string

type FinancialInstrumentQuantity33Choice struct {
	Unit        float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Unit,omitempty"`
	FaceAmt     float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 FaceAmt,omitempty"`
	AmtsdVal    float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AmtsdVal,omitempty"`
	DgtlTknUnit float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 DgtlTknUnit,omitempty"`
}

type GenericIdentification30 struct {
	Id      Exact4AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Id"`
	Issr    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Issr"`
	SchmeNm Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 SchmeNm,omitempty"`
}

type GenericIdentification36 struct {
	Id      Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Id"`
	Issr    Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Issr"`
	SchmeNm Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 SchmeNm,omitempty"`
}

// Must match the pattern [A-Z]{2,2}[A-Z0-9]{9,9}[0-9]{1,1}
type ISINOct2015Identifier string

type ISODate time.Time

func (t *ISODate) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t ISODate) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type ISODateTime time.Time

func (t *ISODateTime) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t ISODateTime) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

type IdentificationSource3Choice struct {
	Cd    ExternalFinancialInstrumentIdentificationType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd,omitempty"`
	Prtry Max35Text                                          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Prtry,omitempty"`
}

// Must match the pattern [A-Z0-9]{18,18}[0-9]{2,2}
type LEIIdentifier string

// May be no more than 140 items long
type Max140Text string

// May be no more than 16 items long
type Max16Text string

// May be no more than 210 items long
type Max210Text string

// May be no more than 350 items long
type Max350Text string

// May be no more than 35 items long
type Max35Text string

// May be no more than 70 items long
type Max70Text string

type ModificationProcessingStatus12Choice struct {
	AckdAccptd AcknowledgedAcceptedStatus23Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AckdAccptd,omitempty"`
	PdgPrcg    PendingProcessingStatus23Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 PdgPrcg,omitempty"`
	Dnd        DeniedStatus15Choice               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Dnd,omitempty"`
	Rjctd      RejectionStatus37Choice            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Rjctd,omitempty"`
	Rprd       RepairStatus13Choice               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Rprd,omitempty"`
	Modfd      ModificationStatus6Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Modfd,omitempty"`
	Prtry      ProprietaryStatusAndReason6        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Prtry,omitempty"`
}

type ModificationReason4 struct {
	Cd          ModificationReason4Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd"`
	AddtlRsnInf Max210Text                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AddtlRsnInf,omitempty"`
}

type ModificationReason4Choice struct {
	Cd    ModifiedStatusReason1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd,omitempty"`
	Prtry GenericIdentification30   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Prtry,omitempty"`
}

type ModificationStatus6Choice struct {
	NoSpcfdRsn NoReasonCode          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 NoSpcfdRsn,omitempty"`
	Rsn        []ModificationReason4 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Rsn,omitempty"`
}

// May be one of MDBY, OTHR
type ModifiedStatusReason1Code string

type NameAndAddress5 struct {
	Nm  Max350Text     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Nm"`
	Adr PostalAddress1 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Adr,omitempty"`
}

// May be one of NORE
type NoReasonCode string

type OriginalAndCurrentQuantities1 struct {
	FaceAmt  float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 FaceAmt"`
	AmtsdVal float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AmtsdVal"`
}

type OtherIdentification1 struct {
	Id  Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Id"`
	Sfx Max16Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Sfx,omitempty"`
	Tp  IdentificationSource3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Tp"`
}

type PartyIdentification120Choice struct {
	AnyBIC   AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AnyBIC,omitempty"`
	PrtryId  GenericIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 PrtryId,omitempty"`
	NmAndAdr NameAndAddress5         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 NmAndAdr,omitempty"`
}

type PartyIdentification127Choice struct {
	AnyBIC  AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AnyBIC,omitempty"`
	PrtryId GenericIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 PrtryId,omitempty"`
}

type PartyIdentification134Choice struct {
	AnyBIC   AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AnyBIC,omitempty"`
	PrtryId  GenericIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 PrtryId,omitempty"`
	NmAndAdr NameAndAddress5         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 NmAndAdr,omitempty"`
	Ctry     CountryCode             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Ctry,omitempty"`
}

type PartyIdentification144 struct {
	Id  PartyIdentification127Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Id"`
	LEI LEIIdentifier                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 LEI,omitempty"`
}

type PartyIdentification149 struct {
	Id  PartyIdentification134Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Id"`
	LEI LEIIdentifier                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 LEI,omitempty"`
}

type PartyIdentification257Choice struct {
	AnyBIC     AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AnyBIC,omitempty"`
	NmAndAdr   NameAndAddress5         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 NmAndAdr,omitempty"`
	Ctry       CountryCode             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Ctry,omitempty"`
	DgtlLdgrId DTI2024Identifier       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 DgtlLdgrId,omitempty"`
}

type PartyIdentification314 struct {
	Id     PartyIdentification257Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Id"`
	LEI    LEIIdentifier                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 LEI,omitempty"`
	PrcgId Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 PrcgId,omitempty"`
}

type PartyIdentificationAndAccount195 struct {
	Id                 PartyIdentification120Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Id"`
	LEI                LEIIdentifier                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 LEI,omitempty"`
	SfkpgAcct          SecuritiesAccount19          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 SfkpgAcct,omitempty"`
	BlckChainAdrOrWllt BlockChainAddressWallet3     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 BlckChainAdrOrWllt,omitempty"`
	PrcgId             Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 PrcgId,omitempty"`
}

type PendingProcessingReason20 struct {
	Cd          PendingProcessingReason22Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd"`
	AddtlRsnInf Max210Text                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AddtlRsnInf,omitempty"`
}

type PendingProcessingReason22Choice struct {
	Cd    PendingProcessingReason8Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd,omitempty"`
	Prtry GenericIdentification30      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Prtry,omitempty"`
}

// May be one of BLOC, ADEA, MINO, MUNO, NEXT, OTHR, DENO, CERT
type PendingProcessingReason8Code string

type PendingProcessingStatus23Choice struct {
	NoSpcfdRsn NoReasonCode                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 NoSpcfdRsn,omitempty"`
	Rsn        []PendingProcessingReason20 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Rsn,omitempty"`
}

type PostalAddress1 struct {
	AdrTp       AddressType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AdrTp,omitempty"`
	AdrLine     []Max70Text      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AdrLine,omitempty"`
	StrtNm      Max70Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 StrtNm,omitempty"`
	BldgNb      Max16Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 BldgNb,omitempty"`
	PstCd       Max16Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 PstCd,omitempty"`
	TwnNm       Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 TwnNm,omitempty"`
	CtrySubDvsn Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 CtrySubDvsn,omitempty"`
	Ctry        CountryCode      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Ctry"`
}

type ProprietaryReason4 struct {
	Rsn         GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Rsn,omitempty"`
	AddtlRsnInf Max210Text              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AddtlRsnInf,omitempty"`
}

type ProprietaryStatusAndReason6 struct {
	PrtrySts GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 PrtrySts"`
	PrtryRsn []ProprietaryReason4    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 PrtryRsn,omitempty"`
}

type Quantity51Choice struct {
	Qty             FinancialInstrumentQuantity33Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Qty,omitempty"`
	OrgnlAndCurFace OriginalAndCurrentQuantities1       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 OrgnlAndCurFace,omitempty"`
}

// May be one of DELI, RECE
type ReceiveDelivery1Code string

type RejectionReason42Choice struct {
	Cd    RejectionReason72Code   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Prtry,omitempty"`
}

type RejectionReason57 struct {
	Cd          RejectionReason42Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd"`
	AddtlRsnInf Max210Text              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AddtlRsnInf,omitempty"`
}

// May be one of SAFE, DQUA, ADEA, DSEC, LATE, CASH, DDEA, DTRD, PLCE, RTGS, NCRR, PHYS, REFE, DMON, MINO, BATC, MUNO, TXST, SETS, IIND, CAEV, CASY, DDAT, SETR, SDUT, INPS, OTHR, ICUS, ICAG, DEPT, IEXE, INVL, INVB, INVN, VALR
type RejectionReason72Code string

type RejectionStatus37Choice struct {
	NoSpcfdRsn NoReasonCode        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 NoSpcfdRsn,omitempty"`
	Rsn        []RejectionReason57 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Rsn,omitempty"`
}

type RepairReason10Choice struct {
	Cd    RepairReason4Code       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Prtry,omitempty"`
}

// May be one of BATC, CAEV, CASH, CASY, DDAT, DDEA, DMON, DQUA, DSEC, DTRD, IIND, MINO, MUNO, NCRR, PHYS, PLCE, REFE, RTGS, SAFE, SETR, SETS, TXST, INPS, SDUT, OTHR, IEXE, ICAG, DEPT, ICUS
type RepairReason4Code string

type RepairReason9 struct {
	Cd          RepairReason10Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd"`
	AddtlRsnInf Max210Text           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AddtlRsnInf,omitempty"`
}

type RepairStatus13Choice struct {
	NoSpcfdRsn NoReasonCode    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 NoSpcfdRsn,omitempty"`
	Rsn        []RepairReason9 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Rsn,omitempty"`
}

type SecuritiesAccount19 struct {
	Id Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Id"`
	Tp GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Tp,omitempty"`
	Nm Max70Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Nm,omitempty"`
}

type SecuritiesSettlementTransactionModificationRequestStatusAdviceV08 struct {
	ModReqRef          Max35Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 ModReqRef"`
	AcctOwnr           PartyIdentification144               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AcctOwnr,omitempty"`
	SfkpgAcct          SecuritiesAccount19                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 SfkpgAcct,omitempty"`
	BlckChainAdrOrWllt BlockChainAddressWallet3             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 BlckChainAdrOrWllt,omitempty"`
	TxId               TransactionIdentifications33         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 TxId,omitempty"`
	ModPrcgSts         ModificationProcessingStatus12Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 ModPrcgSts"`
	TxDtls             TransactionDetails182                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 TxDtls,omitempty"`
	SplmtryData        []SupplementaryData1                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 SplmtryData,omitempty"`
}

type SecurityIdentification19 struct {
	ISIN   ISINOct2015Identifier  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 ISIN,omitempty"`
	OthrId []OtherIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 OthrId,omitempty"`
	Desc   Max140Text             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Desc,omitempty"`
}

type SettlementDate19Choice struct {
	Dt   DateAndDateTime2Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Dt,omitempty"`
	DtCd SettlementDateCode8Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 DtCd,omitempty"`
}

type SettlementDateCode8Choice struct {
	Cd    DateType4Code           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Prtry,omitempty"`
}

type SettlementParties125 struct {
	Dpstry PartyIdentification314           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Dpstry,omitempty"`
	Pty1   PartyIdentificationAndAccount195 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Pty1,omitempty"`
	Pty2   PartyIdentificationAndAccount195 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Pty2,omitempty"`
	Pty3   PartyIdentificationAndAccount195 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Pty3,omitempty"`
	Pty4   PartyIdentificationAndAccount195 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Pty4,omitempty"`
	Pty5   PartyIdentificationAndAccount195 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Pty5,omitempty"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type TradeDate8Choice struct {
	Dt   DateAndDateTime2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Dt,omitempty"`
	DtCd TradeDateCode3Choice   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 DtCd,omitempty"`
}

type TradeDateCode3Choice struct {
	Cd    DateType3Code           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Prtry,omitempty"`
}

type TransactionDetails182 struct {
	FinInstrmId     SecurityIdentification19  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 FinInstrmId"`
	SctiesMvmntTp   ReceiveDelivery1Code      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 SctiesMvmntTp"`
	Pmt             DeliveryReceiptType2Code  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Pmt"`
	SttlmQty        Quantity51Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 SttlmQty"`
	SttlmAmt        AmountAndDirection51      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 SttlmAmt,omitempty"`
	DgtlPmtSttlm    DigitalPaymentSettlement2 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 DgtlPmtSttlm,omitempty"`
	SttlmDt         SettlementDate19Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 SttlmDt"`
	TradDt          TradeDate8Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 TradDt,omitempty"`
	DlvrgSttlmPties SettlementParties125      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 DlvrgSttlmPties,omitempty"`
	RcvgSttlmPties  SettlementParties125      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 RcvgSttlmPties,omitempty"`
	Invstr          PartyIdentification149    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 Invstr,omitempty"`
}

type TransactionIdentifications33 struct {
	AcctOwnrTxId      Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AcctOwnrTxId"`
	AcctSvcrTxId      Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 AcctSvcrTxId,omitempty"`
	MktInfrstrctrTxId Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 MktInfrstrctrTxId,omitempty"`
	PrcrTxId          Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 PrcrTxId,omitempty"`
	OthrId            Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.039.001.08 OthrId,omitempty"`
}

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
