// Code generated by z. DO NOT EDIT.

package sese_036_001_10

import (
	"bytes"
	"encoding/xml"
	"time"
)

type ActiveCurrencyAndAmount struct {
	Value float64            `xml:",chardata"`
	Ccy   ActiveCurrencyCode `xml:"Ccy,attr"`
}

// Must match the pattern [A-Z]{3,3}
type ActiveCurrencyCode string

type ActiveOrHistoricCurrencyAndAmount struct {
	Value float64                      `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode `xml:"Ccy,attr"`
}

// Must match the pattern [A-Z]{3,3}
type ActiveOrHistoricCurrencyCode string

// May be one of ADDR, PBOX, HOME, BIZZ, MLTO, DLVY
type AddressType2Code string

type AlternatePartyIdentification7 struct {
	IdTp    IdentificationType42Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 IdTp"`
	Ctry    CountryCode                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Ctry"`
	AltrnId Max35Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AltrnId"`
}

type AmountAndDirection21 struct {
	Amt       ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Amt"`
	CdtDbtInd CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 CdtDbtInd,omitempty"`
}

type AmountAndDirection49 struct {
	Amt                 ActiveCurrencyAndAmount           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Amt"`
	CdtDbtInd           CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 CdtDbtInd,omitempty"`
	OrgnlCcyAndOrdrdAmt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 OrgnlCcyAndOrdrdAmt,omitempty"`
	FXDtls              ForeignExchangeTerms23            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 FXDtls,omitempty"`
}

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type AnyBICDec2014Identifier string

// May be one of LAMI, NBOR, YBOR
type AutoBorrowing1Code string

type AutomaticBorrowing6Choice struct {
	Cd    AutoBorrowing1Code      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type BeneficialOwnership4Choice struct {
	Ind   bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Ind,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type BlockChainAddressWallet3 struct {
	Id Max140Text              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Id"`
	Tp GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Tp,omitempty"`
	Nm Max70Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Nm,omitempty"`
}

// May be one of BLPA, BLCH
type BlockTrade1Code string

type BlockTrade4Choice struct {
	Cd    BlockTrade1Code         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type CashAccountIdentification9Choice struct {
	IBAN             IBAN2007Identifier       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 IBAN,omitempty"`
	BlckChainCshWllt BlockChainAddressWallet3 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 BlckChainCshWllt,omitempty"`
	Prtry            Max34Text                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

// May be one of DCSS, GROS, NETS
type CashSettlementSystem3Code string

type CashSettlementSystem6Choice struct {
	Cd    CashSettlementSystem3Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type CashSettlementSystemPlace1Choice struct {
	DgtlLdgrId DTI2024Identifier       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 DgtlLdgrId,omitempty"`
	AnyBIC     AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AnyBIC,omitempty"`
	LEI        LEIIdentifier           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 LEI,omitempty"`
}

type CentralCounterPartyEligibility4Choice struct {
	Ind   bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Ind,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

// Must match the pattern [A-Z]{2,2}
type CountryCode string

// May be one of CRDT, DBIT
type CreditDebitCode string

// Must match the pattern [1-9B-DF-HJ-NP-TV-XZ][0-9B-DF-HJ-NP-TV-XZ]{8,8}
type DTI2024Identifier string

type DateAndDateTime2Choice struct {
	Dt   ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Dt,omitempty"`
	DtTm ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 DtTm,omitempty"`
}

type DateCode18Choice struct {
	Cd    DateType5Code           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

// May be one of OPEN
type DateType5Code string

// May be one of FREE, APMT
type DeliveryReceiptType2Code string

type DigitalPaymentSettlement2 struct {
	FinInstrmId           SecurityIdentification19         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 FinInstrmId"`
	ElctrncMnyTknSttlmQty float64                          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 ElctrncMnyTknSttlmQty"`
	CshSttlmSysPlc        CashSettlementSystemPlace1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 CshSttlmSysPlc,omitempty"`
}

type Document struct {
	SctiesFincgModInstr SecuritiesFinancingModificationInstructionV10 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SctiesFincgModInstr"`
}

// Must match the pattern [0-9]{3}
type Exact3NumericText string

// Must match the pattern [a-zA-Z0-9]{4}
type Exact4AlphaNumericText string

// Must match the pattern [0-9]{4}
type Exact4NumericText string

// May be no more than 4 items long
type ExternalFinancialInstrumentIdentificationType1Code string

type FXStandingInstruction4Choice struct {
	Ind   bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Ind,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type FinancialInstrumentQuantity33Choice struct {
	Unit        float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Unit,omitempty"`
	FaceAmt     float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 FaceAmt,omitempty"`
	AmtsdVal    float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AmtsdVal,omitempty"`
	DgtlTknUnit float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 DgtlTknUnit,omitempty"`
}

type ForeignExchangeTerms23 struct {
	UnitCcy  ActiveCurrencyCode      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 UnitCcy"`
	QtdCcy   ActiveCurrencyCode      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 QtdCcy"`
	XchgRate float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 XchgRate"`
	RsltgAmt ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 RsltgAmt"`
}

type GenericIdentification30 struct {
	Id      Exact4AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Id"`
	Issr    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Issr"`
	SchmeNm Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SchmeNm,omitempty"`
}

type GenericIdentification36 struct {
	Id      Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Id"`
	Issr    Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Issr"`
	SchmeNm Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SchmeNm,omitempty"`
}

type GenericIdentification78 struct {
	Tp GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Tp"`
	Id Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Id,omitempty"`
}

// Must match the pattern [A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}
type IBAN2007Identifier string

// Must match the pattern [A-Z]{2,2}[A-Z0-9]{9,9}[0-9]{1,1}
type ISINOct2015Identifier string

type ISODate time.Time

func (t *ISODate) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t ISODate) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type ISODateTime time.Time

func (t *ISODateTime) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t ISODateTime) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

type IdentificationSource3Choice struct {
	Cd    ExternalFinancialInstrumentIdentificationType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry Max35Text                                          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type IdentificationType42Choice struct {
	Cd    TypeOfIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

// May be one of A001, A002, A003, A004, A005, A006, A007, A008, A009, A010, A011, A012, A013, A014, NARR
type InterestComputationMethod2Code string

type InterestComputationMethodFormat4Choice struct {
	Cd    InterestComputationMethod2Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

// Must match the pattern [A-Z0-9]{18,18}[0-9]{2,2}
type LEIIdentifier string

// May be one of FRAN
type LegalFramework1Code string

type LegalFramework3Choice struct {
	Cd    LegalFramework1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

// May be one of CLNT, MAKT
type MarketClientSide1Code string

type MarketClientSide6Choice struct {
	Cd    MarketClientSide1Code   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

// May be no more than 140 items long
type Max140Text string

// May be no more than 16 items long
type Max16Text string

// May be no more than 34 items long
type Max34Text string

// May be no more than 350 items long
type Max350Text string

// May be no more than 35 items long
type Max35Text string

// May be no more than 70 items long
type Max70Text string

// May be no more than 8 items long
type Max8Text string

type NameAndAddress5 struct {
	Nm  Max350Text     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Nm"`
	Adr PostalAddress1 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Adr,omitempty"`
}

type NettingEligibility4Choice struct {
	Ind   bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Ind,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type OtherIdentification1 struct {
	Id  Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Id"`
	Sfx Max16Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Sfx,omitempty"`
	Tp  IdentificationSource3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Tp"`
}

// May be one of A144, NRST, RSTR
type OwnershipLegalRestrictions1Code string

type PartyIdentification120Choice struct {
	AnyBIC   AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AnyBIC,omitempty"`
	PrtryId  GenericIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 PrtryId,omitempty"`
	NmAndAdr NameAndAddress5         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 NmAndAdr,omitempty"`
}

type PartyIdentification127Choice struct {
	AnyBIC  AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AnyBIC,omitempty"`
	PrtryId GenericIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 PrtryId,omitempty"`
}

type PartyIdentification144 struct {
	Id  PartyIdentification127Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Id"`
	LEI LEIIdentifier                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 LEI,omitempty"`
}

type PartyIdentification257Choice struct {
	AnyBIC     AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AnyBIC,omitempty"`
	NmAndAdr   NameAndAddress5         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 NmAndAdr,omitempty"`
	Ctry       CountryCode             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Ctry,omitempty"`
	DgtlLdgrId DTI2024Identifier       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 DgtlLdgrId,omitempty"`
}

type PartyIdentification315 struct {
	Id       PartyIdentification257Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Id"`
	LEI      LEIIdentifier                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 LEI,omitempty"`
	AltrnId  AlternatePartyIdentification7 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AltrnId,omitempty"`
	PrcgDt   DateAndDateTime2Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 PrcgDt,omitempty"`
	PrcgId   Max35Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 PrcgId,omitempty"`
	AddtlInf PartyTextInformation1         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AddtlInf,omitempty"`
}

type PartyIdentificationAndAccount199 struct {
	Id                 PartyIdentification120Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Id"`
	LEI                LEIIdentifier                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 LEI,omitempty"`
	AltrnId            AlternatePartyIdentification7 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AltrnId,omitempty"`
	SfkpgAcct          SecuritiesAccount22           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SfkpgAcct,omitempty"`
	BlckChainAdrOrWllt BlockChainAddressWallet3      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 BlckChainAdrOrWllt,omitempty"`
	PrcgDt             DateAndDateTime2Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 PrcgDt,omitempty"`
	PrcgId             Max35Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 PrcgId,omitempty"`
	AddtlInf           PartyTextInformation1         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AddtlInf,omitempty"`
}

type PartyTextInformation1 struct {
	DclrtnDtls  Max350Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 DclrtnDtls,omitempty"`
	PtyCtctDtls Max140Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 PtyCtctDtls,omitempty"`
	RegnDtls    Max350Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 RegnDtls,omitempty"`
}

type PostalAddress1 struct {
	AdrTp       AddressType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AdrTp,omitempty"`
	AdrLine     []Max70Text      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AdrLine,omitempty"`
	StrtNm      Max70Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 StrtNm,omitempty"`
	BldgNb      Max16Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 BldgNb,omitempty"`
	PstCd       Max16Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 PstCd,omitempty"`
	TwnNm       Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 TwnNm,omitempty"`
	CtrySubDvsn Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 CtrySubDvsn,omitempty"`
	Ctry        CountryCode      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Ctry"`
}

type PriorityNumeric4Choice struct {
	Nmrc  Exact4NumericText       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Nmrc,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type QuantityAndAccount119 struct {
	SttlmQty           FinancialInstrumentQuantity33Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SttlmQty"`
	AcctOwnr           PartyIdentification144              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AcctOwnr,omitempty"`
	SfkpgAcct          SecuritiesAccount19                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SfkpgAcct,omitempty"`
	BlckChainAdrOrWllt BlockChainAddressWallet3            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 BlckChainAdrOrWllt,omitempty"`
	CshAcct            CashAccountIdentification9Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 CshAcct,omitempty"`
	SfkpgPlc           SafeKeepingPlace5                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SfkpgPlc,omitempty"`
}

type Rate2 struct {
	Sgn  bool    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Sgn,omitempty"`
	Rate float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Rate"`
}

type RateName1 struct {
	Issr   Max8Text  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Issr,omitempty"`
	RateNm Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 RateNm"`
}

type RateOrName1Choice struct {
	Rate   Rate2     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Rate,omitempty"`
	RateNm RateName1 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 RateNm,omitempty"`
}

// May be one of FIXE, FORF, VARI
type RateType1Code string

type RateType35Choice struct {
	Cd    RateType1Code           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type RepurchaseType21Choice struct {
	Cd    RepurchaseType8Code     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

// May be one of PADJ, ROLP, RATE, CALL
type RepurchaseType8Code string

type Restriction5Choice struct {
	Cd    OwnershipLegalRestrictions1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type RevaluationIndicator3Choice struct {
	Ind   bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Ind,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type SafeKeepingPlace5 struct {
	SfkpgPlcFrmt SafekeepingPlaceFormat41Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SfkpgPlcFrmt,omitempty"`
	LEI          LEIIdentifier                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 LEI,omitempty"`
}

// May be one of CUST, ICSD, NCSD, SHHE
type SafekeepingPlace1Code string

// May be one of SHHE
type SafekeepingPlace3Code string

type SafekeepingPlaceFormat41Choice struct {
	Id         SafekeepingPlaceTypeAndText8           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Id,omitempty"`
	Ctry       CountryCode                            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Ctry,omitempty"`
	DgtlLdgrId DTI2024Identifier                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 DgtlLdgrId,omitempty"`
	TpAndId    SafekeepingPlaceTypeAndIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 TpAndId,omitempty"`
	Prtry      GenericIdentification78                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type SafekeepingPlaceTypeAndIdentification1 struct {
	SfkpgPlcTp SafekeepingPlace1Code   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SfkpgPlcTp"`
	Id         AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Id"`
}

type SafekeepingPlaceTypeAndText8 struct {
	SfkpgPlcTp SafekeepingPlace3Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SfkpgPlcTp"`
	Id         Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Id,omitempty"`
}

type SecuritiesAccount19 struct {
	Id Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Id"`
	Tp GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Tp,omitempty"`
	Nm Max70Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Nm,omitempty"`
}

type SecuritiesAccount22 struct {
	Id Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Id"`
	Tp GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Tp,omitempty"`
	Nm Max70Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Nm,omitempty"`
}

type SecuritiesFinancingModificationInstructionV10 struct {
	TxTpAndModAddtlParams TransactionTypeAndAdditionalParameters23 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 TxTpAndModAddtlParams"`
	TradDtls              SecuritiesTradeDetails100                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 TradDtls"`
	FinInstrmId           SecurityIdentification19                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 FinInstrmId"`
	QtyAndAcctDtls        QuantityAndAccount119                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 QtyAndAcctDtls"`
	SctiesFincgAddtlDtls  SecuritiesFinancingTransactionDetails58  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SctiesFincgAddtlDtls"`
	SttlmParams           SettlementDetails226                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SttlmParams,omitempty"`
	DlvrgSttlmPties       SettlementParties127                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 DlvrgSttlmPties,omitempty"`
	RcvgSttlmPties        SettlementParties127                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 RcvgSttlmPties,omitempty"`
	OpngSttlmAmt          AmountAndDirection49                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 OpngSttlmAmt,omitempty"`
	OpngDgtlSttlmAmt      DigitalPaymentSettlement2                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 OpngDgtlSttlmAmt,omitempty"`
	SplmtryData           []SupplementaryData1                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SplmtryData,omitempty"`
}

type SecuritiesFinancingTransactionDetails58 struct {
	SctiesFincgTradId     Max35Text                              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SctiesFincgTradId,omitempty"`
	SctiesFincgUnqTxIdr   UTIIdentifier                          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SctiesFincgUnqTxIdr,omitempty"`
	ClsgLegId             Max35Text                              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 ClsgLegId,omitempty"`
	TermntnDt             TerminationDate6Choice                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 TermntnDt,omitempty"`
	RateChngDt            DateAndDateTime2Choice                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 RateChngDt,omitempty"`
	EarlstCallBckDt       DateAndDateTime2Choice                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 EarlstCallBckDt,omitempty"`
	ComssnClctnDt         DateAndDateTime2Choice                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 ComssnClctnDt,omitempty"`
	RateTp                RateType35Choice                       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 RateTp,omitempty"`
	Rvaltn                RevaluationIndicator3Choice            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Rvaltn,omitempty"`
	LglFrmwk              LegalFramework3Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 LglFrmwk,omitempty"`
	IntrstCmptnMtd        InterestComputationMethodFormat4Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 IntrstCmptnMtd,omitempty"`
	MtrtyDtMod            bool                                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 MtrtyDtMod,omitempty"`
	IntrstPmt             bool                                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 IntrstPmt,omitempty"`
	VarblRateSpprt        RateName1                              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 VarblRateSpprt,omitempty"`
	RpRate                Rate2                                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 RpRate,omitempty"`
	StockLnMrgn           Rate2                                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 StockLnMrgn,omitempty"`
	SctiesHrcut           Rate2                                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SctiesHrcut,omitempty"`
	ChrgsRate             Rate2                                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 ChrgsRate,omitempty"`
	PricgRate             RateOrName1Choice                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 PricgRate,omitempty"`
	Sprd                  Rate2                                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Sprd,omitempty"`
	TxCallDely            Exact3NumericText                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 TxCallDely,omitempty"`
	TtlNbOfCollInstrs     Exact3NumericText                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 TtlNbOfCollInstrs,omitempty"`
	LclBrkrComssn         AmountAndDirection21                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 LclBrkrComssn,omitempty"`
	DealAmt               AmountAndDirection21                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 DealAmt,omitempty"`
	AcrdIntrstAmt         AmountAndDirection21                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AcrdIntrstAmt,omitempty"`
	FrftAmt               AmountAndDirection21                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 FrftAmt,omitempty"`
	PrmAmt                AmountAndDirection21                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 PrmAmt,omitempty"`
	TermntnAmtPerPcOfColl AmountAndDirection21                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 TermntnAmtPerPcOfColl,omitempty"`
	TermntnTxAmt          AmountAndDirection21                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 TermntnTxAmt,omitempty"`
	ScndLegNrrtv          Max140Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 ScndLegNrrtv,omitempty"`
}

// May be one of REPU, RVPO, SECB, SECL, BSBK, SBBK
type SecuritiesFinancingTransactionType2Code string

type SecuritiesRTGS4Choice struct {
	Ind   bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Ind,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type SecuritiesTradeDetails100 struct {
	TradDt             DateAndDateTime2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 TradDt,omitempty"`
	OpngSttlmDt        DateAndDateTime2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 OpngSttlmDt"`
	NbOfDaysAcrd       float64                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 NbOfDaysAcrd,omitempty"`
	InstrPrcgAddtlDtls Max350Text             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 InstrPrcgAddtlDtls,omitempty"`
}

type SecurityIdentification19 struct {
	ISIN   ISINOct2015Identifier  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 ISIN,omitempty"`
	OthrId []OtherIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 OthrId,omitempty"`
	Desc   Max140Text             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Desc,omitempty"`
}

type SettlementDetails226 struct {
	HldInd         bool                                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 HldInd,omitempty"`
	Prty           PriorityNumeric4Choice                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prty,omitempty"`
	SttlmTxCond    []SettlementTransactionCondition45Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SttlmTxCond,omitempty"`
	SttlgCpcty     SettlingCapacity7Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SttlgCpcty,omitempty"`
	StmpDtyTaxBsis GenericIdentification30                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 StmpDtyTaxBsis,omitempty"`
	SctiesRTGS     SecuritiesRTGS4Choice                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SctiesRTGS,omitempty"`
	BnfclOwnrsh    BeneficialOwnership4Choice               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 BnfclOwnrsh,omitempty"`
	CshClrSys      CashSettlementSystem6Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 CshClrSys,omitempty"`
	TaxCpcty       TaxCapacityParty4Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 TaxCpcty,omitempty"`
	MktClntSd      MarketClientSide6Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 MktClntSd,omitempty"`
	FxStgInstr     FXStandingInstruction4Choice             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 FxStgInstr,omitempty"`
	BlckTrad       BlockTrade4Choice                        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 BlckTrad,omitempty"`
	LglRstrctns    Restriction5Choice                       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 LglRstrctns,omitempty"`
	SttlmSysMtd    SettlementSystemMethod4Choice            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SttlmSysMtd,omitempty"`
	NetgElgblty    NettingEligibility4Choice                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 NetgElgblty,omitempty"`
	CCPElgblty     CentralCounterPartyEligibility4Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 CCPElgblty,omitempty"`
	Trckg          Tracking4Choice                          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Trckg,omitempty"`
	AutomtcBrrwg   AutomaticBorrowing6Choice                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AutomtcBrrwg,omitempty"`
	PrtlSttlmInd   SettlementTransactionCondition5Code      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 PrtlSttlmInd,omitempty"`
	ElgblForColl   bool                                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 ElgblForColl,omitempty"`
}

type SettlementParties127 struct {
	Dpstry PartyIdentification315           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Dpstry,omitempty"`
	Pty1   PartyIdentificationAndAccount199 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Pty1,omitempty"`
	Pty2   PartyIdentificationAndAccount199 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Pty2,omitempty"`
	Pty3   PartyIdentificationAndAccount199 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Pty3,omitempty"`
	Pty4   PartyIdentificationAndAccount199 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Pty4,omitempty"`
	Pty5   PartyIdentificationAndAccount199 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Pty5,omitempty"`
}

// May be one of NSET, YSET
type SettlementSystemMethod1Code string

type SettlementSystemMethod4Choice struct {
	Cd    SettlementSystemMethod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

// May be one of ADEA, ASGN, BUTC, CLEN, DLWM, DIRT, DRAW, EXER, EXPI, FRCL, GATE, KNOC, NOMC, PENS, PHYS, RHYP, RESI, SHOR, SPDL, SPST, TRAN, TRIP, UNEX
type SettlementTransactionCondition20Code string

type SettlementTransactionCondition45Choice struct {
	Cd    SettlementTransactionCondition20Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

// May be one of PART, NPAR, PARC, PARQ
type SettlementTransactionCondition5Code string

// May be one of SAGE, CUST, SPRI, RISP
type SettlingCapacity2Code string

type SettlingCapacity7Choice struct {
	Cd    SettlingCapacity2Code   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type TaxCapacityParty4Choice struct {
	Cd    TaxLiability1Code       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

// May be one of PRIN, AGEN
type TaxLiability1Code string

type TerminationDate6Choice struct {
	Dt DateAndDateTime2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Dt,omitempty"`
	Cd DateCode18Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Cd,omitempty"`
}

type Tracking4Choice struct {
	Ind   bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Ind,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Prtry,omitempty"`
}

type TransactionTypeAndAdditionalParameters23 struct {
	AcctOwnrTxId    Max35Text                               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AcctOwnrTxId"`
	AcctSvcrTxId    Max35Text                               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 AcctSvcrTxId,omitempty"`
	SctiesFincgTxTp SecuritiesFinancingTransactionType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 SctiesFincgTxTp"`
	Pmt             DeliveryReceiptType2Code                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 Pmt"`
	ModTp           RepurchaseType21Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 ModTp,omitempty"`
	CmonId          Max35Text                               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 CmonId,omitempty"`
	PoolId          Max35Text                               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 PoolId,omitempty"`
	NonceId         Max35Text                               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.036.001.10 NonceId,omitempty"`
}

// May be one of ARNU, CCPT, CHTY, CORP, DRLC, FIIN, TXID
type TypeOfIdentification1Code string

// Must match the pattern [A-Z0-9]{18}[0-9]{2}[A-Z0-9]{0,32}
type UTIIdentifier string

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
