// Code generated by z. DO NOT EDIT.

package sese_030_001_09

import (
	"bytes"
	"encoding/xml"
	"time"
)

type AdditionalInformation26 struct {
	AcctOwnrTxId       Max35Text                           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 AcctOwnrTxId,omitempty"`
	ClssfctnTp         ClassificationType32Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 ClssfctnTp,omitempty"`
	SfkpgAcct          SecuritiesAccount19                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 SfkpgAcct,omitempty"`
	BlckChainAdrOrWllt BlockChainAddressWallet3            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 BlckChainAdrOrWllt,omitempty"`
	FinInstrmId        SecurityIdentification19            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 FinInstrmId,omitempty"`
	Qty                FinancialInstrumentQuantity33Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Qty,omitempty"`
	FctvDt             DateAndDateTime2Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 FctvDt,omitempty"`
	XpryDt             DateAndDateTime2Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 XpryDt,omitempty"`
	CutOffDt           DateAndDateTime2Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 CutOffDt,omitempty"`
	Invstr             PartyIdentification136              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Invstr,omitempty"`
	DlvrgPty1          PartyIdentificationAndAccount195    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 DlvrgPty1,omitempty"`
	RcvgPty1           PartyIdentificationAndAccount195    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 RcvgPty1,omitempty"`
	TxSbjtToBuyIn      bool                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 TxSbjtToBuyIn,omitempty"`
}

// May be one of ADDR, PBOX, HOME, BIZZ, MLTO, DLVY
type AddressType2Code string

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type AnyBICDec2014Identifier string

// May be one of LAMI, NBOR, YBOR, RTRN
type AutoBorrowing2Code string

type AutomaticBorrowing7Choice struct {
	Cd    AutoBorrowing2Code      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Prtry,omitempty"`
}

type BlockChainAddressWallet3 struct {
	Id Max140Text              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Id"`
	Tp GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Tp,omitempty"`
	Nm Max70Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Nm,omitempty"`
}

// Must match the pattern [A-Z]{6,6}
type CFIOct2015Identifier string

type ClassificationType32Choice struct {
	ClssfctnFinInstrm CFIOct2015Identifier    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 ClssfctnFinInstrm,omitempty"`
	AltrnClssfctn     GenericIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 AltrnClssfctn,omitempty"`
}

// Must match the pattern [A-Z]{2,2}
type CountryCode string

type DateAndDateTime2Choice struct {
	Dt   ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Dt,omitempty"`
	DtTm ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 DtTm,omitempty"`
}

type Document struct {
	SctiesSttlmCondsModReq SecuritiesSettlementConditionsModificationRequestV09 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 SctiesSttlmCondsModReq"`
}

type DocumentNumber5Choice struct {
	ShrtNb  Exact3NumericText                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 ShrtNb,omitempty"`
	LngNb   ISO20022MessageIdentificationText `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 LngNb,omitempty"`
	PrtryNb GenericIdentification36           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 PrtryNb,omitempty"`
}

// Must match the pattern [0-9]{3}
type Exact3NumericText string

// Must match the pattern [a-zA-Z0-9]{4}
type Exact4AlphaNumericText string

// Must match the pattern [0-9]{4}
type Exact4NumericText string

// May be no more than 4 items long
type ExternalFinancialInstrumentIdentificationType1Code string

type FinancialInstrumentQuantity33Choice struct {
	Unit        float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Unit,omitempty"`
	FaceAmt     float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 FaceAmt,omitempty"`
	AmtsdVal    float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 AmtsdVal,omitempty"`
	DgtlTknUnit float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 DgtlTknUnit,omitempty"`
}

type GenericIdentification30 struct {
	Id      Exact4AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Id"`
	Issr    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Issr"`
	SchmeNm Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 SchmeNm,omitempty"`
}

type GenericIdentification36 struct {
	Id      Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Id"`
	Issr    Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Issr"`
	SchmeNm Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 SchmeNm,omitempty"`
}

type HoldIndicator6 struct {
	Ind bool                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Ind"`
	Rsn []RegistrationReason5 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Rsn,omitempty"`
}

// Must match the pattern [A-Z]{2,2}[A-Z0-9]{9,9}[0-9]{1,1}
type ISINOct2015Identifier string

// Must match the pattern [a-z]{4}\.[0-9]{3}\.[0-9]{3}\.[0-9]{2}
type ISO20022MessageIdentificationText string

type ISODate time.Time

func (t *ISODate) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t ISODate) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type ISODateTime time.Time

func (t *ISODateTime) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t ISODateTime) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

type IdentificationSource3Choice struct {
	Cd    ExternalFinancialInstrumentIdentificationType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Cd,omitempty"`
	Prtry Max35Text                                          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Prtry,omitempty"`
}

// Must match the pattern [A-Z0-9]{18,18}[0-9]{2,2}
type LEIIdentifier string

// May be one of LINK, UNLK, SOFT
type LinkageType1Code string

type LinkageType3Choice struct {
	Cd    LinkageType1Code        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Prtry,omitempty"`
}

type Linkages62 struct {
	PrcgPos ProcessingPosition8Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 PrcgPos,omitempty"`
	MsgNb   DocumentNumber5Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 MsgNb,omitempty"`
	Ref     References74Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Ref"`
	RefOwnr PartyIdentification127Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 RefOwnr,omitempty"`
}

type MatchingDenied3Choice struct {
	Cd    MatchingProcess1Code    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Prtry,omitempty"`
}

// May be one of UNMT, MTRE
type MatchingProcess1Code string

// May be no more than 140 items long
type Max140Text string

// May be no more than 16 items long
type Max16Text string

// May be no more than 210 items long
type Max210Text string

// May be no more than 350 items long
type Max350Text string

// May be no more than 35 items long
type Max35Text string

// May be no more than 52 items long
type Max52Text string

// May be no more than 70 items long
type Max70Text string

type NameAndAddress5 struct {
	Nm  Max350Text     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Nm"`
	Adr PostalAddress1 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Adr,omitempty"`
}

type OtherIdentification1 struct {
	Id  Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Id"`
	Sfx Max16Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Sfx,omitempty"`
	Tp  IdentificationSource3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Tp"`
}

type PartyIdentification120Choice struct {
	AnyBIC   AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 AnyBIC,omitempty"`
	PrtryId  GenericIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 PrtryId,omitempty"`
	NmAndAdr NameAndAddress5         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 NmAndAdr,omitempty"`
}

type PartyIdentification127Choice struct {
	AnyBIC  AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 AnyBIC,omitempty"`
	PrtryId GenericIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 PrtryId,omitempty"`
}

type PartyIdentification136 struct {
	Id  PartyIdentification120Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Id"`
	LEI LEIIdentifier                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 LEI,omitempty"`
}

type PartyIdentification144 struct {
	Id  PartyIdentification127Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Id"`
	LEI LEIIdentifier                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 LEI,omitempty"`
}

type PartyIdentificationAndAccount195 struct {
	Id                 PartyIdentification120Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Id"`
	LEI                LEIIdentifier                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 LEI,omitempty"`
	SfkpgAcct          SecuritiesAccount19          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 SfkpgAcct,omitempty"`
	BlckChainAdrOrWllt BlockChainAddressWallet3     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 BlckChainAdrOrWllt,omitempty"`
	PrcgId             Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 PrcgId,omitempty"`
}

type PostalAddress1 struct {
	AdrTp       AddressType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 AdrTp,omitempty"`
	AdrLine     []Max70Text      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 AdrLine,omitempty"`
	StrtNm      Max70Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 StrtNm,omitempty"`
	BldgNb      Max16Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 BldgNb,omitempty"`
	PstCd       Max16Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 PstCd,omitempty"`
	TwnNm       Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 TwnNm,omitempty"`
	CtrySubDvsn Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 CtrySubDvsn,omitempty"`
	Ctry        CountryCode      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Ctry"`
}

type PriorityNumeric4Choice struct {
	Nmrc  Exact4NumericText       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Nmrc,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Prtry,omitempty"`
}

// May be one of AFTE, BEFO, WITH
type ProcessingPosition4Code string

type ProcessingPosition8Choice struct {
	Cd    ProcessingPosition4Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Prtry,omitempty"`
}

type References27 struct {
	AcctOwnrTxId            Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 AcctOwnrTxId,omitempty"`
	AcctSvcrTxId            Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 AcctSvcrTxId,omitempty"`
	MktInfrstrctrTxId       Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 MktInfrstrctrTxId,omitempty"`
	CtrPtyMktInfrstrctrTxId Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 CtrPtyMktInfrstrctrTxId,omitempty"`
	PrcrTxId                Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 PrcrTxId,omitempty"`
	PoolId                  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 PoolId,omitempty"`
	CmonId                  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 CmonId,omitempty"`
	TradId                  Max52Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 TradId,omitempty"`
}

type References74Choice struct {
	SctiesSttlmTxId         Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 SctiesSttlmTxId,omitempty"`
	IntraPosMvmntId         Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 IntraPosMvmntId,omitempty"`
	IntraBalMvmntId         Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 IntraBalMvmntId,omitempty"`
	AcctSvcrTxId            Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 AcctSvcrTxId,omitempty"`
	MktInfrstrctrTxId       Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 MktInfrstrctrTxId,omitempty"`
	CtrPtyMktInfrstrctrTxId Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 CtrPtyMktInfrstrctrTxId,omitempty"`
	PoolId                  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 PoolId,omitempty"`
	CmonId                  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 CmonId,omitempty"`
	TradId                  Max52Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 TradId,omitempty"`
	OthrTxId                Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 OthrTxId,omitempty"`
}

type Registration10Choice struct {
	Cd    Registration2Code       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Prtry,omitempty"`
}

// May be one of PTYH, CSDH, CDEL, CVAL
type Registration2Code string

type RegistrationReason5 struct {
	Cd       Registration10Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Cd"`
	AddtlInf Max210Text           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 AddtlInf,omitempty"`
}

type RequestDetails27 struct {
	Ref          References27                        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Ref"`
	RstrctnRef   []RestrictionIdentification1        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 RstrctnRef,omitempty"`
	AutomtcBrrwg AutomaticBorrowing7Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 AutomtcBrrwg,omitempty"`
	RtnInd       bool                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 RtnInd,omitempty"`
	Lkg          LinkageType3Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Lkg,omitempty"`
	Prty         PriorityNumeric4Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Prty,omitempty"`
	OthrPrcg     []GenericIdentification30           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 OthrPrcg,omitempty"`
	PrtlSttlmInd SettlementTransactionCondition5Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 PrtlSttlmInd,omitempty"`
	SctiesRTGS   SecuritiesRTGS4Choice               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 SctiesRTGS,omitempty"`
	HldInd       HoldIndicator6                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 HldInd,omitempty"`
	MtchgDnl     MatchingDenied3Choice               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 MtchgDnl,omitempty"`
	UnltrlSplt   UnilateralSplit3Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 UnltrlSplt,omitempty"`
	Lnkgs        []Linkages62                        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Lnkgs,omitempty"`
}

type RestrictionIdentification1 struct {
	Cd RestrictionReference1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Cd"`
	Id Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Id"`
}

// May be one of ADDC, ADDS, REMC, REMS
type RestrictionReference1Code string

type SecuritiesAccount19 struct {
	Id Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Id"`
	Tp GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Tp,omitempty"`
	Nm Max70Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Nm,omitempty"`
}

type SecuritiesRTGS4Choice struct {
	Ind   bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Ind,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Prtry,omitempty"`
}

type SecuritiesSettlementConditionsModificationRequestV09 struct {
	AcctOwnr           PartyIdentification144    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 AcctOwnr,omitempty"`
	SfkpgAcct          SecuritiesAccount19       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 SfkpgAcct,omitempty"`
	BlckChainAdrOrWllt BlockChainAddressWallet3  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 BlckChainAdrOrWllt,omitempty"`
	ReqDtls            []RequestDetails27        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 ReqDtls"`
	AddtlInf           []AdditionalInformation26 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 AddtlInf,omitempty"`
	SplmtryData        []SupplementaryData1      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 SplmtryData,omitempty"`
}

// May be one of TRAD
type SecuritiesTransactionType5Code string

type SecurityIdentification19 struct {
	ISIN   ISINOct2015Identifier  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 ISIN,omitempty"`
	OthrId []OtherIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 OthrId,omitempty"`
	Desc   Max140Text             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Desc,omitempty"`
}

// May be one of PART, NPAR, PARC, PARQ
type SettlementTransactionCondition5Code string

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type UnilateralSplit3Choice struct {
	Cd    SecuritiesTransactionType5Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Cd,omitempty"`
	Prtry GenericIdentification30        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.030.001.09 Prtry,omitempty"`
}

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
