// Code generated by z. DO NOT EDIT.

package semt_020_001_07

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type AnyBICDec2014Identifier string

type BlockChainAddressWallet3 struct {
	Id Max140Text              `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 Id"`
	Tp GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 Tp,omitempty"`
	Nm Max70Text               `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 Nm,omitempty"`
}

// May be one of FREE, APMT
type DeliveryReceiptType2Code string

type Document struct {
	SctiesMsgCxlAdvc SecuritiesMessageCancellationAdviceV07 `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SctiesMsgCxlAdvc"`
}

// Must match the pattern [a-zA-Z0-9]{4}
type Exact4AlphaNumericText string

type GenericIdentification30 struct {
	Id      Exact4AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 Id"`
	Issr    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 Issr"`
	SchmeNm Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SchmeNm,omitempty"`
}

type GenericIdentification36 struct {
	Id      Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 Id"`
	Issr    Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 Issr"`
	SchmeNm Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SchmeNm,omitempty"`
}

// Must match the pattern [A-Z0-9]{18,18}[0-9]{2,2}
type LEIIdentifier string

// May be no more than 140 items long
type Max140Text string

// May be no more than 350 items long
type Max350Text string

// May be no more than 35 items long
type Max35Text string

// May be no more than 70 items long
type Max70Text string

type PartyIdentification127Choice struct {
	AnyBIC  AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 AnyBIC,omitempty"`
	PrtryId GenericIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 PrtryId,omitempty"`
}

type PartyIdentification144 struct {
	Id  PartyIdentification127Choice `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 Id"`
	LEI LEIIdentifier                `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 LEI,omitempty"`
}

// May be one of DELI, RECE
type ReceiveDelivery1Code string

type References69Choice struct {
	SctiesSttlmTxConfId           SettlementTypeAndIdentification18 `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SctiesSttlmTxConfId,omitempty"`
	IntraPosMvmntConfId           Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 IntraPosMvmntConfId,omitempty"`
	SctiesBalAcctgRptId           Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SctiesBalAcctgRptId,omitempty"`
	SctiesBalCtdyRptId            Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SctiesBalCtdyRptId,omitempty"`
	IntraPosMvmntPstngRptId       Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 IntraPosMvmntPstngRptId,omitempty"`
	SctiesFincgConfId             SettlementTypeAndIdentification18 `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SctiesFincgConfId,omitempty"`
	SctiesTxPdgRptId              Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SctiesTxPdgRptId,omitempty"`
	SctiesTxPstngRptId            Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SctiesTxPstngRptId,omitempty"`
	SctiesSttlmTxAllgmtRptId      Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SctiesSttlmTxAllgmtRptId,omitempty"`
	SctiesSttlmTxAllgmtNtfctnTxId SettlementTypeAndIdentification18 `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SctiesSttlmTxAllgmtNtfctnTxId,omitempty"`
	PrtflTrfNtfctnId              Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 PrtflTrfNtfctnId,omitempty"`
	SctiesSttlmTxGnrtnNtfctnId    SettlementTypeAndIdentification18 `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SctiesSttlmTxGnrtnNtfctnId,omitempty"`
	OthrMsgId                     Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 OthrMsgId,omitempty"`
	TtlPrtflValtnRptId            Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 TtlPrtflValtnRptId,omitempty"`
	TrptyCollTxInstrPrcgStsAdvcId Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 TrptyCollTxInstrPrcgStsAdvcId,omitempty"`
	TrptyCollStsAdvcId            Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 TrptyCollStsAdvcId,omitempty"`
	TrptyCollAndXpsrRptId         Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 TrptyCollAndXpsrRptId,omitempty"`
}

type SecuritiesAccount19 struct {
	Id Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 Id"`
	Tp GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 Tp,omitempty"`
	Nm Max70Text               `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 Nm,omitempty"`
}

type SecuritiesMessageCancellationAdviceV07 struct {
	Ref                References69Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 Ref"`
	AcctOwnr           PartyIdentification144   `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 AcctOwnr,omitempty"`
	SfkpgAcct          SecuritiesAccount19      `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SfkpgAcct,omitempty"`
	BlckChainAdrOrWllt BlockChainAddressWallet3 `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 BlckChainAdrOrWllt,omitempty"`
	SplmtryData        []SupplementaryData1     `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SplmtryData,omitempty"`
}

type SettlementTypeAndIdentification18 struct {
	TxId          Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 TxId"`
	SctiesMvmntTp ReceiveDelivery1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 SctiesMvmntTp"`
	Pmt           DeliveryReceiptType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 Pmt"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:semt.020.001.07 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}
