// Code generated by z. DO NOT EDIT.

package catm_002_001_12

import (
	"bytes"
	"encoding/base64"
	"encoding/xml"
	"time"
)

type Acquirer10 struct {
	Id         GenericIdentification177 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id,omitempty"`
	ParamsVrsn Max256Text               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ParamsVrsn,omitempty"`
}

type ActionMessage11 struct {
	MsgDstn      UserInterface4Code       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MsgDstn"`
	InfQlfr      InformationQualify1Code  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 InfQlfr,omitempty"`
	Frmt         OutputFormat3Code        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Frmt,omitempty"`
	MsgCntt      Max20000Text             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MsgCntt,omitempty"`
	MsgCnttSgntr ContentInformationType38 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MsgCnttSgntr,omitempty"`
	OutptBrcd    OutputBarcode2           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 OutptBrcd,omitempty"`
	RspnReqrdFlg bool                     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RspnReqrdFlg,omitempty"`
	MinDispTm    float64                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MinDispTm,omitempty"`
}

// Must match the pattern [A-Z]{3,3}
type ActiveCurrencyCode string

// May be one of ADDR, PBOX, HOME, BIZZ, MLTO, DLVY
type AddressType2Code string

type AddressVerification1 struct {
	AdrDgts    Max5NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AdrDgts,omitempty"`
	PstlCdDgts Max5NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PstlCdDgts,omitempty"`
}

// May be one of HS25, HS38, HS51, HS01, SH31, SH32, SH33, SH35, SHK1, SHK2, SMS3
type Algorithm26Code string

// May be one of MACC, MCCS, CMA1, MCC1, CMA9, CMA5, CMA2, CM31, CM32, CM33, MCS3, CCA1, CCA2, CCA3, S34C, S34R
type Algorithm27Code string

// May be one of EA2C, E3DC, DKP9, UKPT, UKA2, EA9C, EA5C, DA12, DA19, DA25, N108, EA5R, EA9R, EA2R, E3DR, E36C, E36R, SD5C, UKA1, UKA3, SM4C, SM4R
type Algorithm28Code string

// May be one of ERS2, ERS1, RPSS, ERS3, ED32, ED33, ED35, ED23, ED25, ES22, ES32, ES33, ES35, ES23, ES25, ED22, EF32, EF22, EF33, EF35, EF23, EO33, EF25, EO32, EO22, EO35, EO23, EO25, DD22, DD32, DD33, DD35, DD23, DD25, SM22, SM33, SM32, SM35, SM23, SM25, S2S3
type Algorithm29Code string

// May be one of ERSA, RSAO
type Algorithm7Code string

// May be one of MGF1
type Algorithm8Code string

type AlgorithmIdentification31 struct {
	Algo  Algorithm27Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Algo"`
	Param Parameter7      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Param,omitempty"`
}

type AlgorithmIdentification32 struct {
	Algo  Algorithm28Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Algo"`
	Param Parameter12     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Param,omitempty"`
}

type AlgorithmIdentification33 struct {
	Algo  Algorithm29Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Algo"`
	Param Parameter16     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Param,omitempty"`
}

type AlgorithmIdentification34 struct {
	Algo  Algorithm8Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Algo"`
	Param Parameter18    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Param,omitempty"`
}

type AlgorithmIdentification35 struct {
	Algo  Algorithm7Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Algo"`
	Param Parameter17    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Param,omitempty"`
}

type AlgorithmIdentification36 struct {
	Algo Algorithm26Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Algo"`
}

// May be one of MONE, POIN
type AmountUnit1Code string

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type AnyBICDec2014Identifier string

// May be one of ATTD, SATT, UATT
type AttendanceContext1Code string

// May be one of CNAT, LATT, OATT, OUAT, CATT
type AttributeType1Code string

type AuthenticatedData10 struct {
	Vrsn        float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Vrsn,omitempty"`
	Rcpt        []Recipient15Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Rcpt"`
	MACAlgo     AlgorithmIdentification31 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MACAlgo"`
	NcpsltdCntt EncapsulatedContent3      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NcpsltdCntt"`
	MAC         Max140Binary              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MAC"`
}

// May be one of ICCD, AGNT, MERC, ACQR, ISSR, TRML
type AuthenticationEntity2Code string

// May be one of NPIN, PPSG, PSWD, SCRT, SCNL, SNCT, CPSG, ADDB, BIOM, CDHI, CRYP, CSCV, PSVE, CSEC, ADDS, MANU, FPIN, TOKP
type AuthenticationMethod6Code string

// May be one of TOKA, ADDB, BYPS, BIOM, CDHI, CRYP, CSCV, MANU, MERC, MOBL, FPIN, NPIN, OTHR, PPSG, PSVE, PSWD, TOKP, SCRT, SCNL, CSEC, SNCT, ADDS, CPSG, TOKN, UKNW
type AuthenticationMethod8Code string

// May be one of DENY, MRCH, CARD, AUTH, CRPT, UCRP
type AuthenticationResult1Code string

// Must match the pattern [a-zA-Z0-9]{1,30}
type BBANIdentifier string

// May be one of COQR, C128, C025, C039, EA13, EAN8, P417, UPCA
type BarcodeType1Code string

// May be one of AIBD, PPAY, TKNF, EOPT, TOPT
type BusinessArea2Code string

// May be one of LNGT, NUL8, NULG, NULL, RAND
type BytePadding1Code string

// May be one of TAGC, PHYS, BRCD, MGST, CICC, DFLE, CTLS, ECTL, CDFL
type CardDataReading5Code string

// May be one of TAGC, PHYS, BRCD, MGST, CICC, DFLE, CTLS, ECTL, CDFL, SICC, UNKW, QRCD, OPTC
type CardDataReading8Code string

type CardDirectDebit2 struct {
	DbtrId      Debtor4                     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DbtrId,omitempty"`
	CdtrId      Creditor4                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CdtrId"`
	MndtRltdInf MandateRelatedInformation13 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MndtRltdInf"`
}

// May be one of FFLB, SFLB, NFLB
type CardFallback1Code string

// May be one of ACCT, BARC, ISO2, PHON, CPAN, PRIV, UUID
type CardIdentificationType1Code string

type CardPaymentContext30 struct {
	PmtCntxt     PaymentContext29 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PmtCntxt,omitempty"`
	SaleCntxt    SaleContext4     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SaleCntxt,omitempty"`
	DrctDbtCntxt CardDirectDebit2 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DrctDbtCntxt,omitempty"`
}

type CardPaymentEnvironment80 struct {
	Acqrr             Acquirer10               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Acqrr,omitempty"`
	SvcPrvdr          Acquirer10               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SvcPrvdr,omitempty"`
	Mrchnt            Organisation41           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Mrchnt,omitempty"`
	POI               PointOfInteraction14     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 POI,omitempty"`
	Card              PaymentCard35            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Card,omitempty"`
	Chck              Check1                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Chck,omitempty"`
	StordValAcct      []StoredValueAccount2    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 StordValAcct,omitempty"`
	LltyAcct          []LoyaltyAccount3        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 LltyAcct,omitempty"`
	CstmrDvc          CustomerDevice3          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CstmrDvc,omitempty"`
	Wllt              CustomerDevice3          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Wllt,omitempty"`
	PmtTkn            Token1                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PmtTkn,omitempty"`
	MrchntTkn         MerchantToken2           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MrchntTkn,omitempty"`
	Crdhldr           Cardholder21             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Crdhldr,omitempty"`
	PrtctdCrdhldrData ContentInformationType40 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrtctdCrdhldrData,omitempty"`
	SaleEnvt          RetailerSaleEnvironment2 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SaleEnvt,omitempty"`
}

// May be one of COMM, CONS
type CardProductType1Code string

type Cardholder21 struct {
	Id           PersonIdentification15           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id,omitempty"`
	Nm           Max45Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Nm,omitempty"`
	Lang         string                           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Lang,omitempty"`
	BllgAdr      PostalAddress22                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 BllgAdr,omitempty"`
	ShppgAdr     PostalAddress22                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ShppgAdr,omitempty"`
	TripNb       Max35Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TripNb,omitempty"`
	Vhcl         Vehicle1                         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Vhcl,omitempty"`
	Authntcn     []CardholderAuthentication17     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Authntcn,omitempty"`
	TxVrfctnRslt []TransactionVerificationResult4 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TxVrfctnRslt,omitempty"`
	PrsnlData    Max70Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrsnlData,omitempty"`
	MobData      []MobileData6                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MobData,omitempty"`
}

type CardholderAuthentication17 struct {
	AuthntcnMtd       AuthenticationMethod8Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AuthntcnMtd,omitempty"`
	AuthntcnXmptn     Exemption1Code            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AuthntcnXmptn,omitempty"`
	AuthntcnVal       Max5000Binary             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AuthntcnVal,omitempty"`
	PrtctdAuthntcnVal ContentInformationType40  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrtctdAuthntcnVal,omitempty"`
	CrdhldrOnLinePIN  OnLinePIN11               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CrdhldrOnLinePIN,omitempty"`
	CrdhldrId         PersonIdentification15    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CrdhldrId,omitempty"`
	AdrVrfctn         AddressVerification1      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AdrVrfctn,omitempty"`
	AuthntcnTp        Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AuthntcnTp,omitempty"`
	AuthntcnLvl       Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AuthntcnLvl,omitempty"`
	AuthntcnRslt      AuthenticationResult1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AuthntcnRslt,omitempty"`
	AuthntcnAddtlInf  ExternallyDefinedData5    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AuthntcnAddtlInf,omitempty"`
}

// May be one of APKI, CHDT, MNSG, MNVR, FBIG, FBIO, FDSG, FCPN, FEPN, NPIN, PKIS, SCEC, NBIO, NOVF, OTHR
type CardholderVerificationCapability4Code string

type CashAccountIdentification7Choice struct {
	IBAN     IBAN2007Identifier               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 IBAN,omitempty"`
	BBAN     BBANIdentifier                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 BBAN,omitempty"`
	UPIC     UPICIdentifier                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 UPIC,omitempty"`
	DmstAcct SimpleIdentificationInformation4 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DmstAcct,omitempty"`
}

type CertificateIssuer1 struct {
	RltvDstngshdNm []RelativeDistinguishedName1 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RltvDstngshdNm"`
}

type Check1 struct {
	BkId          Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 BkId,omitempty"`
	AcctNb        Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AcctNb,omitempty"`
	ChckNb        Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ChckNb,omitempty"`
	ChckCardNb    Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ChckCardNb,omitempty"`
	ChckTrckData2 TrackData2     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ChckTrckData2,omitempty"`
	ChckTp        CheckType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ChckTp,omitempty"`
	Ctry          Max3Text       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Ctry,omitempty"`
}

// May be one of BANK, BUSI, GOVC, PAYR, PERS
type CheckType1Code string

type CommunicationAddress9 struct {
	PstlAdr      PostalAddress22 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PstlAdr,omitempty"`
	Email        Max256Text      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Email,omitempty"`
	URLAdr       Max256Text      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 URLAdr,omitempty"`
	Phne         PhoneNumber     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Phne,omitempty"`
	CstmrSvc     PhoneNumber     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CstmrSvc,omitempty"`
	AddtlCtctInf Max256Text      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AddtlCtctInf,omitempty"`
}

type CommunicationCharacteristics5 struct {
	ComTp      POICommunicationType2Code   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ComTp"`
	RmotPty    []PartyType7Code            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RmotPty"`
	Actv       bool                        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Actv"`
	Params     NetworkParameters7          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Params,omitempty"`
	PhysIntrfc PhysicalInterfaceParameter1 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PhysIntrfc,omitempty"`
}

type ContentInformationType38 struct {
	CnttTp       ContentType2Code    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CnttTp"`
	AuthntcdData AuthenticatedData10 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AuthntcdData,omitempty"`
	SgndData     SignedData9         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SgndData,omitempty"`
}

type ContentInformationType39 struct {
	CnttTp       ContentType2Code    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CnttTp"`
	EnvlpdData   EnvelopedData11     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 EnvlpdData,omitempty"`
	AuthntcdData AuthenticatedData10 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AuthntcdData,omitempty"`
	SgndData     SignedData9         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SgndData,omitempty"`
	DgstdData    DigestedData6       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DgstdData,omitempty"`
}

type ContentInformationType40 struct {
	CnttTp     ContentType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CnttTp"`
	EnvlpdData EnvelopedData11  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 EnvlpdData"`
}

// May be one of DATA, SIGN, EVLP, DGST, AUTH
type ContentType2Code string

// Must match the pattern [A-Z]{2,2}
type CountryCode string

type Creditor4 struct {
	Cdtr   PartyIdentification178Choice `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Cdtr"`
	RegnId Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RegnId,omitempty"`
}

type CryptographicKey18 struct {
	Id                        Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id"`
	AddtlId                   Max35Binary                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AddtlId,omitempty"`
	Nm                        Max256Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Nm,omitempty"`
	SctyPrfl                  Max35Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SctyPrfl,omitempty"`
	ItmNb                     Max35Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ItmNb,omitempty"`
	Vrsn                      Max256Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Vrsn"`
	Tp                        CryptographicKeyType3Code  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tp,omitempty"`
	Fctn                      []KeyUsage1Code            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Fctn,omitempty"`
	ActvtnDt                  ISODateTime                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ActvtnDt,omitempty"`
	DeactvtnDt                ISODateTime                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DeactvtnDt,omitempty"`
	KeyVal                    ContentInformationType39   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 KeyVal,omitempty"`
	CmpntWthAuthrsdAccs       []GenericIdentification186 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CmpntWthAuthrsdAccs,omitempty"`
	PrtctdCmpntWthAuthrsdAccs []ContentInformationType39 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrtctdCmpntWthAuthrsdAccs,omitempty"`
	KeyChckVal                Max35Binary                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 KeyChckVal,omitempty"`
	AddtlMgmtInf              []GenericInformation1      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AddtlMgmtInf,omitempty"`
}

// May be one of AES2, EDE3, DKP9, AES9, AES5, EDE4
type CryptographicKeyType3Code string

type CustomerDevice3 struct {
	Id    Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id,omitempty"`
	Tp    Max70Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tp,omitempty"`
	Prvdr Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Prvdr,omitempty"`
}

// May be one of AQPR, APPR, TXCP, AKCP, DLGT, MGTP, MRPR, SCPR, SWPK, STRP, TRPR, VDPR, PARA, TMSP, CRTF, LOGF, CMRQ, MDFL, CONF, RPFL, SAPR, SPRP
type DataSetCategory18Code string

type DataSetIdentification10 struct {
	Nm      Max256Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Nm,omitempty"`
	Tp      DataSetCategory18Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tp"`
	Vrsn    Max256Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Vrsn,omitempty"`
	CreDtTm ISODateTime           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CreDtTm,omitempty"`
}

type DateAndPlaceOfBirth1 struct {
	BirthDt     ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 BirthDt"`
	PrvcOfBirth Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrvcOfBirth,omitempty"`
	CityOfBirth Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CityOfBirth"`
	CtryOfBirth CountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CtryOfBirth"`
}

type Debtor4 struct {
	Dbtr   PartyIdentification178Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Dbtr,omitempty"`
	AcctId CashAccountIdentification7Choice `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AcctId,omitempty"`
}

type DeviceDisplayRequest6 struct {
	DispOutpt []ActionMessage11 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DispOutpt"`
}

type DeviceInitialisationCardReaderRequest6 struct {
	WarmRstFlg  bool                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 WarmRstFlg,omitempty"`
	ForceNtryMd []CardDataReading8Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ForceNtryMd,omitempty"`
	LeavCardFlg bool                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 LeavCardFlg,omitempty"`
	MaxWtgTm    float64                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MaxWtgTm,omitempty"`
	DispOutpt   ActionMessage11        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DispOutpt,omitempty"`
}

type DeviceInputNotification6 struct {
	XchgId    Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 XchgId"`
	OutptCntt ActionMessage11 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 OutptCntt"`
}

type DeviceInputRequest6 struct {
	DispOutpt ActionMessage11 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DispOutpt,omitempty"`
	InptData  InputData6      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 InptData"`
}

type DevicePlayResourceRequest1 struct {
	RspnMd    ResponseMode2Code       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RspnMd,omitempty"`
	RsrcActn  ResourceAction1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RsrcActn"`
	SoundVol  float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SoundVol,omitempty"`
	DispRsltn Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DispRsltn,omitempty"`
	Rsrc      ResourceContent1        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Rsrc,omitempty"`
	TmgSlot   ProcessingPosition2Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TmgSlot,omitempty"`
}

type DevicePoweroffCardReaderRequest6 struct {
	PwrOffMaxWtgTm float64         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PwrOffMaxWtgTm,omitempty"`
	DispOutpt      ActionMessage11 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DispOutpt,omitempty"`
}

type DevicePrintRequest6 struct {
	DocQlfr       DocumentType7Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DocQlfr"`
	RspnMd        ResponseMode2Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RspnMd"`
	IntgrtdPrtFlg bool              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 IntgrtdPrtFlg,omitempty"`
	ReqrdSgntrFlg bool              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ReqrdSgntrFlg,omitempty"`
	OutptCntt     ActionMessage11   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 OutptCntt"`
}

type DeviceRequest7 struct {
	Envt               CardPaymentEnvironment80                                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Envt,omitempty"`
	Cntxt              CardPaymentContext30                                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Cntxt,omitempty"`
	SvcCntt            RetailerService8Code                                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SvcCntt"`
	DispReq            DeviceDisplayRequest6                                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DispReq,omitempty"`
	InptReq            DeviceInputRequest6                                     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 InptReq,omitempty"`
	PrtReq             DevicePrintRequest6                                     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrtReq,omitempty"`
	PlayRsrcReq        DevicePlayResourceRequest1                              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PlayRsrcReq,omitempty"`
	ScrInptReq         DeviceSecureInputRequest6                               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ScrInptReq,omitempty"`
	InitlstnCardRdrReq DeviceInitialisationCardReaderRequest6                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 InitlstnCardRdrReq,omitempty"`
	CardRdrAPDUReq     DeviceSendApplicationProtocolDataUnitCardReaderRequest1 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CardRdrAPDUReq,omitempty"`
	PwrOffCardRdrReq   DevicePoweroffCardReaderRequest6                        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PwrOffCardRdrReq,omitempty"`
	TrnsmssnReq        DeviceTransmitMessageRequest2                           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TrnsmssnReq,omitempty"`
	InptNtfctn         DeviceInputNotification6                                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 InptNtfctn,omitempty"`
	SplmtryData        []SupplementaryData1                                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SplmtryData,omitempty"`
}

type DeviceSecureInputRequest6 struct {
	PINReqTp     PINRequestType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PINReqTp"`
	PINVrfctnMtd Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PINVrfctnMtd,omitempty"`
	MaxWtgTm     float64             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MaxWtgTm,omitempty"`
	BeepKeyFlg   bool                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 BeepKeyFlg,omitempty"`
	CrdhldrPIN   OnLinePIN11         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CrdhldrPIN,omitempty"`
}

type DeviceSendApplicationProtocolDataUnitCardReaderRequest1 struct {
	Clss       Min1Max256Binary `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Clss"`
	Instr      Min1Max256Binary `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Instr"`
	Param1     Min1Max256Binary `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Param1"`
	Param2     Min1Max256Binary `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Param2"`
	Data       Min1Max256Binary `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Data,omitempty"`
	XpctdLngth Min1Max256Binary `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 XpctdLngth,omitempty"`
}

type DeviceTransmitMessageRequest2 struct {
	DstnAdr       NetworkParameters7 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DstnAdr"`
	MaxTrnsmssnTm float64            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MaxTrnsmssnTm"`
	MaxWtgTm      float64            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MaxWtgTm,omitempty"`
	MsgToSnd      Max100KBinary      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MsgToSnd"`
}

type DigestedData6 struct {
	Vrsn        float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Vrsn,omitempty"`
	DgstAlgo    AlgorithmIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DgstAlgo"`
	NcpsltdCntt EncapsulatedContent3      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NcpsltdCntt"`
	Dgst        Max140Binary              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Dgst"`
}

type DisplayCapabilities4 struct {
	Dstn      []UserInterface4Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Dstn"`
	AvlblFrmt []OutputFormat1Code  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AvlblFrmt,omitempty"`
	NbOfLines float64              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NbOfLines,omitempty"`
	LineWidth float64              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 LineWidth,omitempty"`
	AvlblLang []string             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AvlblLang,omitempty"`
}

type Document struct {
	MgmtPlanRplcmnt ManagementPlanReplacementV12 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MgmtPlanRplcmnt"`
}

// May be one of JNRL, CRCP, HRCP, SRCP, RPIN, VCHR
type DocumentType7Code string

type EncapsulatedContent3 struct {
	CnttTp ContentType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CnttTp"`
	Cntt   Max100KBinary    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Cntt,omitempty"`
}

type EncryptedContent7 struct {
	CnttTp         ContentType2Code          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CnttTp"`
	CnttNcrptnAlgo AlgorithmIdentification32 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CnttNcrptnAlgo,omitempty"`
	NcrptdData     Max100KBinary             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NcrptdData"`
}

// May be one of TR31, TR34, I238
type EncryptionFormat2Code string

type EnvelopedData11 struct {
	Vrsn       float64                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Vrsn,omitempty"`
	OrgtrInf   OriginatorInformation1 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 OrgtrInf,omitempty"`
	Rcpt       []Recipient15Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Rcpt"`
	NcrptdCntt EncryptedContent7      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NcrptdCntt,omitempty"`
}

type ErrorAction5 struct {
	ActnRslt  []TerminalManagementActionResult5Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ActnRslt"`
	ActnToPrc TerminalManagementErrorAction2Code    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ActnToPrc"`
}

// Must match the pattern [a-zA-Z0-9]{3}
type Exact3AlphaNumericText string

// Must match the pattern [0-9]{3}
type Exact3NumericText string

// Must match the pattern [0-9]{4}
type Exact4NumericText string

// May be one of LOWA, MINT, RECP, SCPE, SCAD, TRAE, PKGE, TMBE
type Exemption1Code string

type ExternallyDefinedData5 struct {
	Id        Max1025Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id"`
	Val       Max100KBinary            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Val,omitempty"`
	PrtctdVal ContentInformationType39 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrtctdVal,omitempty"`
	Tp        Max1025Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tp,omitempty"`
}

type GenericIdentification176 struct {
	Id     Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id"`
	Tp     PartyType33Code   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tp,omitempty"`
	Issr   PartyType33Code   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Issr,omitempty"`
	Ctry   Min2Max3AlphaText `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Ctry,omitempty"`
	ShrtNm Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ShrtNm,omitempty"`
}

type GenericIdentification177 struct {
	Id       Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id"`
	Tp       PartyType33Code    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tp,omitempty"`
	Issr     PartyType33Code    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Issr,omitempty"`
	Ctry     Min2Max3AlphaText  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Ctry,omitempty"`
	ShrtNm   Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ShrtNm,omitempty"`
	RmotAccs NetworkParameters7 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RmotAccs,omitempty"`
	Glctn    Geolocation1       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Glctn,omitempty"`
}

type GenericIdentification186 struct {
	Id Max256Text     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id"`
	Tp PartyType7Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tp"`
}

type GenericIdentification32 struct {
	Id     Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id"`
	Tp     PartyType3Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tp,omitempty"`
	Issr   PartyType4Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Issr,omitempty"`
	ShrtNm Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ShrtNm,omitempty"`
}

type GenericIdentification36 struct {
	Id      Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id"`
	Issr    Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Issr"`
	SchmeNm Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SchmeNm,omitempty"`
}

type GenericIdentification4 struct {
	Id   Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id"`
	IdTp Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 IdTp"`
}

type GenericIdentification48 struct {
	Id   Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id"`
	Vrsn Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Vrsn"`
	Issr Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Issr"`
}

type GenericInformation1 struct {
	Nm  Max70Text  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Nm"`
	Val Max140Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Val,omitempty"`
}

type Geolocation1 struct {
	GeogcCordints GeolocationGeographicCoordinates1 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 GeogcCordints,omitempty"`
	UTMCordints   GeolocationUTMCoordinates1        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 UTMCordints,omitempty"`
}

type GeolocationGeographicCoordinates1 struct {
	Lat  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Lat"`
	Long Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Long"`
}

type GeolocationUTMCoordinates1 struct {
	UTMZone    Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 UTMZone"`
	UTMEstwrd  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 UTMEstwrd"`
	UTMNrthwrd Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 UTMNrthwrd"`
}

// Must match the pattern [A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}
type IBAN2007Identifier string

// Must match the pattern [0-9]{3,3}
type ISO3NumericCountryCode string

type ISODate time.Time

func (t *ISODate) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t ISODate) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type ISODateTime time.Time

func (t *ISODateTime) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t ISODateTime) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

// May be one of CUSA, DISP, DOCT, ERRO, INPT, POIR, RCPT, SOND, STAT, VCHR
type InformationQualify1Code string

// May be one of DCSG, DGSG, GAKY, GCNF, GFKY, GMNE, PSWD, SITE, TXSG, HTML, SIGN
type InputCommand1Code string

type InputData6 struct {
	DvcTp           SaleCapabilities2Code   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DvcTp"`
	InfQlfr         InformationQualify1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 InfQlfr"`
	InptCmd         InputCommand1Code       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 InptCmd"`
	NtfyCardInptFlg bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NtfyCardInptFlg"`
	MaxInptTm       float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MaxInptTm,omitempty"`
	InptTxt         ActionMessage11         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 InptTxt,omitempty"`
	ImdtRspnFlg     bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ImdtRspnFlg,omitempty"`
	WaitUsrVldtnFlg bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 WaitUsrVldtnFlg,omitempty"`
	BeepKeyFlg      bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 BeepKeyFlg,omitempty"`
	GblCrrctnFlg    bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 GblCrrctnFlg,omitempty"`
	DsblCclFlg      bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DsblCclFlg,omitempty"`
	DsblCrrctFlg    bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DsblCrrctFlg,omitempty"`
	DsblVldFlg      bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DsblVldFlg,omitempty"`
	MenuBckFlg      bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MenuBckFlg,omitempty"`
}

type IssuerAndSerialNumber2 struct {
	Issr  CertificateIssuer1 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Issr"`
	SrlNb Max500Binary       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SrlNb"`
}

type KEK9 struct {
	Vrsn          float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Vrsn,omitempty"`
	KEKId         KEKIdentifier7            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 KEKId"`
	KeyNcrptnAlgo AlgorithmIdentification32 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 KeyNcrptnAlgo"`
	NcrptdKey     Max500Binary              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NcrptdKey,omitempty"`
}

type KEKIdentifier5 struct {
	KeyId     Max140Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 KeyId"`
	KeyVrsn   Max140Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 KeyVrsn"`
	SeqNb     float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SeqNb,omitempty"`
	DerivtnId Min5Max16Binary           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DerivtnId,omitempty"`
	Tp        CryptographicKeyType3Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tp,omitempty"`
	Fctn      []KeyUsage1Code           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Fctn,omitempty"`
}

type KEKIdentifier7 struct {
	KeyId     Max140Text   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 KeyId"`
	KeyVrsn   Max140Text   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 KeyVrsn"`
	SeqNb     float64      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SeqNb,omitempty"`
	DerivtnId Max500Binary `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DerivtnId,omitempty"`
}

type KeyTransport10 struct {
	Vrsn          float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Vrsn,omitempty"`
	RcptId        Recipient13Choice         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RcptId"`
	KeyNcrptnAlgo AlgorithmIdentification35 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 KeyNcrptnAlgo"`
	NcrptdKey     Max5000Binary             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NcrptdKey"`
}

// May be one of ENCR, DCPT, DENC, DDEC, TRNI, TRNX, MACG, MACV, SIGG, SUGV, PINE, PIND, PINV, KEYG, KEYI, KEYX, KEYD
type KeyUsage1Code string

// May be one of INDR, IPMP, MPOI, MPMP, MSLE, SSLE, VNDG
type LocationCategory3Code string

// May be one of ABRD, NMDC, FIXD, VIRT
type LocationCategory4Code string

type LoyaltyAccount3 struct {
	LltyId Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 LltyId"`
	NtryMd CardDataReading8Code        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NtryMd,omitempty"`
	IdTp   CardIdentificationType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 IdTp,omitempty"`
	Brnd   Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Brnd,omitempty"`
	Prvdr  Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Prvdr,omitempty"`
	OwnrNm Max45Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 OwnrNm,omitempty"`
	Unit   AmountUnit1Code             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Unit,omitempty"`
	Ccy    ActiveCurrencyCode          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Ccy,omitempty"`
	Bal    float64                     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Bal,omitempty"`
}

// May be one of ALLO, DENY, PRCS, PROP, REQU
type LoyaltyHandling1Code string

type ManagementPlan12 struct {
	POIId       GenericIdentification176    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 POIId,omitempty"`
	TermnlMgrId GenericIdentification176    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TermnlMgrId"`
	DataSet     TerminalManagementDataSet33 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DataSet"`
}

type ManagementPlanContent12 struct {
	TMChllng        Max140Binary   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TMChllng,omitempty"`
	KeyNcphrmntCert []Max10KBinary `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 KeyNcphrmntCert,omitempty"`
	Actn            []TMSAction12  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Actn"`
}

type ManagementPlanReplacementV12 struct {
	Hdr      TMSHeader1               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Hdr"`
	MgmtPlan ManagementPlan12         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MgmtPlan"`
	SctyTrlr ContentInformationType38 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SctyTrlr,omitempty"`
}

type MandateRelatedInformation13 struct {
	MndtId    Max35Text    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MndtId"`
	DtOfSgntr ISODate      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DtOfSgntr,omitempty"`
	MndtImg   Max2MBBinary `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MndtImg,omitempty"`
}

type Max100KBinary []byte

func (t *Max100KBinary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max100KBinary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be no more than 1025 items long
type Max1025Text string

// May be no more than 104 items long
type Max104Text string

type Max10KBinary []byte

func (t *Max10KBinary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max10KBinary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be no more than 10 items long
type Max10Text string

// Must match the pattern [0-9]{1,11}
type Max11NumericText string

type Max140Binary []byte

func (t *Max140Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max140Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be no more than 140 items long
type Max140Text string

// Must match the pattern [0-9]{1,15}
type Max15NumericText string

// May be no more than 16 items long
type Max16Text string

// Must match the pattern [0-9]{1,19}
type Max19NumericText string

// May be no more than 20000 items long
type Max20000Text string

// May be no more than 256 items long
type Max256Text string

type Max2KBinary []byte

func (t *Max2KBinary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max2KBinary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

type Max2MBBinary []byte

func (t *Max2MBBinary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max2MBBinary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// Must match the pattern [0-9]{1,2}
type Max2NumericText string

type Max3000Binary []byte

func (t *Max3000Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max3000Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be no more than 30 items long
type Max30Text string

// May be no more than 350 items long
type Max350Text string

type Max35Binary []byte

func (t *Max35Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max35Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// Must match the pattern [0-9]{1,35}
type Max35NumericText string

// May be no more than 35 items long
type Max35Text string

// May be no more than 37 items long
type Max37Text string

// May be no more than 3 items long
type Max3Text string

// May be no more than 45 items long
type Max45Text string

type Max5000Binary []byte

func (t *Max5000Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max5000Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

type Max500Binary []byte

func (t *Max500Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max500Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be no more than 500 items long
type Max500Text string

// Must match the pattern [0-9]{1,5}
type Max5NumericText string

// May be no more than 6 items long
type Max6Text string

// May be no more than 70 items long
type Max70Text string

// May be no more than 76 items long
type Max76Text string

// May be no more than 8000 items long
type Max8000Text string

// Must match the pattern [0-9]{1,9}
type Max9NumericText string

type MemoryCharacteristics1 struct {
	Id     Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id"`
	TtlSz  float64         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TtlSz"`
	FreeSz float64         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 FreeSz"`
	Unit   MemoryUnit1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Unit"`
}

// May be one of BYTE, EXAB, GIGA, KILO, MEGA, PETA, TERA
type MemoryUnit1Code string

type MerchantToken2 struct {
	Tkn           Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tkn,omitempty"`
	TknXpryDt     Max10Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TknXpryDt,omitempty"`
	TknChrtc      []Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TknChrtc,omitempty"`
	TknRqstr      PaymentTokenIdentifiers1 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TknRqstr,omitempty"`
	TknAssrncLvl  float64                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TknAssrncLvl,omitempty"`
	TknAssrncData Max500Binary             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TknAssrncData,omitempty"`
	TknAssrncMtd  Max2NumericText          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TknAssrncMtd,omitempty"`
	TknInittdInd  bool                     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TknInittdInd,omitempty"`
}

type MessageItemCondition2 struct {
	ItmId Max140Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ItmId"`
	Cond  MessageItemCondition2Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Cond"`
	Val   []Max140Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Val,omitempty"`
}

// May be one of MNDT, CFVL, DFLT, ALWV, IFAV, COPY, UNSP, LMNV
type MessageItemCondition2Code string

type Min1Max256Binary []byte

func (t *Min1Max256Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Min1Max256Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// Must match the pattern [a-zA-Z]{2,3}
type Min2Max3AlphaText string

// Must match the pattern [0-9]{2,3}
type Min2Max3NumericText string

// May be no more than 4 items long
type Min3Max4Text string

type Min5Max16Binary []byte

func (t *Min5Max16Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Min5Max16Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// Must match the pattern [0-9]{8,28}
type Min8Max28NumericText string

type MobileData6 struct {
	MobCtryCd     Min2Max3AlphaText        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MobCtryCd,omitempty"`
	MobNtwkCd     Min2Max3NumericText      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MobNtwkCd,omitempty"`
	MobMskdMSISDN Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MobMskdMSISDN,omitempty"`
	Glctn         Geolocation1             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Glctn,omitempty"`
	SnstvMobData  SensitiveMobileData1     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SnstvMobData,omitempty"`
	PrtctdMobData ContentInformationType40 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrtctdMobData,omitempty"`
}

type NameAndAddress6 struct {
	Nm  Max70Text      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Nm"`
	Adr PostalAddress2 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Adr"`
}

type NetworkParameters7 struct {
	Adr        []NetworkParameters9 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Adr"`
	UsrNm      Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 UsrNm,omitempty"`
	AccsCd     Max35Binary          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AccsCd,omitempty"`
	SvrCert    []Max10KBinary       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SvrCert,omitempty"`
	SvrCertIdr []Max140Binary       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SvrCertIdr,omitempty"`
	ClntCert   []Max10KBinary       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ClntCert,omitempty"`
	SctyPrfl   Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SctyPrfl,omitempty"`
}

type NetworkParameters9 struct {
	NtwkTp NetworkType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NtwkTp"`
	AdrVal Max500Text       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AdrVal"`
}

// May be one of IPNW, PSTN
type NetworkType1Code string

// May be one of OFLN, ONLN, SMON
type OnLineCapability1Code string

type OnLinePIN11 struct {
	NcrptdPINBlck ContentInformationType40 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NcrptdPINBlck"`
	PINFrmt       PINFormat3Code           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PINFrmt"`
	AddtlInpt     Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AddtlInpt,omitempty"`
}

type Organisation26 struct {
	CmonNm       Max70Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CmonNm"`
	Adr          Max140Text             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Adr,omitempty"`
	CtryCd       ISO3NumericCountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CtryCd"`
	MrchntCtgyCd Min3Max4Text           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MrchntCtgyCd"`
	RegdIdr      Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RegdIdr"`
}

type Organisation41 struct {
	Id          GenericIdentification32 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id,omitempty"`
	CmonNm      Max70Text               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CmonNm,omitempty"`
	LctnCtgy    LocationCategory4Code   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 LctnCtgy,omitempty"`
	LctnAndCtct CommunicationAddress9   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 LctnAndCtct,omitempty"`
	SchmeData   Max140Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SchmeData,omitempty"`
}

type OriginatorInformation1 struct {
	Cert []Max5000Binary `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Cert,omitempty"`
}

type OutputBarcode2 struct {
	BrcdTp        BarcodeType1Code           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 BrcdTp"`
	BrcdVal       Max8000Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 BrcdVal,omitempty"`
	QRCdBinryVal  Max3000Binary              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 QRCdBinryVal,omitempty"`
	QRCdVrsn      Max16Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 QRCdVrsn,omitempty"`
	QRCdNcodgMd   QRCodeEncodingMode1Code    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 QRCdNcodgMd,omitempty"`
	QRCdErrCrrctn QRCodeErrorCorrection1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 QRCdErrCrrctn,omitempty"`
}

// May be one of MREF, TEXT, HTML
type OutputFormat1Code string

// May be one of BARC, MENT, MREF, SREF, TEXT, HTML
type OutputFormat3Code string

// May be one of ISO0, ISO1, ISO2, ISO3, ISO4, ISO5
type PINFormat3Code string

// May be one of PIAE, PIAV, PIVO
type PINRequestType1Code string

// May be one of BLTH, ETHR, GPRS, GSMF, PSTN, RS23, USBD, USBH, WIFI, WT2G, WT3G, WT4G, WT5G
type POICommunicationType2Code string

// May be one of APPL, CERT, EVAL
type POIComponentAssessment1Code string

// May be one of WAIT, OUTD, OPER, DACT
type POIComponentStatus1Code string

// May be one of AQPP, APPR, TLPR, SCPR, SERV, TERM, DVCE, SECM, APLI, EMVK, EMVO, MDWR, DRVR, OPST, MRPR, CRTF, TMSP, SACP, SAPR, LOGF, MDFL, SOFT, CONF, RPFL
type POIComponentType6Code string

type PackageType5 struct {
	PackgId     GenericIdentification176 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PackgId,omitempty"`
	PackgLngth  float64                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PackgLngth,omitempty"`
	OffsetStart float64                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 OffsetStart,omitempty"`
	OffsetEnd   float64                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 OffsetEnd,omitempty"`
	PackgBlck   []ExternallyDefinedData5 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PackgBlck,omitempty"`
}

type Parameter12 struct {
	NcrptnFrmt   EncryptionFormat2Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NcrptnFrmt,omitempty"`
	InitlstnVctr Max500Binary          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 InitlstnVctr,omitempty"`
	BPddg        BytePadding1Code      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 BPddg,omitempty"`
}

type Parameter16 struct {
	DgstAlgo     Algorithm26Code           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DgstAlgo,omitempty"`
	MskGnrtrAlgo AlgorithmIdentification34 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MskGnrtrAlgo,omitempty"`
	SaltLngth    float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SaltLngth,omitempty"`
	TrlrFld      float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TrlrFld,omitempty"`
	OIDCrvNm     Max140Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 OIDCrvNm,omitempty"`
}

type Parameter17 struct {
	NcrptnFrmt   EncryptionFormat2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NcrptnFrmt,omitempty"`
	DgstAlgo     Algorithm26Code           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DgstAlgo,omitempty"`
	MskGnrtrAlgo AlgorithmIdentification34 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MskGnrtrAlgo,omitempty"`
}

type Parameter18 struct {
	DgstAlgo Algorithm26Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DgstAlgo,omitempty"`
}

type Parameter7 struct {
	InitlstnVctr Max500Binary     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 InitlstnVctr,omitempty"`
	BPddg        BytePadding1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 BPddg,omitempty"`
}

type PartyIdentification178Choice struct {
	AnyBIC   AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AnyBIC,omitempty"`
	PrtryId  GenericIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrtryId,omitempty"`
	NmAndAdr NameAndAddress6         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NmAndAdr,omitempty"`
}

// May be one of OPOI, MERC, ACCP, ITAG, ACQR, CISS, DLIS, MTMG, TAXH, TMGT
type PartyType33Code string

// May be one of OPOI, MERC, ACCP, ITAG, ACQR, CISS, DLIS
type PartyType3Code string

// May be one of MERC, ACCP, ITAG, ACQR, CISS, TAXH
type PartyType4Code string

// May be one of ACQR, ITAG, PCPT, TMGT, SALE
type PartyType7Code string

type PaymentCard35 struct {
	PrtctdCardData ContentInformationType40 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrtctdCardData,omitempty"`
	PrvtCardData   Max100KBinary            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrvtCardData,omitempty"`
	PlainCardData  PlainCardData22          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PlainCardData,omitempty"`
	PmtAcctRef     Max70Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PmtAcctRef,omitempty"`
	MskdPAN        Max30Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MskdPAN,omitempty"`
	IssrBIN        Max15NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 IssrBIN,omitempty"`
	CardCtryCd     Max3Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CardCtryCd,omitempty"`
	CardCcyCd      Exact3AlphaNumericText   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CardCcyCd,omitempty"`
	CardPdctPrfl   Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CardPdctPrfl,omitempty"`
	CardBrnd       Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CardBrnd,omitempty"`
	CardPdctTp     CardProductType1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CardPdctTp,omitempty"`
	CardPdctSubTp  Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CardPdctSubTp,omitempty"`
	IntrnlCard     bool                     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 IntrnlCard,omitempty"`
	AllwdPdct      []Max70Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AllwdPdct,omitempty"`
	SvcOptn        Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SvcOptn,omitempty"`
	AddtlCardData  Max70Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AddtlCardData,omitempty"`
}

type PaymentContext29 struct {
	CardPres       bool                          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CardPres,omitempty"`
	CrdhldrPres    bool                          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CrdhldrPres,omitempty"`
	OnLineCntxt    bool                          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 OnLineCntxt,omitempty"`
	AttndncCntxt   AttendanceContext1Code        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AttndncCntxt,omitempty"`
	TxEnvt         TransactionEnvironment1Code   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TxEnvt,omitempty"`
	TxChanl        TransactionChannel5Code       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TxChanl,omitempty"`
	BizArea        BusinessArea2Code             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 BizArea,omitempty"`
	AttndntMsgCpbl bool                          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AttndntMsgCpbl,omitempty"`
	AttndntLang    string                        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AttndntLang,omitempty"`
	CardDataNtryMd CardDataReading8Code          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CardDataNtryMd,omitempty"`
	FllbckInd      CardFallback1Code             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 FllbckInd,omitempty"`
	SpprtdOptn     []SupportedPaymentOption2Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SpprtdOptn,omitempty"`
}

type PaymentTokenIdentifiers1 struct {
	PrvdrId Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrvdrId"`
	RqstrId Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RqstrId"`
}

type PersonIdentification15 struct {
	DrvrLicNb       Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DrvrLicNb,omitempty"`
	DrvrLicLctn     Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DrvrLicLctn,omitempty"`
	DrvrLicNm       Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DrvrLicNm,omitempty"`
	DrvrId          Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DrvrId,omitempty"`
	CstmrNb         Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CstmrNb,omitempty"`
	SclSctyNb       Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SclSctyNb,omitempty"`
	AlnRegnNb       Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AlnRegnNb,omitempty"`
	PsptNb          Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PsptNb,omitempty"`
	TaxIdNb         Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TaxIdNb,omitempty"`
	IdntyCardNb     Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 IdntyCardNb,omitempty"`
	MplyrIdNb       Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MplyrIdNb,omitempty"`
	MplyeeIdNb      Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MplyeeIdNb,omitempty"`
	JobNb           Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 JobNb,omitempty"`
	Dept            Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Dept,omitempty"`
	EmailAdr        Max256Text               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 EmailAdr,omitempty"`
	DtAndPlcOfBirth DateAndPlaceOfBirth1     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DtAndPlcOfBirth,omitempty"`
	Othr            []GenericIdentification4 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Othr,omitempty"`
}

// Must match the pattern \+[0-9]{1,3}-[0-9()+\-]{1,30}
type PhoneNumber string

type PhysicalInterfaceParameter1 struct {
	IntrfcNm    Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 IntrfcNm"`
	IntrfcTp    POICommunicationType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 IntrfcTp,omitempty"`
	UsrNm       Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 UsrNm,omitempty"`
	AccsCd      Max35Binary               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AccsCd,omitempty"`
	SctyPrfl    Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SctyPrfl,omitempty"`
	AddtlParams Max2KBinary               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AddtlParams,omitempty"`
}

type PlainCardData17 struct {
	PAN           Min8Max28NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PAN,omitempty"`
	Trck1         Max76Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Trck1,omitempty"`
	Trck2         Max37Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Trck2,omitempty"`
	Trck3         Max104Text           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Trck3,omitempty"`
	AddtlCardData []Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AddtlCardData,omitempty"`
	NtryMd        CardDataReading5Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NtryMd,omitempty"`
}

type PlainCardData22 struct {
	PAN       Min8Max28NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PAN"`
	CardSeqNb Min2Max3NumericText  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CardSeqNb,omitempty"`
	FctvDt    Max10Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 FctvDt,omitempty"`
	XpryDt    Max10Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 XpryDt,omitempty"`
	SvcCd     Exact3NumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SvcCd,omitempty"`
	Trck1     Max76Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Trck1,omitempty"`
	Trck2     Max37Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Trck2,omitempty"`
	Trck3     Max104Text           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Trck3,omitempty"`
	CrdhldrNm Max45Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CrdhldrNm,omitempty"`
}

type PointOfInteraction14 struct {
	Id           GenericIdentification177        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id"`
	SysNm        Max70Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SysNm,omitempty"`
	GrpId        Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 GrpId,omitempty"`
	Cpblties     PointOfInteractionCapabilities9 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Cpblties,omitempty"`
	TmZone       Max70Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TmZone,omitempty"`
	TermnlIntgtn LocationCategory3Code           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TermnlIntgtn,omitempty"`
	Cmpnt        []PointOfInteractionComponent15 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Cmpnt,omitempty"`
}

type PointOfInteractionCapabilities9 struct {
	CardRdngCpblties      []CardDataReading8Code                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CardRdngCpblties,omitempty"`
	CrdhldrVrfctnCpblties []CardholderVerificationCapability4Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CrdhldrVrfctnCpblties,omitempty"`
	PINLngthCpblties      float64                                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PINLngthCpblties,omitempty"`
	ApprvlCdLngth         float64                                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ApprvlCdLngth,omitempty"`
	MxScrptLngth          float64                                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MxScrptLngth,omitempty"`
	CardCaptrCpbl         bool                                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CardCaptrCpbl,omitempty"`
	OnLineCpblties        OnLineCapability1Code                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 OnLineCpblties,omitempty"`
	MsgCpblties           []DisplayCapabilities4                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MsgCpblties,omitempty"`
}

type PointOfInteractionComponent15 struct {
	Tp       POIComponentType6Code                        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tp"`
	SubTpInf Max70Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SubTpInf,omitempty"`
	Id       PointOfInteractionComponentIdentification2   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id"`
	Sts      PointOfInteractionComponentStatus3           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Sts,omitempty"`
	StdCmplc []GenericIdentification48                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 StdCmplc,omitempty"`
	Chrtcs   PointOfInteractionComponentCharacteristics10 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Chrtcs,omitempty"`
	Assmnt   []PointOfInteractionComponentAssessment1     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Assmnt,omitempty"`
	Packg    []PackageType5                               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Packg,omitempty"`
}

type PointOfInteractionComponentAssessment1 struct {
	Tp      POIComponentAssessment1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tp"`
	Assgnr  []Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Assgnr"`
	DlvryDt ISODateTime                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DlvryDt,omitempty"`
	XprtnDt ISODateTime                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 XprtnDt,omitempty"`
	Nb      Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Nb"`
}

type PointOfInteractionComponentCharacteristics10 struct {
	Mmry           []MemoryCharacteristics1        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Mmry,omitempty"`
	Com            []CommunicationCharacteristics5 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Com,omitempty"`
	SctyAccsMdls   float64                         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SctyAccsMdls,omitempty"`
	SbcbrIdntyMdls float64                         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SbcbrIdntyMdls,omitempty"`
	SctyElmt       []CryptographicKey18            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SctyElmt,omitempty"`
}

type PointOfInteractionComponentIdentification2 struct {
	ItmNb   Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ItmNb,omitempty"`
	PrvdrId Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrvdrId,omitempty"`
	Id      Max256Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id,omitempty"`
	SrlNb   Max256Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SrlNb,omitempty"`
}

type PointOfInteractionComponentStatus3 struct {
	VrsnNb Max256Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 VrsnNb,omitempty"`
	Sts    POIComponentStatus1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Sts,omitempty"`
	XpryDt ISODate                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 XpryDt,omitempty"`
}

type PostalAddress2 struct {
	StrtNm      Max70Text   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 StrtNm,omitempty"`
	PstCdId     Max16Text   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PstCdId"`
	TwnNm       Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TwnNm"`
	CtrySubDvsn Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CtrySubDvsn,omitempty"`
	Ctry        CountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Ctry"`
}

type PostalAddress22 struct {
	AdrTp       AddressType2Code  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AdrTp,omitempty"`
	Dept        Max70Text         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Dept,omitempty"`
	SubDept     Max70Text         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SubDept,omitempty"`
	AdrLine     []Max70Text       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AdrLine,omitempty"`
	StrtNm      Max70Text         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 StrtNm,omitempty"`
	BldgNb      Max16Text         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 BldgNb,omitempty"`
	PstCd       Max16Text         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PstCd,omitempty"`
	TwnNm       Max70Text         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TwnNm,omitempty"`
	CtrySubDvsn []Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CtrySubDvsn,omitempty"`
	CtryCd      Min2Max3AlphaText `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CtryCd,omitempty"`
}

type ProcessRetry3 struct {
	Dely     Max9NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Dely"`
	MaxNb    float64         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MaxNb,omitempty"`
	UnitOfTm TimeUnit1Code   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 UnitOfTm,omitempty"`
}

type ProcessTiming5 struct {
	WtgTm    Max9NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 WtgTm,omitempty"`
	StartTm  ISODateTime     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 StartTm,omitempty"`
	EndTm    ISODateTime     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 EndTm,omitempty"`
	Prd      Max9NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Prd,omitempty"`
	MaxNb    float64         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MaxNb,omitempty"`
	UnitOfTm TimeUnit1Code   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 UnitOfTm,omitempty"`
}

// May be one of AFTE, WITH, BEFO, INFO
type ProcessingPosition2Code string

// May be one of ALFA, BINA, KANJ, NUME
type QRCodeEncodingMode1Code string

// May be one of M015, Q025, H030, L007
type QRCodeErrorCorrection1Code string

type Recipient13Choice struct {
	IssrAndSrlNb IssuerAndSerialNumber2 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 IssrAndSrlNb,omitempty"`
	SbjtKeyIdr   Max140Binary           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SbjtKeyIdr,omitempty"`
}

type Recipient15Choice struct {
	KeyTrnsprt KeyTransport10 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 KeyTrnsprt,omitempty"`
	KEK        KEK9           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 KEK,omitempty"`
	KeyIdr     KEKIdentifier7 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 KeyIdr,omitempty"`
}

type RelativeDistinguishedName1 struct {
	AttrTp  AttributeType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AttrTp"`
	AttrVal Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AttrVal"`
}

// May be one of PAUS, STAS, LOOP, RESU, DVOL, STOS
type ResourceAction1Code string

type ResourceContent1 struct {
	RsrcTp   ResourceType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RsrcTp"`
	RsrcFrmt SoundFormat1Code  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RsrcFrmt,omitempty"`
	Lang     string            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Lang,omitempty"`
	RsrcRef  Max1025Text       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RsrcRef,omitempty"`
}

// May be one of TEXT, URLI
type ResourceType1Code string

// May be one of SEND, IMMD, NREQ, PEND
type ResponseMode2Code string

type RetailerSaleEnvironment2 struct {
	SaleCpblties []SaleCapabilities1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SaleCpblties,omitempty"`
	Ccy          ActiveCurrencyCode      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Ccy,omitempty"`
	MinAmtToDlvr float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MinAmtToDlvr,omitempty"`
	MaxCshBckAmt float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MaxCshBckAmt,omitempty"`
	MinSpltAmt   float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MinSpltAmt,omitempty"`
	DbtPrefrdFlg bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DbtPrefrdFlg,omitempty"`
	LltyHdlg     LoyaltyHandling1Code    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 LltyHdlg,omitempty"`
}

// May be one of DDYQ, DINQ, DPRQ, DSOQ, DSIQ, DCIQ, DCAQ, DCPQ, DCOQ, DINO
type RetailerService8Code string

// May be one of CHDI, CHER, CHIN, CHST, CUDI, CUAS, CUER, CUIN, POIR, PRDC, PRRP, PRVC
type SaleCapabilities1Code string

// May be one of CHIN, CUIN
type SaleCapabilities2Code string

type SaleContext4 struct {
	SaleId           Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SaleId,omitempty"`
	SaleRefNb        Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SaleRefNb,omitempty"`
	SaleRcncltnId    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SaleRcncltnId,omitempty"`
	CshrId           Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CshrId,omitempty"`
	CshrLang         []string               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CshrLang,omitempty"`
	ShftNb           Max2NumericText        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ShftNb,omitempty"`
	CstmrOrdrReqFlg  bool                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CstmrOrdrReqFlg,omitempty"`
	PurchsOrdrNb     Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PurchsOrdrNb,omitempty"`
	InvcNb           Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 InvcNb,omitempty"`
	DlvryNoteNb      Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DlvryNoteNb,omitempty"`
	SpnsrdMrchnt     []Organisation26       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SpnsrdMrchnt,omitempty"`
	SpltPmt          bool                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SpltPmt,omitempty"`
	RmngAmt          float64                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RmngAmt,omitempty"`
	ForceOnlnFlg     bool                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ForceOnlnFlg,omitempty"`
	ReuseCardDataFlg bool                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ReuseCardDataFlg,omitempty"`
	AllwdNtryMd      []CardDataReading8Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AllwdNtryMd,omitempty"`
	SaleTknScp       SaleTokenScope1Code    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SaleTknScp,omitempty"`
	AddtlSaleData    Max70Text              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AddtlSaleData,omitempty"`
}

// May be one of MULT, SNGL
type SaleTokenScope1Code string

type SensitiveMobileData1 struct {
	MSISDN Max35NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MSISDN"`
	IMSI   Max35NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 IMSI,omitempty"`
	IMEI   Max35NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 IMEI,omitempty"`
}

type SignedData9 struct {
	Vrsn        float64                     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Vrsn,omitempty"`
	DgstAlgo    []AlgorithmIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DgstAlgo,omitempty"`
	NcpsltdCntt EncapsulatedContent3        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NcpsltdCntt,omitempty"`
	Cert        []Max5000Binary             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Cert,omitempty"`
	Sgnr        []Signer8                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Sgnr,omitempty"`
}

type Signer8 struct {
	Vrsn        float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Vrsn,omitempty"`
	SgnrId      Recipient13Choice         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SgnrId,omitempty"`
	DgstAlgo    AlgorithmIdentification36 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DgstAlgo"`
	SgndAttrbts []GenericInformation1     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SgndAttrbts,omitempty"`
	SgntrAlgo   AlgorithmIdentification33 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SgntrAlgo"`
	Sgntr       Max3000Binary             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Sgntr"`
}

type SimpleIdentificationInformation4 struct {
	Id Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id"`
}

// May be one of MSGR, SNDR, TEXT
type SoundFormat1Code string

type StoredValueAccount2 struct {
	AcctTp StoredValueAccountType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AcctTp,omitempty"`
	IdTp   CardIdentificationType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 IdTp,omitempty"`
	Id     Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id,omitempty"`
	Brnd   Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Brnd,omitempty"`
	Prvdr  Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Prvdr,omitempty"`
	OwnrNm Max45Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 OwnrNm,omitempty"`
	XpryDt Max10Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 XpryDt,omitempty"`
	NtryMd CardDataReading8Code        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NtryMd,omitempty"`
	Ccy    ActiveCurrencyCode          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Ccy,omitempty"`
	Bal    float64                     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Bal,omitempty"`
}

// May be one of BNKA, CWVC, CPYA, ELMY, GIFT, GCER, MLVC, OLVC, MERC, OTHR, PHON, CARD, TRVL
type StoredValueAccountType1Code string

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

// May be one of PART, MSRV, INSI, PINQ
type SupportedPaymentOption2Code string

type TMSAction12 struct {
	Tp               TerminalManagementAction5Code              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tp"`
	RmotAccs         NetworkParameters7                         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RmotAccs,omitempty"`
	Key              []KEKIdentifier5                           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Key,omitempty"`
	TermnlMgrId      GenericIdentification176                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TermnlMgrId,omitempty"`
	TMSPrtcol        Max35Text                                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TMSPrtcol,omitempty"`
	TMSPrtcolVrsn    Max35Text                                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TMSPrtcolVrsn,omitempty"`
	DataSetId        DataSetIdentification10                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DataSetId,omitempty"`
	CmpntTp          []DataSetCategory18Code                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CmpntTp,omitempty"`
	DlgtnScpId       Max35Text                                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DlgtnScpId,omitempty"`
	DlgtnScpDef      Max3000Binary                              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DlgtnScpDef,omitempty"`
	DlgtnProof       Max5000Binary                              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DlgtnProof,omitempty"`
	PrtctdDlgtnProof ContentInformationType39                   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrtctdDlgtnProof,omitempty"`
	Trggr            TerminalManagementActionTrigger1Code       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Trggr"`
	AddtlPrc         []TerminalManagementAdditionalProcess1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AddtlPrc,omitempty"`
	ReTry            ProcessRetry3                              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ReTry,omitempty"`
	TmCond           ProcessTiming5                             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TmCond,omitempty"`
	TMChllng         Max140Binary                               `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TMChllng,omitempty"`
	KeyNcphrmntCert  []Max10KBinary                             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 KeyNcphrmntCert,omitempty"`
	ErrActn          []ErrorAction5                             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 ErrActn,omitempty"`
	AddtlInf         []Max3000Binary                            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AddtlInf,omitempty"`
	MsgItm           []MessageItemCondition2                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MsgItm,omitempty"`
	DvcReq           DeviceRequest7                             `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DvcReq,omitempty"`
}

type TMSHeader1 struct {
	DwnldTrf bool                     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DwnldTrf"`
	FrmtVrsn Max6Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 FrmtVrsn"`
	XchgId   float64                  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 XchgId"`
	CreDtTm  ISODateTime              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 CreDtTm"`
	InitgPty GenericIdentification176 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 InitgPty"`
	RcptPty  GenericIdentification177 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RcptPty,omitempty"`
	Tracblt  []Traceability8          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tracblt,omitempty"`
}

// May be one of DCTV, DELT, DWNL, INST, RSTR, UPLD, UPDT, BIND, RBND, UBND, ACTV, DEVR
type TerminalManagementAction5Code string

// May be one of ACCD, CNTE, FMTE, INVC, LENE, OVER, MISS, NSUP, SIGE, WARN, SYNE, TIMO, UKDT, UKRF, INDP, IDMP, DPRU, AERR, CMER, ULER, SUCC
type TerminalManagementActionResult5Code string

// May be one of DATE, HOST, MANU, SALE
type TerminalManagementActionTrigger1Code string

// May be one of MANC, RCNC, RSRT
type TerminalManagementAdditionalProcess1Code string

type TerminalManagementDataSet33 struct {
	Id      DataSetIdentification10 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Id"`
	SeqCntr Max9NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 SeqCntr,omitempty"`
	LastSeq bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 LastSeq,omitempty"`
	Cntt    ManagementPlanContent12 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Cntt,omitempty"`
}

// May be one of SDSR, STOP
type TerminalManagementErrorAction2Code string

// May be one of DAYC, HOUR, MINU, MNTH, SECO, WEEK, YEAR
type TimeUnit1Code string

type Token1 struct {
	PmtTkn        Max19NumericText  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PmtTkn,omitempty"`
	TknXpryDt     Exact4NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TknXpryDt,omitempty"`
	TknRqstrId    Max11NumericText  `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TknRqstrId,omitempty"`
	TknAssrncData Max140Text        `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TknAssrncData,omitempty"`
	TknAssrncMtd  Max2NumericText   `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TknAssrncMtd,omitempty"`
	TknInittdInd  bool              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TknInittdInd,omitempty"`
}

type Traceability8 struct {
	RlayId      GenericIdentification177 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RlayId"`
	PrtcolNm    Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrtcolNm,omitempty"`
	PrtcolVrsn  Max6Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 PrtcolVrsn,omitempty"`
	TracDtTmIn  ISODateTime              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TracDtTmIn"`
	TracDtTmOut ISODateTime              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TracDtTmOut"`
}

type TrackData2 struct {
	TrckNb   float64          `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TrckNb,omitempty"`
	TrckFrmt TrackFormat1Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TrckFrmt,omitempty"`
	TrckVal  Max140Text       `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TrckVal"`
}

// May be one of AAMV, CMC7, E13B, ISOF, JIS1, JIS2
type TrackFormat1Code string

// May be one of MAIL, TLPH, ECOM, TVPY, SECM, MOBL, MPOS
type TransactionChannel5Code string

// May be one of MERC, PRIV, PUBL
type TransactionEnvironment1Code string

type TransactionVerificationResult4 struct {
	Mtd        AuthenticationMethod6Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Mtd"`
	VrfctnNtty AuthenticationEntity2Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 VrfctnNtty,omitempty"`
	Rslt       Verification1Code         `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Rslt,omitempty"`
	AddtlRslt  Max500Text                `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AddtlRslt,omitempty"`
}

// Must match the pattern [0-9]{8,17}
type UPICIdentifier string

// May be one of CDSP, CRCP, MDSP, MRCP, CRDO
type UserInterface4Code string

type Vehicle1 struct {
	VhclNb         Max35NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 VhclNb,omitempty"`
	TrlrNb         Max35NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TrlrNb,omitempty"`
	VhclTag        Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 VhclTag,omitempty"`
	VhclTagNtryMd  CardDataReading5Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 VhclTagNtryMd,omitempty"`
	UnitNb         Max35NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 UnitNb,omitempty"`
	RplcmntCar     bool                 `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RplcmntCar,omitempty"`
	Odmtr          float64              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Odmtr,omitempty"`
	Hbmtr          float64              `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Hbmtr,omitempty"`
	TrlrHrs        Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 TrlrHrs,omitempty"`
	RefrHrs        Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 RefrHrs,omitempty"`
	MntncId        Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 MntncId,omitempty"`
	DrvrOrVhclCard PlainCardData17      `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 DrvrOrVhclCard,omitempty"`
	AddtlVhclData  []Vehicle2           `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 AddtlVhclData,omitempty"`
}

type Vehicle2 struct {
	Tp     Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Tp,omitempty"`
	NtryMd CardDataReading5Code `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 NtryMd,omitempty"`
	Data   Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:catm.002.001.12 Data"`
}

// May be one of FAIL, MISS, NOVF, PART, SUCC, ERRR
type Verification1Code string

type xsdBase64Binary []byte

func (b *xsdBase64Binary) UnmarshalText(text []byte) (err error) {
	*b, err = base64.StdEncoding.DecodeString(string(text))
	return
}
func (b xsdBase64Binary) MarshalText() ([]byte, error) {
	var buf bytes.Buffer
	enc := base64.NewEncoder(base64.StdEncoding, &buf)
	enc.Write([]byte(b))
	enc.Close()
	return buf.Bytes(), nil
}

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
