// Code generated by z. DO NOT EDIT.

package pacs_004_001_15

import (
	"bytes"
	"encoding/base64"
	"encoding/xml"
	"time"
)

type AccountIdentification4Choice struct {
	IBAN IBAN2007Identifier            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IBAN,omitempty"`
	Othr GenericAccountIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Othr,omitempty"`
}

type AccountSchemeName1Choice struct {
	Cd    ExternalAccountIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type ActiveCurrencyAndAmount struct {
	Value float64            `xml:",chardata"`
	Ccy   ActiveCurrencyCode `xml:"Ccy,attr"`
}

// Must match the pattern [A-Z]{3,3}
type ActiveCurrencyCode string

type ActiveOrHistoricCurrencyAndAmount struct {
	Value float64                      `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode `xml:"Ccy,attr"`
}

// Must match the pattern [A-Z]{3,3}
type ActiveOrHistoricCurrencyCode string

// May be one of ADDR, PBOX, HOME, BIZZ, MLTO, DLVY
type AddressType2Code string

type AddressType3Choice struct {
	Cd    AddressType2Code        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type AmendmentInformationDetails15 struct {
	OrgnlMndtId      Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlMndtId,omitempty"`
	OrgnlCdtrSchmeId PartyIdentification272                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlCdtrSchmeId,omitempty"`
	OrgnlCdtrAgt     BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlCdtrAgt,omitempty"`
	OrgnlCdtrAgtAcct CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlCdtrAgtAcct,omitempty"`
	OrgnlDbtr        PartyIdentification272                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlDbtr,omitempty"`
	OrgnlDbtrAcct    CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlDbtrAcct,omitempty"`
	OrgnlDbtrAgt     BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlDbtrAgt,omitempty"`
	OrgnlDbtrAgtAcct CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlDbtrAgtAcct,omitempty"`
	OrgnlFnlColltnDt ISODate                                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlFnlColltnDt,omitempty"`
	OrgnlFrqcy       Frequency36Choice                            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlFrqcy,omitempty"`
	OrgnlRsn         MandateSetupReason1Choice                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlRsn,omitempty"`
	OrgnlTrckgDays   Exact2NumericText                            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlTrckgDays,omitempty"`
}

type AmountType4Choice struct {
	InstdAmt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstdAmt,omitempty"`
	EqvtAmt  EquivalentAmount2                 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 EqvtAmt,omitempty"`
}

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type AnyBICDec2014Identifier string

type Authorisation1Choice struct {
	Cd    Authorisation1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max128Text         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

// May be one of AUTH, FDET, FSUM, ILEV
type Authorisation1Code string

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type BICFIDec2014Identifier string

type BranchAndFinancialInstitutionIdentification8 struct {
	FinInstnId FinancialInstitutionIdentification23 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 FinInstnId"`
	BrnchId    BranchData5                          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 BrnchId,omitempty"`
}

type BranchData5 struct {
	Id      Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Id,omitempty"`
	LEI     LEIIdentifier   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 LEI,omitempty"`
	Nm      Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Nm,omitempty"`
	PstlAdr PostalAddress27 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PstlAdr,omitempty"`
}

type CashAccount40 struct {
	Id   AccountIdentification4Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Id,omitempty"`
	Tp   CashAccountType2Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp,omitempty"`
	Ccy  ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Ccy,omitempty"`
	Nm   Max70Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Nm,omitempty"`
	Prxy ProxyAccountIdentification1  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prxy,omitempty"`
}

type CashAccountType2Choice struct {
	Cd    ExternalCashAccountType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type CategoryPurpose1Choice struct {
	Cd    ExternalCategoryPurpose1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

// May be one of DEBT, CRED, SHAR, SLEV
type ChargeBearerType1Code string

type ChargeType3Choice struct {
	Cd    ExternalChargeType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry GenericIdentification3  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type Charges16 struct {
	Amt ActiveOrHistoricCurrencyAndAmount            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Amt"`
	Agt BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Agt"`
	Tp  ChargeType3Choice                            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp,omitempty"`
}

// May be one of RTGS, RTNS, MPNS, BOOK
type ClearingChannel2Code string

type ClearingSystemIdentification2Choice struct {
	Cd    ExternalClearingSystemIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                                 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type ClearingSystemIdentification3Choice struct {
	Cd    ExternalCashClearingSystem1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type ClearingSystemMemberIdentification2 struct {
	ClrSysId ClearingSystemIdentification2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ClrSysId,omitempty"`
	MmbId    Max35Text                           `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 MmbId"`
}

type Contact13 struct {
	NmPrfx    NamePrefix2Code             `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 NmPrfx,omitempty"`
	Nm        Max140Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Nm,omitempty"`
	PhneNb    PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PhneNb,omitempty"`
	MobNb     PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 MobNb,omitempty"`
	FaxNb     PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 FaxNb,omitempty"`
	URLAdr    Max2048Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 URLAdr,omitempty"`
	EmailAdr  Max256Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 EmailAdr,omitempty"`
	EmailPurp Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 EmailPurp,omitempty"`
	JobTitl   Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 JobTitl,omitempty"`
	Rspnsblty Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Rspnsblty,omitempty"`
	Dept      Max70Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Dept,omitempty"`
	Othr      []OtherContact1             `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Othr,omitempty"`
	PrefrdMtd PreferredContactMethod2Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrefrdMtd,omitempty"`
}

// Must match the pattern [A-Z]{2,2}
type CountryCode string

// May be one of CRDT, DBIT
type CreditDebitCode string

type CreditTransferMandateData1 struct {
	MndtId       Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 MndtId,omitempty"`
	Tp           MandateTypeInformation2   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp,omitempty"`
	DtOfSgntr    ISODate                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DtOfSgntr,omitempty"`
	DtOfVrfctn   ISODateTime               `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DtOfVrfctn,omitempty"`
	ElctrncSgntr Max10KBinary              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ElctrncSgntr,omitempty"`
	FrstPmtDt    ISODate                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 FrstPmtDt,omitempty"`
	FnlPmtDt     ISODate                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 FnlPmtDt,omitempty"`
	Frqcy        Frequency36Choice         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Frqcy,omitempty"`
	Rsn          MandateSetupReason1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Rsn,omitempty"`
}

type CreditTransferTransaction72 struct {
	PmtId             PaymentIdentification13                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PmtId,omitempty"`
	PmtTpInf          PaymentTypeInformation28                     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PmtTpInf,omitempty"`
	UltmtDbtr         PartyIdentification272                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UltmtDbtr,omitempty"`
	InitgPty          PartyIdentification272                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InitgPty,omitempty"`
	Dbtr              PartyIdentification272                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Dbtr"`
	DbtrAcct          CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DbtrAcct,omitempty"`
	DbtrAgt           BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DbtrAgt"`
	DbtrAgtAcct       CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DbtrAgtAcct,omitempty"`
	PrvsInstgAgt1     BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt1,omitempty"`
	PrvsInstgAgt1Acct CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt1Acct,omitempty"`
	PrvsInstgAgt2     BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt2,omitempty"`
	PrvsInstgAgt2Acct CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt2Acct,omitempty"`
	PrvsInstgAgt3     BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt3,omitempty"`
	PrvsInstgAgt3Acct CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt3Acct,omitempty"`
	IntrmyAgt1        BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt1,omitempty"`
	IntrmyAgt1Acct    CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt1Acct,omitempty"`
	IntrmyAgt2        BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt2,omitempty"`
	IntrmyAgt2Acct    CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt2Acct,omitempty"`
	IntrmyAgt3        BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt3,omitempty"`
	IntrmyAgt3Acct    CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt3Acct,omitempty"`
	CdtrAgt           BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtrAgt"`
	CdtrAgtAcct       CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtrAgtAcct,omitempty"`
	Cdtr              PartyIdentification272                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cdtr"`
	CdtrAcct          CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtrAcct,omitempty"`
	UltmtCdtr         PartyIdentification272                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UltmtCdtr,omitempty"`
	InstrForCdtrAgt   []InstructionForCreditorAgent3               `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstrForCdtrAgt,omitempty"`
	InstrForNxtAgt    []InstructionForNextAgent1                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstrForNxtAgt,omitempty"`
	Purp              Purpose2Choice                               `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Purp,omitempty"`
	Tax               TaxData1                                     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tax,omitempty"`
	RmtInf            RemittanceInformation26                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RmtInf,omitempty"`
	InstdAmt          ActiveOrHistoricCurrencyAndAmount            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstdAmt,omitempty"`
}

type CreditTransferTransaction82 struct {
	PmtId             PaymentIdentification13                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PmtId"`
	PmtTpInf          PaymentTypeInformation28                     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PmtTpInf,omitempty"`
	IntrBkSttlmAmt    ActiveCurrencyAndAmount                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrBkSttlmAmt"`
	IntrBkSttlmDt     ISODate                                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrBkSttlmDt,omitempty"`
	SttlmPrty         Priority3Code                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SttlmPrty,omitempty"`
	SttlmTmIndctn     SettlementDateTimeIndication1                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SttlmTmIndctn,omitempty"`
	SttlmTmReq        SettlementTimeRequest2                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SttlmTmReq,omitempty"`
	XpryDtTm          ISODateTime                                  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 XpryDtTm,omitempty"`
	PmtSgntr          CryptographicKey1Choice                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PmtSgntr,omitempty"`
	PrvsInstgAgt1     BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt1,omitempty"`
	PrvsInstgAgt1Acct CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt1Acct,omitempty"`
	PrvsInstgAgt2     BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt2,omitempty"`
	PrvsInstgAgt2Acct CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt2Acct,omitempty"`
	PrvsInstgAgt3     BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt3,omitempty"`
	PrvsInstgAgt3Acct CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt3Acct,omitempty"`
	InstgAgt          BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstgAgt,omitempty"`
	InstdAgt          BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstdAgt,omitempty"`
	IntrmyAgt1        BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt1,omitempty"`
	IntrmyAgt1Acct    CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt1Acct,omitempty"`
	IntrmyAgt2        BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt2,omitempty"`
	IntrmyAgt2Acct    CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt2Acct,omitempty"`
	IntrmyAgt3        BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt3,omitempty"`
	IntrmyAgt3Acct    CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt3Acct,omitempty"`
	UltmtDbtr         BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UltmtDbtr,omitempty"`
	Dbtr              BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Dbtr"`
	DbtrAcct          CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DbtrAcct,omitempty"`
	DbtrAgt           BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DbtrAgt,omitempty"`
	DbtrAgtAcct       CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DbtrAgtAcct,omitempty"`
	CdtrAgt           BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtrAgt,omitempty"`
	CdtrAgtAcct       CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtrAgtAcct,omitempty"`
	Cdtr              BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cdtr"`
	CdtrAcct          CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtrAcct,omitempty"`
	UltmtCdtr         BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UltmtCdtr,omitempty"`
	InstrForCdtrAgt   []InstructionForCreditorAgent3               `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstrForCdtrAgt,omitempty"`
	InstrForNxtAgt    []InstructionForNextAgent1                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstrForNxtAgt,omitempty"`
	Purp              Purpose2Choice                               `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Purp,omitempty"`
	RmtInf            RemittanceInformation2                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RmtInf,omitempty"`
	UndrlygAllcn      []TransactionAllocation2                     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UndrlygAllcn,omitempty"`
}

type CreditorReferenceInformation3 struct {
	Tp  CreditorReferenceType3 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp,omitempty"`
	Ref Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Ref,omitempty"`
}

type CreditorReferenceType2Choice struct {
	Cd    ExternalCreditorReferenceType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type CreditorReferenceType3 struct {
	CdOrPrtry CreditorReferenceType2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdOrPrtry"`
	Issr      Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Issr,omitempty"`
}

type CryptographicKey1Choice struct {
	ILPV4 HexBinaryText       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ILPV4,omitempty"`
	Sgntr SHA256SignatureText `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Sgntr,omitempty"`
}

type CurrencyExchange26 struct {
	UnitCcy         ActiveOrHistoricCurrencyCode                 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UnitCcy,omitempty"`
	QtdCcy          ActiveOrHistoricCurrencyCode                 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 QtdCcy,omitempty"`
	PreAgrdXchgRate float64                                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PreAgrdXchgRate"`
	QtnDtTm         ISODateTime                                  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 QtnDtTm,omitempty"`
	QtId            UUIDv4Identifier                             `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 QtId,omitempty"`
	FXAgt           BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 FXAgt,omitempty"`
}

type DateAndDateTime2Choice struct {
	Dt   ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Dt,omitempty"`
	DtTm ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DtTm,omitempty"`
}

type DateAndPlaceOfBirth1 struct {
	BirthDt     ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 BirthDt"`
	PrvcOfBirth Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvcOfBirth,omitempty"`
	CityOfBirth Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CityOfBirth"`
	CtryOfBirth CountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CtryOfBirth"`
}

type DateAndType1 struct {
	Tp DateType2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp"`
	Dt ISODate         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Dt"`
}

type DatePeriod2 struct {
	FrDt ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 FrDt"`
	ToDt ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ToDt"`
}

type DateType2Choice struct {
	Cd    ExternalDateType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type Document struct {
	PmtRtr PaymentReturnV15 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PmtRtr"`
}

type DocumentAdjustment1 struct {
	Amt       ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Amt"`
	CdtDbtInd CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtDbtInd,omitempty"`
	Rsn       Max4Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Rsn,omitempty"`
	AddtlInf  Max140Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 AddtlInf,omitempty"`
}

type DocumentAmount1 struct {
	Tp  DocumentAmountType1Choice         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp"`
	Amt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Amt"`
}

type DocumentAmountType1Choice struct {
	Cd    ExternalDocumentAmountType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type DocumentLineIdentification1 struct {
	Tp     DocumentLineType1 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp,omitempty"`
	Nb     Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Nb,omitempty"`
	RltdDt ISODate           `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RltdDt,omitempty"`
}

type DocumentLineInformation2 struct {
	Id   []DocumentLineIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Id"`
	Desc Max2048Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Desc,omitempty"`
	Amt  RemittanceAmount4             `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Amt,omitempty"`
}

type DocumentLineType1 struct {
	CdOrPrtry DocumentLineType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdOrPrtry"`
	Issr      Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Issr,omitempty"`
}

type DocumentLineType1Choice struct {
	Cd    ExternalDocumentLineType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type DocumentType1 struct {
	CdOrPrtry DocumentType2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdOrPrtry"`
	Issr      Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Issr,omitempty"`
}

type DocumentType2Choice struct {
	Cd    ExternalDocumentType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type EquivalentAmount2 struct {
	Amt      ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Amt"`
	CcyOfTrf ActiveOrHistoricCurrencyCode      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CcyOfTrf"`
}

// Must match the pattern [0-9]{2}
type Exact2NumericText string

// Must match the pattern [a-zA-Z0-9]{4}
type Exact4AlphaNumericText string

// May be no more than 4 items long
type ExternalAccountIdentification1Code string

// May be no more than 4 items long
type ExternalCashAccountType1Code string

// May be no more than 3 items long
type ExternalCashClearingSystem1Code string

// May be no more than 4 items long
type ExternalCategoryPurpose1Code string

// May be no more than 4 items long
type ExternalChargeType1Code string

// May be no more than 5 items long
type ExternalClearingSystemIdentification1Code string

// May be no more than 4 items long
type ExternalCreditorAgentInstruction1Code string

// May be no more than 4 items long
type ExternalCreditorReferenceType1Code string

// May be no more than 4 items long
type ExternalDateType1Code string

// May be no more than 4 items long
type ExternalDocumentAmountType1Code string

// May be no more than 4 items long
type ExternalDocumentLineType1Code string

// May be no more than 4 items long
type ExternalDocumentType1Code string

// May be no more than 4 items long
type ExternalFinancialInstitutionIdentification1Code string

// May be no more than 4 items long
type ExternalGarnishmentType1Code string

// May be no more than 35 items long
type ExternalLocalInstrument1Code string

// May be no more than 4 items long
type ExternalMandateSetupReason1Code string

// May be no more than 4 items long
type ExternalOrganisationIdentification1Code string

// May be no more than 4 items long
type ExternalPersonIdentification1Code string

// May be no more than 4 items long
type ExternalProxyAccountType1Code string

// May be no more than 4 items long
type ExternalPurpose1Code string

// May be no more than 4 items long
type ExternalReturnReason1Code string

// May be no more than 4 items long
type ExternalServiceLevel1Code string

type FinancialIdentificationSchemeName1Choice struct {
	Cd    ExternalFinancialInstitutionIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type FinancialInstitutionIdentification23 struct {
	BICFI       BICFIDec2014Identifier              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 BICFI,omitempty"`
	ClrSysMmbId ClearingSystemMemberIdentification2 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ClrSysMmbId,omitempty"`
	LEI         LEIIdentifier                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 LEI,omitempty"`
	Nm          Max140Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Nm,omitempty"`
	PstlAdr     PostalAddress27                     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PstlAdr,omitempty"`
	Othr        GenericFinancialIdentification1     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Othr,omitempty"`
}

type Frequency36Choice struct {
	Tp     Frequency6Code      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp,omitempty"`
	Prd    FrequencyPeriod1    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prd,omitempty"`
	PtInTm FrequencyAndMoment1 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PtInTm,omitempty"`
}

// May be one of YEAR, MNTH, QURT, MIAN, WEEK, DAIL, ADHO, INDA, FRTN
type Frequency6Code string

type FrequencyAndMoment1 struct {
	Tp     Frequency6Code    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp"`
	PtInTm Exact2NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PtInTm"`
}

type FrequencyPeriod1 struct {
	Tp        Frequency6Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp"`
	CntPerPrd float64        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CntPerPrd"`
}

type Garnishment4 struct {
	Tp                GarnishmentType1                  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp"`
	Grnshee           PartyIdentification272            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Grnshee,omitempty"`
	GrnshmtAdmstr     PartyIdentification272            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 GrnshmtAdmstr,omitempty"`
	RefNb             Max140Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RefNb,omitempty"`
	Dt                ISODate                           `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Dt,omitempty"`
	RmtdAmt           ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RmtdAmt,omitempty"`
	FmlyMdclInsrncInd bool                              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 FmlyMdclInsrncInd,omitempty"`
	MplyeeTermntnInd  bool                              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 MplyeeTermntnInd,omitempty"`
}

type GarnishmentType1 struct {
	CdOrPrtry GarnishmentType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdOrPrtry"`
	Issr      Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Issr,omitempty"`
}

type GarnishmentType1Choice struct {
	Cd    ExternalGarnishmentType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type GenericAccountIdentification1 struct {
	Id      Max34Text                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Id"`
	SchmeNm AccountSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SchmeNm,omitempty"`
	Issr    Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Issr,omitempty"`
}

type GenericFinancialIdentification1 struct {
	Id      Max35Text                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Id"`
	SchmeNm FinancialIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SchmeNm,omitempty"`
	Issr    Max35Text                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Issr,omitempty"`
}

type GenericIdentification3 struct {
	Id   Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Id"`
	Issr Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Issr,omitempty"`
}

type GenericIdentification30 struct {
	Id      Exact4AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Id"`
	Issr    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Issr"`
	SchmeNm Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SchmeNm,omitempty"`
}

type GenericOrganisationIdentification3 struct {
	Id      Max256Text                                  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Id"`
	SchmeNm OrganisationIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SchmeNm,omitempty"`
	Issr    Max35Text                                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Issr,omitempty"`
}

type GenericPersonIdentification2 struct {
	Id      Max256Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Id"`
	SchmeNm PersonIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SchmeNm,omitempty"`
	Issr    Max35Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Issr,omitempty"`
}

type GroupHeader123 struct {
	MsgId                 Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 MsgId"`
	CreDtTm               ISODateTime                                  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CreDtTm"`
	Authstn               []Authorisation1Choice                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Authstn,omitempty"`
	BtchBookg             bool                                         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 BtchBookg,omitempty"`
	NbOfTxs               Max15NumericText                             `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 NbOfTxs"`
	CtrlSum               float64                                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CtrlSum,omitempty"`
	GrpRtr                bool                                         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 GrpRtr,omitempty"`
	TtlRtrdIntrBkSttlmAmt ActiveCurrencyAndAmount                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TtlRtrdIntrBkSttlmAmt,omitempty"`
	IntrBkSttlmDt         ISODate                                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrBkSttlmDt,omitempty"`
	SttlmInf              SettlementInstruction15                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SttlmInf"`
	PmtTpInf              PaymentTypeInformation28                     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PmtTpInf,omitempty"`
	InstgAgt              BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstgAgt,omitempty"`
	InstdAgt              BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstdAgt,omitempty"`
}

// Must match the pattern [0-9a-fA-F]+
type HexBinaryText string

// Must match the pattern [A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}
type IBAN2007Identifier string

type ISODate time.Time

func (t *ISODate) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t ISODate) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type ISODateTime time.Time

func (t *ISODateTime) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t ISODateTime) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

type ISOTime time.Time

func (t *ISOTime) UnmarshalText(text []byte) error {
	return (*xsdTime)(t).UnmarshalText(text)
}
func (t ISOTime) MarshalText() ([]byte, error) {
	return xsdTime(t).MarshalText()
}

type ISOYear time.Time

func (t *ISOYear) UnmarshalText(text []byte) error {
	return (*xsdGYear)(t).UnmarshalText(text)
}
func (t ISOYear) MarshalText() ([]byte, error) {
	return xsdGYear(t).MarshalText()
}

// May be one of PHOA, TELA
type Instruction4Code string

type InstructionForCreditorAgent3 struct {
	Cd       ExternalCreditorAgentInstruction1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	InstrInf Max140Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstrInf,omitempty"`
}

type InstructionForNextAgent1 struct {
	Cd       Instruction4Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	InstrInf Max140Text       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstrInf,omitempty"`
}

// Must match the pattern [A-Z0-9]{18,18}[0-9]{2,2}
type LEIIdentifier string

type LocalInstrument2Choice struct {
	Cd    ExternalLocalInstrument1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type MandateClassification1Choice struct {
	Cd    MandateClassification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

// May be one of FIXE, USGB, VARI
type MandateClassification1Code string

type MandateRelatedData5Choice struct {
	DrctDbtMndt MandateRelatedInformation16 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DrctDbtMndt,omitempty"`
	CdtTrfMndt  CreditTransferMandateData1  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtTrfMndt,omitempty"`
}

type MandateRelatedInformation16 struct {
	MndtId        Max35Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 MndtId,omitempty"`
	DtOfSgntr     ISODate                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DtOfSgntr,omitempty"`
	AmdmntInd     bool                          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 AmdmntInd,omitempty"`
	AmdmntInfDtls AmendmentInformationDetails15 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 AmdmntInfDtls,omitempty"`
	ElctrncSgntr  Max1025Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ElctrncSgntr,omitempty"`
	FrstColltnDt  ISODate                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 FrstColltnDt,omitempty"`
	FnlColltnDt   ISODate                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 FnlColltnDt,omitempty"`
	Frqcy         Frequency36Choice             `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Frqcy,omitempty"`
	Rsn           MandateSetupReason1Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Rsn,omitempty"`
	TrckgDays     Exact2NumericText             `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TrckgDays,omitempty"`
}

type MandateSetupReason1Choice struct {
	Cd    ExternalMandateSetupReason1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max70Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type MandateTypeInformation2 struct {
	SvcLvl    ServiceLevel8Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SvcLvl,omitempty"`
	LclInstrm LocalInstrument2Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 LclInstrm,omitempty"`
	CtgyPurp  CategoryPurpose1Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CtgyPurp,omitempty"`
	Clssfctn  MandateClassification1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Clssfctn,omitempty"`
}

// May be no more than 1025 items long
type Max1025Text string

// May be no more than 105 items long
type Max105Text string

type Max10KBinary []byte

func (t *Max10KBinary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max10KBinary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be no more than 128 items long
type Max128Text string

// May be no more than 140 items long
type Max140Text string

// Must match the pattern [0-9]{1,15}
type Max15NumericText string

// May be no more than 16 items long
type Max16Text string

// May be no more than 2048 items long
type Max2048Text string

// May be no more than 256 items long
type Max256Text string

// May be no more than 34 items long
type Max34Text string

// May be no more than 350 items long
type Max350Text string

// May be no more than 35 items long
type Max35Text string

// May be no more than 4 items long
type Max4Text string

// May be no more than 70 items long
type Max70Text string

// May be one of DOCT, MADM, MISS, MIST, MIKS
type NamePrefix2Code string

type OrganisationIdentification39 struct {
	AnyBIC AnyBICDec2014Identifier              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 AnyBIC,omitempty"`
	LEI    LEIIdentifier                        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 LEI,omitempty"`
	Othr   []GenericOrganisationIdentification3 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Othr,omitempty"`
}

type OrganisationIdentificationSchemeName1Choice struct {
	Cd    ExternalOrganisationIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                               `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type OriginalGroupHeader19 struct {
	OrgnlMsgId   Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlMsgId"`
	OrgnlMsgNmId Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlMsgNmId"`
	OrgnlCreDtTm ISODateTime            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlCreDtTm,omitempty"`
	RtrRsnInf    []PaymentReturnReason7 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RtrRsnInf,omitempty"`
}

type OriginalGroupInformation33 struct {
	OrgnlMsgId   Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlMsgId"`
	OrgnlMsgNmId Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlMsgNmId"`
	OrgnlCreDtTm ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlCreDtTm,omitempty"`
}

type OriginalTransactionReference45 struct {
	IntrBkSttlmAmt     ActiveOrHistoricCurrencyAndAmount            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrBkSttlmAmt,omitempty"`
	Amt                AmountType4Choice                            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Amt,omitempty"`
	IntrBkSttlmDt      ISODate                                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrBkSttlmDt,omitempty"`
	ReqdColltnDt       ISODate                                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ReqdColltnDt,omitempty"`
	ReqdExctnDt        DateAndDateTime2Choice                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ReqdExctnDt,omitempty"`
	CdtrSchmeId        PartyIdentification272                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtrSchmeId,omitempty"`
	SttlmInf           SettlementInstruction15                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SttlmInf,omitempty"`
	PmtTpInf           PaymentTypeInformation27                     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PmtTpInf,omitempty"`
	PmtMtd             PaymentMethod4Code                           `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PmtMtd,omitempty"`
	MndtRltdInf        MandateRelatedData5Choice                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 MndtRltdInf,omitempty"`
	RmtInf             RemittanceInformation26                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RmtInf,omitempty"`
	UltmtDbtr          Party50Choice                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UltmtDbtr,omitempty"`
	Dbtr               Party50Choice                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Dbtr,omitempty"`
	DbtrAcct           CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DbtrAcct,omitempty"`
	DbtrAgt            BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DbtrAgt,omitempty"`
	DbtrAgtAcct        CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DbtrAgtAcct,omitempty"`
	CdtrAgt            BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtrAgt,omitempty"`
	CdtrAgtAcct        CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtrAgtAcct,omitempty"`
	Cdtr               Party50Choice                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cdtr,omitempty"`
	CdtrAcct           CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtrAcct,omitempty"`
	UltmtCdtr          Party50Choice                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UltmtCdtr,omitempty"`
	Purp               Purpose2Choice                               `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Purp,omitempty"`
	UndrlygCstmrCdtTrf CreditTransferTransaction72                  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UndrlygCstmrCdtTrf,omitempty"`
	UndrlygFICdtTrf    CreditTransferTransaction82                  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UndrlygFICdtTrf,omitempty"`
}

type OtherContact1 struct {
	ChanlTp Max4Text   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ChanlTp"`
	Id      Max128Text `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Id,omitempty"`
}

type Party50Choice struct {
	Pty PartyIdentification272                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Pty,omitempty"`
	Agt BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Agt,omitempty"`
}

type Party52Choice struct {
	OrgId  OrganisationIdentification39 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgId,omitempty"`
	PrvtId PersonIdentification18       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvtId,omitempty"`
}

type PartyIdentification272 struct {
	Nm        Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Nm,omitempty"`
	PstlAdr   PostalAddress27 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PstlAdr,omitempty"`
	Id        Party52Choice   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Id,omitempty"`
	CtryOfRes CountryCode     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CtryOfRes,omitempty"`
	CtctDtls  Contact13       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CtctDtls,omitempty"`
}

type PaymentIdentification13 struct {
	InstrId    Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstrId,omitempty"`
	EndToEndId Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 EndToEndId"`
	TxId       Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TxId,omitempty"`
	UETR       UUIDv4Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UETR,omitempty"`
	ClrSysRef  Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ClrSysRef,omitempty"`
}

// May be one of CHK, TRF, DD, TRA
type PaymentMethod4Code string

type PaymentReturnReason7 struct {
	Orgtr    PartyIdentification272 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Orgtr,omitempty"`
	Rsn      ReturnReason5Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Rsn,omitempty"`
	AddtlInf []Max105Text           `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 AddtlInf,omitempty"`
}

type PaymentReturnV15 struct {
	GrpHdr      GroupHeader123          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 GrpHdr"`
	OrgnlGrpInf OriginalGroupHeader19   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlGrpInf,omitempty"`
	TxInf       []PaymentTransaction168 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TxInf,omitempty"`
	SplmtryData []SupplementaryData1    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SplmtryData,omitempty"`
}

type PaymentTransaction168 struct {
	RtrId               Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RtrId,omitempty"`
	OrgnlGrpInf         OriginalGroupInformation33                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlGrpInf,omitempty"`
	OrgnlInstrId        Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlInstrId,omitempty"`
	OrgnlEndToEndId     Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlEndToEndId,omitempty"`
	OrgnlTxId           Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlTxId,omitempty"`
	OrgnlUETR           UUIDv4Identifier                             `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlUETR,omitempty"`
	OrgnlClrSysRef      Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlClrSysRef,omitempty"`
	OrgnlIntrBkSttlmAmt ActiveOrHistoricCurrencyAndAmount            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlIntrBkSttlmAmt,omitempty"`
	OrgnlIntrBkSttlmDt  ISODate                                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlIntrBkSttlmDt,omitempty"`
	PmtTpInf            PaymentTypeInformation28                     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PmtTpInf,omitempty"`
	RtrdIntrBkSttlmAmt  ActiveCurrencyAndAmount                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RtrdIntrBkSttlmAmt"`
	IntrBkSttlmDt       ISODate                                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrBkSttlmDt,omitempty"`
	SttlmPrty           Priority3Code                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SttlmPrty,omitempty"`
	SttlmTmIndctn       SettlementDateTimeIndication1                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SttlmTmIndctn,omitempty"`
	SttlmTmReq          SettlementTimeRequest2                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SttlmTmReq,omitempty"`
	RtrdInstdAmt        ActiveOrHistoricCurrencyAndAmount            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RtrdInstdAmt,omitempty"`
	XchgRate            float64                                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 XchgRate,omitempty"`
	AgrdRate            CurrencyExchange26                           `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 AgrdRate,omitempty"`
	CompstnAmt          ActiveOrHistoricCurrencyAndAmount            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CompstnAmt,omitempty"`
	ChrgBr              ChargeBearerType1Code                        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ChrgBr,omitempty"`
	ChrgsInf            []Charges16                                  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ChrgsInf,omitempty"`
	ClrSysRef           Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ClrSysRef,omitempty"`
	InstgAgt            BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstgAgt,omitempty"`
	InstdAgt            BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstdAgt,omitempty"`
	RtrChain            TransactionParties11                         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RtrChain,omitempty"`
	RtrRsnInf           []PaymentReturnReason7                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RtrRsnInf,omitempty"`
	OrgnlTxRef          OriginalTransactionReference45               `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OrgnlTxRef,omitempty"`
	SplmtryData         []SupplementaryData1                         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SplmtryData,omitempty"`
}

type PaymentTypeInformation27 struct {
	InstrPrty Priority2Code          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstrPrty,omitempty"`
	ClrChanl  ClearingChannel2Code   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ClrChanl,omitempty"`
	SvcLvl    []ServiceLevel8Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SvcLvl,omitempty"`
	LclInstrm LocalInstrument2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 LclInstrm,omitempty"`
	SeqTp     SequenceType3Code      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SeqTp,omitempty"`
	CtgyPurp  CategoryPurpose1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CtgyPurp,omitempty"`
}

type PaymentTypeInformation28 struct {
	InstrPrty Priority2Code          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstrPrty,omitempty"`
	ClrChanl  ClearingChannel2Code   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ClrChanl,omitempty"`
	SvcLvl    []ServiceLevel8Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SvcLvl,omitempty"`
	LclInstrm LocalInstrument2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 LclInstrm,omitempty"`
	CtgyPurp  CategoryPurpose1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CtgyPurp,omitempty"`
}

type PersonIdentification18 struct {
	DtAndPlcOfBirth DateAndPlaceOfBirth1           `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DtAndPlcOfBirth,omitempty"`
	Othr            []GenericPersonIdentification2 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Othr,omitempty"`
}

type PersonIdentificationSchemeName1Choice struct {
	Cd    ExternalPersonIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

// Must match the pattern \+[0-9]{1,3}-[0-9()+\-]{1,30}
type PhoneNumber string

type PostalAddress27 struct {
	AdrTp       AddressType3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 AdrTp,omitempty"`
	CareOf      Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CareOf,omitempty"`
	Dept        Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Dept,omitempty"`
	SubDept     Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SubDept,omitempty"`
	StrtNm      Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 StrtNm,omitempty"`
	BldgNb      Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 BldgNb,omitempty"`
	BldgNm      Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 BldgNm,omitempty"`
	Flr         Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Flr,omitempty"`
	UnitNb      Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UnitNb,omitempty"`
	PstBx       Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PstBx,omitempty"`
	Room        Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Room,omitempty"`
	PstCd       Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PstCd,omitempty"`
	TwnNm       Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TwnNm,omitempty"`
	TwnLctnNm   Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TwnLctnNm,omitempty"`
	DstrctNm    Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DstrctNm,omitempty"`
	CtrySubDvsn Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CtrySubDvsn,omitempty"`
	Ctry        CountryCode        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Ctry,omitempty"`
	AdrLine     []Max70Text        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 AdrLine,omitempty"`
}

// May be one of MAIL, FAXX, LETT, CELL, ONLI, PHON
type PreferredContactMethod2Code string

// May be one of HIGH, NORM
type Priority2Code string

// May be one of URGT, HIGH, NORM
type Priority3Code string

type ProxyAccountIdentification1 struct {
	Tp ProxyAccountType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp,omitempty"`
	Id Max2048Text             `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Id"`
}

type ProxyAccountType1Choice struct {
	Cd    ExternalProxyAccountType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type Purpose2Choice struct {
	Cd    ExternalPurpose1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type References80Choice struct {
	SctiesSttlmTxId         Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SctiesSttlmTxId,omitempty"`
	IntraPosMvmntId         Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntraPosMvmntId,omitempty"`
	IntraBalMvmntId         Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntraBalMvmntId,omitempty"`
	AcctSvcrTxId            Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 AcctSvcrTxId,omitempty"`
	MktInfrstrctrTxId       Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 MktInfrstrctrTxId,omitempty"`
	CtrPtyMktInfrstrctrTxId Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CtrPtyMktInfrstrctrTxId,omitempty"`
	PoolId                  Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PoolId,omitempty"`
	CmonId                  Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CmonId,omitempty"`
	TradId                  Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TradId,omitempty"`
	UnqTxIdr                UTIIdentifier `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UnqTxIdr,omitempty"`
	OthrTxId                Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 OthrTxId,omitempty"`
}

type ReferredDocumentInformation8 struct {
	Tp       DocumentType1              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp,omitempty"`
	Nb       Max35Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Nb,omitempty"`
	RltdDt   DateAndType1               `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RltdDt,omitempty"`
	LineDtls []DocumentLineInformation2 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 LineDtls,omitempty"`
}

type RemittanceAmount4 struct {
	RmtAmtAndTp       []DocumentAmount1     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RmtAmtAndTp,omitempty"`
	AdjstmntAmtAndRsn []DocumentAdjustment1 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 AdjstmntAmtAndRsn,omitempty"`
}

type RemittanceInformation2 struct {
	Ustrd []Max140Text `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Ustrd,omitempty"`
}

type RemittanceInformation26 struct {
	Ustrd []Max140Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Ustrd,omitempty"`
	Strd  []StructuredRemittanceInformation22 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Strd,omitempty"`
}

type ReturnReason5Choice struct {
	Cd    ExternalReturnReason1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

// Must match the pattern ([0-9A-F][0-9A-F]){32}
type SHA256SignatureText string

type SecuritiesAttributes1 struct {
	UnqTxIdr UTIIdentifier           `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UnqTxIdr"`
	Amt      ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Amt,omitempty"`
}

// May be one of FRST, RCUR, FNAL, OOFF, RPRE
type SequenceType3Code string

type ServiceLevel8Choice struct {
	Cd    ExternalServiceLevel1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cd,omitempty"`
	Prtry Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prtry,omitempty"`
}

type SettlementDateTimeIndication1 struct {
	DbtDtTm ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DbtDtTm,omitempty"`
	CdtDtTm ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtDtTm,omitempty"`
}

type SettlementInstruction15 struct {
	SttlmMtd             SettlementMethod1Code                        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SttlmMtd"`
	SttlmAcct            CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SttlmAcct,omitempty"`
	ClrSys               ClearingSystemIdentification3Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ClrSys,omitempty"`
	InstgRmbrsmntAgt     BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstgRmbrsmntAgt,omitempty"`
	InstgRmbrsmntAgtAcct CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstgRmbrsmntAgtAcct,omitempty"`
	InstdRmbrsmntAgt     BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstdRmbrsmntAgt,omitempty"`
	InstdRmbrsmntAgtAcct CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InstdRmbrsmntAgtAcct,omitempty"`
	ThrdRmbrsmntAgt      BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ThrdRmbrsmntAgt,omitempty"`
	ThrdRmbrsmntAgtAcct  CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 ThrdRmbrsmntAgtAcct,omitempty"`
}

// May be one of INDA, INGA, COVE, CLRG
type SettlementMethod1Code string

type SettlementTimeRequest2 struct {
	CLSTm  ISOTime `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CLSTm,omitempty"`
	TillTm ISOTime `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TillTm,omitempty"`
	FrTm   ISOTime `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 FrTm,omitempty"`
	RjctTm ISOTime `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RjctTm,omitempty"`
}

type StructuredRemittanceInformation22 struct {
	RfrdDocInf  []ReferredDocumentInformation8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RfrdDocInf,omitempty"`
	RfrdDocAmt  RemittanceAmount4              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RfrdDocAmt,omitempty"`
	CdtrRefInf  CreditorReferenceInformation3  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtrRefInf,omitempty"`
	Invcr       PartyIdentification272         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Invcr,omitempty"`
	Invcee      PartyIdentification272         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Invcee,omitempty"`
	TaxRmt      TaxData1                       `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TaxRmt,omitempty"`
	GrnshmtRmt  Garnishment4                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 GrnshmtRmt,omitempty"`
	SctiesData  []SecuritiesAttributes1        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SctiesData,omitempty"`
	AddtlRmtInf []Max140Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 AddtlRmtInf,omitempty"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type TaxAmount3 struct {
	Rate         float64                           `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Rate,omitempty"`
	TaxblBaseAmt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TaxblBaseAmt,omitempty"`
	TtlAmt       ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TtlAmt,omitempty"`
	Dtls         []TaxRecordDetails3               `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Dtls,omitempty"`
}

type TaxAuthorisation1 struct {
	Titl Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Titl,omitempty"`
	Nm   Max140Text `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Nm,omitempty"`
}

type TaxData1 struct {
	Cdtr            TaxParty1                         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cdtr,omitempty"`
	Dbtr            TaxParty2                         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Dbtr,omitempty"`
	UltmtDbtr       TaxParty2                         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UltmtDbtr,omitempty"`
	AdmstnZone      Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 AdmstnZone,omitempty"`
	RefNb           Max140Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RefNb,omitempty"`
	Mtd             Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Mtd,omitempty"`
	TtlTaxblBaseAmt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TtlTaxblBaseAmt,omitempty"`
	TtlTaxAmt       ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TtlTaxAmt,omitempty"`
	Dt              ISODate                           `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Dt,omitempty"`
	SeqNb           float64                           `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 SeqNb,omitempty"`
	Rcrd            []TaxRecord3                      `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Rcrd,omitempty"`
}

type TaxParty1 struct {
	TaxId  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TaxId,omitempty"`
	RegnId Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RegnId,omitempty"`
	TaxTp  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TaxTp,omitempty"`
}

type TaxParty2 struct {
	TaxId   Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TaxId,omitempty"`
	RegnId  Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RegnId,omitempty"`
	TaxTp   Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TaxTp,omitempty"`
	Authstn TaxAuthorisation1 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Authstn,omitempty"`
}

type TaxPeriod3 struct {
	Yr     ISOYear              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Yr,omitempty"`
	Tp     TaxRecordPeriod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp,omitempty"`
	FrToDt DatePeriod2          `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 FrToDt,omitempty"`
}

type TaxRecord3 struct {
	Tp       Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Tp,omitempty"`
	Ctgy     Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Ctgy,omitempty"`
	CtgyDtls Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CtgyDtls,omitempty"`
	DbtrSts  Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DbtrSts,omitempty"`
	CertId   Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CertId,omitempty"`
	FrmsCd   Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 FrmsCd,omitempty"`
	Prd      TaxPeriod3 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prd,omitempty"`
	TaxAmt   TaxAmount3 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 TaxAmt,omitempty"`
	AddtlInf Max140Text `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 AddtlInf,omitempty"`
}

type TaxRecordDetails3 struct {
	Prd TaxPeriod3                        `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Prd,omitempty"`
	Amt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Amt"`
}

// May be one of MM01, MM02, MM03, MM04, MM05, MM06, MM07, MM08, MM09, MM10, MM11, MM12, QTR1, QTR2, QTR3, QTR4, HLF1, HLF2
type TaxRecordPeriod1Code string

type TransactionAllocation2 struct {
	Amt       ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Amt"`
	CdtDbtInd CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtDbtInd"`
	Acct      CashAccount40                     `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Acct"`
	Purp      Purpose2Choice                    `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Purp"`
	Ref       Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Ref"`
	RltdRefs  []References80Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 RltdRefs,omitempty"`
}

type TransactionParties11 struct {
	UltmtDbtr         Party50Choice                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UltmtDbtr,omitempty"`
	Dbtr              Party50Choice                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Dbtr"`
	DbtrAcct          CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DbtrAcct,omitempty"`
	InitgPty          Party50Choice                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 InitgPty,omitempty"`
	DbtrAgt           BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DbtrAgt,omitempty"`
	DbtrAgtAcct       CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 DbtrAgtAcct,omitempty"`
	PrvsInstgAgt1     BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt1,omitempty"`
	PrvsInstgAgt1Acct CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt1Acct,omitempty"`
	PrvsInstgAgt2     BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt2,omitempty"`
	PrvsInstgAgt2Acct CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt2Acct,omitempty"`
	PrvsInstgAgt3     BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt3,omitempty"`
	PrvsInstgAgt3Acct CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 PrvsInstgAgt3Acct,omitempty"`
	IntrmyAgt1        BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt1,omitempty"`
	IntrmyAgt1Acct    CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt1Acct,omitempty"`
	IntrmyAgt2        BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt2,omitempty"`
	IntrmyAgt2Acct    CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt2Acct,omitempty"`
	IntrmyAgt3        BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt3,omitempty"`
	IntrmyAgt3Acct    CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 IntrmyAgt3Acct,omitempty"`
	CdtrAgt           BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtrAgt,omitempty"`
	CdtrAgtAcct       CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtrAgtAcct,omitempty"`
	Cdtr              Party50Choice                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 Cdtr"`
	CdtrAcct          CashAccount40                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 CdtrAcct,omitempty"`
	UltmtCdtr         Party50Choice                                `xml:"urn:iso:std:iso:20022:tech:xsd:pacs.004.001.15 UltmtCdtr,omitempty"`
}

// Must match the pattern [A-Z0-9]{18}[0-9]{2}[A-Z0-9]{0,32}
type UTIIdentifier string

// Must match the pattern [a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}
type UUIDv4Identifier string

type xsdBase64Binary []byte

func (b *xsdBase64Binary) UnmarshalText(text []byte) (err error) {
	*b, err = base64.StdEncoding.DecodeString(string(text))
	return
}
func (b xsdBase64Binary) MarshalText() ([]byte, error) {
	var buf bytes.Buffer
	enc := base64.NewEncoder(base64.StdEncoding, &buf)
	enc.Write([]byte(b))
	enc.Close()
	return buf.Bytes(), nil
}

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}

type xsdGYear time.Time

func (t *xsdGYear) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006")
}
func (t xsdGYear) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006")
}
func (t xsdGYear) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdGYear) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}

type xsdTime time.Time

func (t *xsdTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "15:04:05.999999999")
}
func (t xsdTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "15:04:05.999999999")
}
func (t xsdTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
